import {escapeHTML as esc,download} from './shared/common.js';
let dispose=()=>{};
function extension(t,v){if(t.id==='csv-tools')return v.mode==='JSON'?'json':v.mode==='CSV'?'csv':v.mode==='TSV'?'tsv':'txt';if(t.id==='csv-editor')return'csv';if(t.id==='csv-statistics'||t.id==='schema-generator')return'json';if(t.id==='json-tools')return ['Format','Minify','Escape'].includes(v.mode)?'json':'txt';if(t.id==='xml-tools')return v.mode==='Validate'?'txt':'xml';if(t.id==='code-formatter')return{JavaScript:'js',HTML:'html',CSS:'css'}[v.language];if(t.id==='sql-formatter')return'sql';if(t.id==='markdown-tools')return v.mode==='HTML to Markdown'?'md':'html';if(['meta-tags','hreflang-generator'].includes(t.id))return'html';if(t.id==='sitemap-generator')return'xml';if(['gradient-generator','css-design'].includes(t.id))return'css';return'txt';}
export function clearTool(){dispose();dispose=()=>{};}
function field(f){const id='tool-'+f.name, attrs=`id="${id}" name="${f.name}" ${f.optional?'':'required'}`;return `<div class="field"><label for="${id}">${esc(f.label)}</label>${f.multiline?`<textarea ${attrs} rows="5" spellcheck="false">${esc(f.value??'')}</textarea>`:f.type==='select'?`<select ${attrs}>${f.options.map(([v,l])=>`<option value="${esc(v)}" ${String(f.value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:`<input ${attrs} type="${f.type}" ${f.type==='password'?'autocomplete="new-password"':''} value="${esc(f.value??'')}" ${f.type==='number'?`step="${f.integer?'1':'any'}" min="${f.min}" max="${f.max}"`:''}>`}</div>`;}
export function toolPage(main,t){clearTool();let generation=0,files=[],urls=[],last=null,activeCleanup=()=>{};const revoke=()=>{urls.forEach(URL.revokeObjectURL);urls=[];};dispose=()=>{generation++;activeCleanup();revoke();};
main.innerHTML=`<div class="container"><div class="breadcrumb"><a href="#/">Home</a> / <a href="#/tools">Tools</a> / ${esc(t.category)}</div><div class="tool-heading"><h1>${esc(t.name)}</h1><p>${esc(t.description)}</p></div><div class="tool-layout"><section class="panel"><h2>Your input</h2><form id="tool-form" novalidate autocomplete="off"><div class="form-grid">${t.fields.map(field).join('')}</div>${t.files?`<label class="drop-zone" id="drop-zone">Drop files here or choose files<input type="file" id="tool-files" ${t.multiple?'multiple':''} accept="${esc(t.accept||'')}"></label><p id="file-info"></p>`:''}<p class="error" id="tool-error" role="alert"></p><div class="form-actions"><button class="primary" type="submit">Process</button><button class="secondary" type="reset">Reset</button><button class="secondary" type="button" id="tool-clear">Clear</button></div><p id="tool-status" role="status"></p></form></section><section class="panel tool-result" aria-label="Tool output"><h2>Output</h2><div id="tool-preview"></div><textarea id="tool-output" rows="12" readonly aria-label="Output text" spellcheck="false"></textarea><div class="form-actions"><button class="secondary" id="tool-copy" disabled>Copy</button><button class="secondary" id="tool-download" disabled>Download text</button></div><div id="tool-downloads"></div><p class="result-note" id="tool-note"></p></section></div><article class="guide"><h2>How to use this tool</h2><p>${esc(t.instructions)}</p><h2>Privacy</h2><p>${t.files?'Your files are processed locally in your browser and are not uploaded.':'Processing happens locally in your browser.'} Input content is not saved. Favorites and recent items store utility IDs only.</p><h2>Frequently asked questions</h2><details><summary>${esc(t.faq[0])}</summary><p>${esc(t.faq[1])}</p></details><details><summary>What are the limits?</summary><p>${esc(t.limits||'Text is limited to 1,000,000 characters. Very large files or outputs may exceed browser memory. Use a current browser with JavaScript enabled.')} Clear discards the current result; Reset restores example inputs.</p></details><p><a href="#/tools">Explore all online tools</a></p></article></div>`;
const form=main.querySelector('#tool-form'),out=main.querySelector('#tool-output'),err=main.querySelector('#tool-error'),status=main.querySelector('#tool-status'),preview=main.querySelector('#tool-preview'),buttons=main.querySelector('#tool-downloads');
function resetResult(){form.querySelector('[type=submit]').disabled=false;activeCleanup();activeCleanup=()=>{};generation++;revoke();last=null;out.value='';err.textContent='';status.textContent='';preview.replaceChildren();buttons.replaceChildren();main.querySelector('#tool-note').textContent='';main.querySelector('#tool-copy').disabled=true;main.querySelector('#tool-download').disabled=true;main.querySelector('#tool-download').textContent='Download text';}
function setFiles(a){resetResult();files=Array.from(a);if(!t.multiple)files=files.slice(0,1);main.querySelector('#file-info').textContent=files.map(f=>`${f.name} — ${f.size.toLocaleString()} bytes`).join('; ');}
if(t.files){const input=main.querySelector('#tool-files'),zone=main.querySelector('#drop-zone');input.onchange=()=>setFiles(input.files);zone.ondragover=e=>{e.preventDefault();};zone.ondrop=e=>{e.preventDefault();setFiles(e.dataTransfer.files);};}
form.onsubmit=async e=>{e.preventDefault();resetResult();const token=generation;try{const values={};for(const f of t.fields){const raw=form.elements.namedItem(f.name).value; if(!f.optional&&!raw.trim()&&!(f.name==='input'&&t.optionalFiles&&files.length))throw Error(`Enter ${f.label.toLowerCase()}.`);if(raw.length>1000000)throw Error('Input must stay below 1,000,000 characters.');values[f.name]=f.type==='number'?Number(raw):raw;if(f.type==='number'&&(!Number.isFinite(values[f.name])||values[f.name]<f.min||values[f.name]>f.max||f.integer&&!Number.isSafeInteger(values[f.name])))throw Error(`${f.label} must be ${f.integer?'a whole number ':''}between ${f.min} and ${f.max}.`);if(f.type==='select'&&!f.options.some(([x])=>String(x)===raw))throw Error('Choose a valid option.');}if(t.files&&!t.optionalFiles&&!files.length)throw Error('Choose a file first.');form.querySelector('[type=submit]').disabled=true;status.textContent='Processing locally…';const module=await import(`./modules/${t.module}.js`);const result=await module.run(t.id,values,files);if(token!==generation)return;last={...result,extension:extension(t,values)};out.value=result.text||'';main.querySelector('#tool-download').textContent=last.extension==='txt'?'Download text':'Download .'+last.extension;main.querySelector('#tool-note').textContent=result.note||'';for(const f of result.files||[]){const b=document.createElement('button');b.className='secondary';b.textContent=`Download ${f.name}`;b.onclick=()=>download(f.blob,f.name);buttons.append(b);}if(result.preview){const url=URL.createObjectURL(result.preview);urls.push(url);const img=document.createElement('img');img.src=url;img.alt=result.previewAlt||'Processed image preview';preview.append(img);}if(result.html){const frame=document.createElement('iframe');frame.setAttribute('sandbox','');frame.title='Local preview';frame.srcdoc='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'"><style>body{font:16px system-ui;line-height:1.6;overflow-wrap:anywhere}</style>'+result.html;preview.append(frame);}status.textContent='Done — processed locally in your browser.';main.querySelector('#tool-copy').disabled=!out.value;main.querySelector('#tool-download').disabled=!out.value;if(module.mount){activeCleanup=module.mount(preview,values)||(()=>{});}}catch(e){if(token===generation){err.textContent=e.message||'Unable to process this input.';status.textContent='';}}finally{if(token===generation)form.querySelector('[type=submit]').disabled=false;}};
form.addEventListener('input',resetResult);
main.querySelector('#tool-copy').onclick=async()=>{try{await navigator.clipboard.writeText(out.value);status.textContent='Copied.';}catch{out.select();status.textContent='Select the output and copy it with your keyboard.';}};
main.querySelector('#tool-download').onclick=()=>download(new Blob([out.value],{type:'text/plain;charset=utf-8'}),t.id+'.'+(last?.extension||'txt'));
form.onreset=()=>{resetResult();files=[];if(t.files)main.querySelector('#file-info').textContent='';};main.querySelector('#tool-clear').onclick=()=>{form.reset();for(const f of t.fields)if(f.type==='text'||f.multiline)form.elements.namedItem(f.name).value='';};
}
