import {output,check,loadScript,fileBytes} from '../shared/common.js';
import {toBase64,fromBase64} from './developer.js';
export async function parseTable(input,source='CSV'){if(source==='JSON'){const x=JSON.parse(input);check(Array.isArray(x)&&x.length>0&&x.every(row=>row&&typeof row==='object'&&!Array.isArray(row)),'JSON must be a nonempty array of flat objects.');check(x.length<=10000,'Limit JSON tables to 10,000 rows.');const headers=[...new Set(x.flatMap(Object.keys))];check(headers.length<=200,'Limit tables to 200 columns.');check(x.every(row=>Object.values(row).every(v=>v===null||['string','number','boolean'].includes(typeof v))),'Nested JSON values are not supported.');return{headers,rows:x.map(row=>headers.map(k=>row[k]??''))};}const P=await loadScript('papaparse-5.5.3.min.js','Papa'),r=P.parse(input,{delimiter:source==='TSV'?'\t':',',skipEmptyLines:false});check(!r.errors.length,'Invalid delimited data: '+r.errors.map(e=>e.message).join('; '));const headers=r.data.shift();if(/\r?\n$/.test(input)&&r.data.length&&r.data.at(-1).length===1&&r.data.at(-1)[0]==='')r.data.pop();check(headers?.length&&new Set(headers).size===headers.length&&headers.every(x=>x.trim()),'Column headers must be nonempty and unique.');check(r.data.length<=10000&&headers.length<=200,'Limit tables to 10,000 rows and 200 columns.');r.data=r.data.map(row=>row.length===1&&row[0]===''?Array(headers.length).fill(''):row);check(r.data.every(row=>row.length===headers.length),'All rows must have the same number of fields as the header.');return{headers,rows:r.data};}
async function serialize(table,mode){if(mode==='JSON')return JSON.stringify(table.rows.map(row=>Object.fromEntries(table.headers.map((h,i)=>[h,row[i]]))),null,2);const P=await loadScript('papaparse-5.5.3.min.js','Papa');return P.unparse([table.headers,...table.rows],{delimiter:mode==='TSV'?'\t':',',newline:'\n'});}
export async function run(id,v,files=[]){
 if(id==='file-viewer'){const f=files[0],bytes=await fileBytes(f);if(v.mode==='Base64')return output(toBase64(bytes));if(v.mode==='UTF-8 text')return output(new TextDecoder('utf-8',{fatal:true}).decode(bytes));return output(`Name: ${f.name}\nBytes: ${f.size}\nExtension: ${f.name.includes('.')?f.name.split('.').at(-1):'(none)'}\nMIME reported by browser: ${f.type||'(unknown)'}\nLast modified: ${new Date(f.lastModified).toISOString()}`,{note:'MIME type and extension are labels, not proof of file contents.'});}
 if(id==='base64-file'){check(/^[^<>:"/\\|?*\x00-\x1f]+$/.test(v.filename),'Use a simple filename without path separators or reserved characters.');check(/^[\w.+-]+\/[\w.+-]+$/.test(v.mime),'Enter a valid MIME type.');const bytes=fromBase64(v.input);return output(`${bytes.length} decoded bytes.`,{files:[{name:v.filename,blob:new Blob([bytes],{type:v.mime})}]});}
 if(id==='filename-cleaner')return output(v.input.split(/\r?\n/).map(s=>{s=s.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[ .]+$/,'').trim();if(/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(s))s='_'+s;return s||'unnamed';}).join('\n'));
 const sourceInput=files.length?new TextDecoder('utf-8',{fatal:true}).decode(await fileBytes(files[0],2*1024*1024)):v.input;check(sourceInput.length<=1000000,'CSV input must stay below 1,000,000 characters.');const t=await parseTable(sourceInput,v.source||'CSV');
 if(id==='csv-tools'){if(v.mode==='View / Validate')return output(`Valid ${v.source}.\nRows (excluding header): ${t.rows.length}\nColumns: ${t.headers.length}\n\n`+JSON.stringify(t,null,2));return output(await serialize(t,v.mode),{note:'CSV/TSV output may contain spreadsheet formulas from the input. Import as text if the input is untrusted.'});}
 if(id==='csv-statistics'){const i=t.headers.indexOf(v.column);check(i>=0,'Column not found.');const nums=t.rows.map(r=>String(r[i]).trim()).filter(Boolean);check(nums.every(s=>Number.isFinite(Number(s))),'Chosen column must contain finite numbers or empty cells.');const a=nums.map(Number),sum=a.reduce((s,n)=>s+n,0);check(Number.isFinite(sum),'Numeric total exceeds supported range.');return output(JSON.stringify({rows:t.rows.length,columns:t.headers.length,emptyCells:t.rows.flat().filter(s=>String(s).trim()==='').length,numericCount:a.length,sum,mean:a.length?sum/a.length:null,min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null},null,2));}
 if(id==='csv-editor'){const i=t.headers.indexOf(v.column);if(['Sort ascending','Sort descending','Filter contains','Rename columns'].includes(v.mode))check(i>=0,'Column not found.');switch(v.mode){case'Deduplicate rows':{const seen=new Set();t.rows=t.rows.filter(r=>{const k=JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true;});break;}case'Remove empty rows':t.rows=t.rows.filter(r=>r.some(s=>String(s).trim()));break;case'Filter contains':t.rows=t.rows.filter(r=>String(r[i]).includes(v.value));break;case'Select columns':{const P=await loadScript('papaparse-5.5.3.min.js','Papa'),parsed=P.parse(v.value,{delimiter:','});check(!parsed.errors.length&&parsed.data.length===1,'Enter one quoted CSV row of column names.');const a=parsed.data[0].map(x=>x.trim());check(a.length&&new Set(a).size===a.length&&a.every(h=>t.headers.includes(h)),'Select existing unique comma-separated column names.');const idx=a.map(h=>t.headers.indexOf(h));t.rows=t.rows.map(r=>idx.map(i=>r[i]));t.headers=a;break;}case'Rename columns':check(v.value.trim()&&!t.headers.includes(v.value),'New column name must be nonempty and unique.');t.headers[i]=v.value;break;default:t.rows.sort((a,b)=>String(a[i]).localeCompare(String(b[i]),undefined,{numeric:true})*(v.mode==='Sort descending'?-1:1));}return output(await serialize(t,'CSV'));}
 throw Error('Unknown data operation.');
}
