import {output,check,randomInt,escapeHTML} from '../shared/common.js';
export function rgbToHsl([r,g,b]){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0,s=0;if(d){s=d/(1-Math.abs(2*l-1));h=(max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4)*60;}return[h,s*100,l*100];}
export function hslToRgb([h,s,l]){h=((h%360)+360)%360;s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs(h/60%2-1)),m=l-c/2;const a=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return a.map(v=>Math.round((v+m)*255));}
export const rgbHex=a=>'#'+a.map(v=>Math.round(v).toString(16).padStart(2,'0')).join('');
export function parseColor(s){let m;if((m=s.trim().match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i))){const h=m[1].length===3?Array.from(m[1],c=>c+c).join(''):m[1];return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16));}if((m=s.match(/^rgb\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)$/i))){const a=m.slice(1).map(Number);check(a.every(x=>x>=0&&x<=255),'RGB values must be 0–255.');return a.map(Math.round);}if((m=s.match(/^hsl\(\s*([-\d.]+)\s*,\s*([\d.]+)%\s*,\s*([\d.]+)%\s*\)$/i))){const a=m.slice(1).map(Number);check(a.every(Number.isFinite)&&a[1]<=100&&a[2]<=100,'HSL saturation and lightness must be 0–100%.');return hslToRgb(a);}throw Error('Use #RGB, #RRGGBB, rgb(r,g,b), or hsl(h,s%,l%).');}
const luminance=a=>a.map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);
export const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
export async function run(id,v){
 if(id==='color-tools'){const rgb=parseColor(v.mode==='Picker'?v.picker:v.input),hsl=rgbToHsl(rgb);return output(`${rgbHex(rgb)}\nrgb(${rgb.join(', ')})\nhsl(${hsl.map(x=>x.toFixed(2)).join(', ').replace(', ', ', ').split(', ').map((x,i)=>x+(i?'%':'')).join(', ')})`,{html:`<div style="height:120px;background:${rgbHex(rgb)}"></div>`});}
 if(id==='color-palette'){const base=parseColor(v.input),hsl=rgbToHsl(base);let a;if(v.mode==='Random')a=Array.from({length:v.count},()=>rgbHex([randomInt(256),randomInt(256),randomInt(256)]));else if(v.mode==='Complementary')a=[rgbHex(base),rgbHex(hslToRgb([hsl[0]+180,hsl[1],hsl[2]]))];else a=Array.from({length:v.count},(_,i)=>rgbHex(base.map(x=>v.mode==='Tints'?x+(255-x)*i/(v.count-1):x*(1-i/(v.count-1)))));return output(a.join('\n'),{html:a.map(c=>`<div style="display:inline-block;padding:24px;background:${c}">${c}</div>`).join('')});}
 if(id==='contrast-checker'){const ratio=contrast(parseColor(v.first),parseColor(v.second));return output(`Contrast ratio: ${ratio.toFixed(2)}:1\nWCAG AA normal text (4.5:1): ${ratio>=4.5?'Pass':'Fail'}\nWCAG AA large text (3:1): ${ratio>=3?'Pass':'Fail'}\nWCAG AAA normal text (7:1): ${ratio>=7?'Pass':'Fail'}\nWCAG AAA large text (4.5:1): ${ratio>=4.5?'Pass':'Fail'}`,{note:'Large text means at least 18pt regular or 14pt bold. This checks color contrast only, not overall accessibility.'});}
 if(id==='gradient-generator'){const css=`background: linear-gradient(${v.angle}deg, ${v.first}, ${v.second});`;return output(css,{html:`<div style="height:150px;${css}"></div>`});}
 if(id==='css-design'){const box=`${v.x}px ${v.y}px ${v.blur}px ${v.spread}px ${v.foreground}`,text=`${v.x}px ${v.y}px ${v.blur}px ${v.foreground}`;const css=v.mode==='Box shadow'?`box-shadow: ${box};`:v.mode==='Text shadow'?`text-shadow: ${text};`:v.mode==='Border radius'?`border-radius: ${v.radius}px;`:`background: ${v.background};\ncolor: ${v.foreground};\nborder: 0;\nborder-radius: ${v.radius}px;\npadding: 12px 24px;\nbox-shadow: ${v.x}px ${v.y}px ${v.blur}px ${v.spread}px #00000033;`;return output(css,{html:`<div style="padding:50px"><button style="${escapeHTML(css)}">Preview</button></div>`});}
 throw Error('Unknown design operation.');
}
