import {output,check,fileBytes} from '../shared/common.js';
import {toBase64,fromBase64} from './developer.js';
export const canvasBlob=(canvas,type,quality)=>new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Browser could not encode this image.')),type,quality));
export async function decodeImage(file){check(file&&['image/png','image/jpeg','image/webp'].includes(file.type),'Choose a PNG, JPEG or WebP image.');await fileBytes(file);const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});check(bitmap.width*bitmap.height<=24000000,'Image exceeds 24 megapixels.');return bitmap;}
export async function run(id,v,files=[]){
 if(id==='base64-image'){const m=v.input.match(/^data:(image\/(?:png|jpeg|webp));base64,([\s\S]+)$/);check(m,'Enter a PNG, JPEG or WebP Base64 data URL.');const blob=new Blob([fromBase64(m[2])],{type:m[1]}),img=await decodeImage(blob);const dims=`${img.width} × ${img.height}`;img.close();return output(dims,{preview:blob,note:`Decoded file: ${blob.size} bytes; ${m[1]}. Base64 decoding preserves original file bytes and metadata.`,files:[{name:'decoded.'+m[1].split('/')[1],blob}]});}
 check(files.length<=20,'Choose at most 20 images.');const result=[],rows=[];let preview;
 for(const file of files){if(id==='image-base64'){const bitmap=await decodeImage(file),dims=bitmap.width+' × '+bitmap.height;bitmap.close();const data='data:'+file.type+';base64,'+toBase64(await fileBytes(file));return output(data,{preview:file,previewAlt:'Original image preview',note:`Original: ${dims}; ${file.size} bytes; ${file.type}. Encoded data URL: ${data.length} ASCII characters. Original file bytes and metadata are preserved.`});}const img=await decodeImage(file),iw=img.width,ih=img.height;
 try{if(id==='image-info')return output(`File: ${file.name}\nBytes: ${file.size}\nMIME: ${file.type}\nDimensions: ${iw} × ${ih}\nAspect ratio: ${(iw/ih).toFixed(6)}`,{preview:file,previewAlt:'Original image preview',note:'Decoded image facts only. EXIF, GPS and camera metadata are not parsed.'});let x=0,y=0,w=iw,h=ih,ow=iw,oh=ih;
 if(id==='image-resizer'){const ratio=Math.min(v.width/iw,v.height/ih,v.upscale==='Yes'?Infinity:1);ow=Math.max(1,Math.round(iw*ratio));oh=Math.max(1,Math.round(ih*ratio));}
 if(id==='image-editor'){x=v.x;y=v.y;w=v.width||iw-x;h=v.height||ih-y;check(x<iw&&y<ih&&w>0&&h>0&&x+w<=iw&&y+h<=ih,'Crop rectangle must fit inside the image.');ow=w;oh=h;if(v.rotation==='90'||v.rotation==='270')[ow,oh]=[oh,ow];}
 check(ow*oh<=24000000,'Output exceeds 24 megapixels.');const c=document.createElement('canvas');c.width=ow;c.height=oh;const ctx=c.getContext('2d');check(ctx,'Canvas unavailable.');if(v.format==='JPEG'){ctx.fillStyle='#ffffff';ctx.fillRect(0,0,ow,oh);}ctx.save();if(id==='image-filters'){ctx.filter=v.effect==='Grayscale'?`grayscale(${v.amount}%)`:v.effect==='Blur'?`blur(${v.amount}px)`:['Brightness','Contrast','Saturation'].includes(v.effect)?`${v.effect==='Saturation'?'saturate':v.effect.toLowerCase()}(${v.amount}%)`:'none';}
 if(id==='image-editor'){ctx.translate(ow/2,oh/2);ctx.rotate(Number(v.rotation)*Math.PI/180);ctx.scale(v.flip==='Horizontal'||v.flip==='Both'?-1:1,v.flip==='Vertical'||v.flip==='Both'?-1:1);ctx.drawImage(img,x,y,w,h,-w/2,-h/2,w,h);}else ctx.drawImage(img,0,0,ow,oh);ctx.restore();ctx.filter='none';
 if(id==='image-filters'&&v.effect==='Sharpen'){const image=ctx.getImageData(0,0,ow,oh),src=new Uint8ClampedArray(image.data),strength=v.amount/100;for(let y=1;y<oh-1;y++)for(let x=1;x<ow-1;x++)for(let k=0;k<3;k++){const i=(y*ow+x)*4+k;image.data[i]=src[i]*(1+4*strength)-strength*(src[i-4]+src[i+4]+src[i-ow*4]+src[i+ow*4]);}ctx.putImageData(image,0,0);}
 if(id==='image-filters'&&v.watermark){ctx.font=`${v.font}px sans-serif`;ctx.fillStyle=v.color;ctx.textAlign='right';ctx.textBaseline='bottom';ctx.fillText(v.watermark,ow-12,oh-12,Math.max(1,ow-24));}
 const type={PNG:'image/png',JPEG:'image/jpeg',WebP:'image/webp'}[v.format],blob=await canvasBlob(c,type,v.quality/100);check(blob.type===type,'Requested format is not supported by this browser.');const ext=v.format.toLowerCase()==='jpeg'?'jpg':v.format.toLowerCase();result.push({name:file.name.replace(/\.[^.]+$/,'')+'-processed.'+ext,blob});preview??=blob;rows.push(`${file.name}\nInput: ${iw} × ${ih}; ${file.size} bytes\nOutput: ${ow} × ${oh}; ${blob.size} bytes; ${type}\nSize reduction: ${((1-blob.size/file.size)*100).toFixed(2)}%`);c.width=c.height=0;
 }finally{img.close();}}
 return output(rows.join('\n\n'),{files:result,preview,note:'Negative reduction means the output is larger. JPEG removes transparency using a white background; PNG ignores the lossy quality setting. EXIF and animation are not preserved.'});
}
