import {output,check,fileBytes,loadScript} from '../shared/common.js';
import {decodeImage,canvasBlob} from './image.js';
export function pageSelection(s,count){if(!s.trim())return Array.from({length:count},(_,i)=>i);const a=[];for(const part of s.split(',')){const m=part.trim().match(/^(\d+)(?:-(\d+))?$/);check(m,'Use page numbers or ascending ranges, such as 1,3-5.');const start=+m[1],end=+(m[2]||m[1]);check(start>=1&&end>=start&&end<=count,'Page selection is outside the document.');for(let n=start;n<=end;n++)a.push(n-1);check(a.length<=1000,'Select at most 1,000 output pages.');}return a;}
export async function run(id,v,files){check(files.length<=20,'Choose at most 20 files.');
 if(id==='pdf-to-images'){const lib=await import('../../../assets/vendor/pdfjs-4.10.38.mjs');lib.GlobalWorkerOptions.workerSrc=new URL('../../../assets/vendor/pdfjs-worker-4.10.38.mjs',import.meta.url).href;const task=lib.getDocument({data:await fileBytes(files[0]),isEvalSupported:false,useSystemFonts:true,disableFontFace:false,cMapUrl:new URL('../../../assets/vendor/pdfjs-cmaps/',import.meta.url).href,cMapPacked:true,standardFontDataUrl:new URL('../../../assets/vendor/pdfjs-standard-fonts/',import.meta.url).href});let encrypted=false;task.onPassword=()=>{encrypted=true;task.destroy();};let doc;try{doc=await task.promise;const indices=pageSelection(v.pages,doc.numPages);check(indices.length<=20,'Render at most 20 pages.');const result=[];let preview;for(const i of indices){const p=await doc.getPage(i+1),view=p.getViewport({scale:v.scale});check(view.width*view.height<=12000000,'Rendered page exceeds 12 megapixels.');const c=document.createElement('canvas');c.width=Math.ceil(view.width);c.height=Math.ceil(view.height);await p.render({canvasContext:c.getContext('2d'),viewport:view}).promise;const blob=await canvasBlob(c,'image/png',1);result.push({name:`page-${i+1}.png`,blob});preview??=blob;c.width=c.height=0;}return output(`${result.length} pages rendered as PNG.`,{files:result,preview});}catch(e){if(encrypted)throw Error('Encrypted / password-protected PDFs are not supported. Supply an unencrypted copy.');throw e;}finally{await task.destroy();}}
const P=await loadScript('pdf-lib-1.17.1.min.js','PDFLib');const load=async file=>{check(file?.type==='application/pdf'||/\.pdf$/i.test(file?.name||''),'Choose a PDF file.');try{const d=await P.PDFDocument.load(await fileBytes(file));check(d.getPageCount()<=500,'PDF exceeds 500 pages.');return d;}catch(e){if(/encrypt/i.test(e.message))throw Error('Encrypted / password-protected PDFs are not supported. Supply an unencrypted copy.');throw e;}};const save=async(d,name)=>({name,blob:new Blob([await d.save()],{type:'application/pdf'})});
 if(id==='images-to-pdf'){const doc=await P.PDFDocument.create();for(const f of files){const b=await decodeImage(f);try{const c=document.createElement('canvas');c.width=b.width;c.height=b.height;c.getContext('2d').drawImage(b,0,0);const image=await doc.embedPng(await (await canvasBlob(c,'image/png',1)).arrayBuffer()),page=doc.addPage([b.width*0.75,b.height*0.75]);page.drawImage(image,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});c.width=c.height=0;}finally{b.close();}}return output(`${files.length} image pages created.`,{files:[await save(doc,'images.pdf')]});}
 if(id==='pdf-merge'){const doc=await P.PDFDocument.create();for(const f of files){const src=await load(f),pages=await doc.copyPages(src,src.getPageIndices());check(doc.getPageCount()+pages.length<=1000,'Merged output exceeds 1,000 pages.');pages.forEach(p=>doc.addPage(p));}return output(`${files.length} PDFs merged; ${doc.getPageCount()} pages.`,{files:[await save(doc,'merged.pdf')]});}
 const pdfFile=id==='pdf-image-watermark'?files.find(f=>f.type==='application/pdf'||/\.pdf$/i.test(f.name)):files[0];const doc=await load(pdfFile),count=doc.getPageCount();
 if(id==='pdf-info')return output(JSON.stringify({pages:count,title:doc.getTitle()||'',author:doc.getAuthor()||'',subject:doc.getSubject()||'',keywords:doc.getKeywords()||'',producer:doc.getProducer()||'',creator:doc.getCreator()||'',created:doc.getCreationDate()?.toISOString(),modified:doc.getModificationDate()?.toISOString(),dimensions:doc.getPages().map((p,i)=>({page:i+1,width:p.getWidth(),height:p.getHeight(),rotation:p.getRotation().angle}))},null,2));
 if(id==='pdf-organizer'){const selected=pageSelection(v.pages,count);if(v.mode==='Split every page'){check(count<=100,'Splitting is limited to 100 individual downloads.');const result=[];for(let i=0;i<count;i++){const d=await P.PDFDocument.create();d.addPage((await d.copyPages(doc,[i]))[0]);result.push(await save(d,`page-${i+1}.pdf`));}return output(`${count} individual PDFs created.`,{files:result});}if(v.mode==='Rotate'){for(const i of new Set(selected)){const p=doc.getPage(i);p.setRotation(P.degrees((p.getRotation().angle+Number(v.rotation))%360));}return output(`${new Set(selected).size} pages rotated.`,{files:[await save(doc,'rotated.pdf')]});}const indices=v.mode==='Delete'?doc.getPageIndices().filter(i=>!selected.includes(i)):selected;check(indices.length>0,'The output must contain at least one page.');const d=await P.PDFDocument.create();(await d.copyPages(doc,indices)).forEach(p=>d.addPage(p));return output(`${indices.length} output pages.`,{files:[await save(d,'organized.pdf')]});}
 if(id==='pdf-overlay'){check(/^[\x20-\x7E]*$/.test(v.text),'Text watermark currently supports printable ASCII only.');const font=await doc.embedFont(P.StandardFonts.Helvetica);doc.getPages().forEach((page,i)=>{const text=v.mode==='Page numbers'?`${i+1} / ${count}`:v.text;page.drawText(text,{x:v.mode==='Page numbers'?Math.max(10,(page.getWidth()-font.widthOfTextAtSize(text,v.size))/2):30,y:v.mode==='Page numbers'?20:page.getHeight()/2,size:v.size,font,color:P.rgb(.3,.3,.3),opacity:v.mode==='Page numbers'?1:.35});});return output(`${count} pages updated.`,{files:[await save(doc,'overlay.pdf')]});}
 if(id==='pdf-image-watermark'){check(files.length===2,'Select exactly one PDF followed by one PNG or JPEG image.');const f=files.find(f=>f!==pdfFile);check(f,'Choose one PDF and one image.');const bytes=await fileBytes(f);check(['image/png','image/jpeg'].includes(f.type),'Use PNG or JPEG watermark.');const image=f.type==='image/png'?await doc.embedPng(bytes):await doc.embedJpg(bytes);for(const p of doc.getPages()){const scale=Math.min(v.width/image.width,p.getWidth()*.8/image.width,p.getHeight()*.8/image.height),width=image.width*scale,height=image.height*scale;p.drawImage(image,{x:(p.getWidth()-width)/2,y:(p.getHeight()-height)/2,width,height,opacity:v.opacity/100});}return output(`${count} pages watermarked.`,{files:[await save(doc,'watermarked.pdf')]});}
 throw Error('Unknown PDF operation.');
}
