import {output,check,loadScript} from '../shared/common.js';
import {httpURL} from './seo.js';
import {contrast,parseColor} from './design.js';
import {canvasBlob} from './image.js';
const phone=s=>{check(/^\+?\d{6,15}$/.test(s),'Use 6–15 digits, optionally starting with +.');return s;};
const wifiEscape=s=>s.replace(/[\\;,:"']/g,'\\$&');
export function qrContent(v){const s=v.input;switch(v.mode){case'URL':return httpURL(s);case'Wi-Fi':return`WIFI:T:${v.wifi};S:${wifiEscape(s)};P:${v.wifi==='nopass'?'':wifiEscape(v.second)};;`;case'Email':check(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s),'Enter a valid email address.');return'mailto:'+s+'?body='+encodeURIComponent(v.second);case'Phone':return'tel:'+phone(s);case'SMS':return'sms:'+phone(s)+'?body='+encodeURIComponent(v.second);case'WhatsApp':return'https://wa.me/'+phone(s).replace(/^\+/,'')+'?text='+encodeURIComponent(v.second);case'Location':check(s.trim()&&v.second.trim()&&Number.isFinite(Number(s))&&Number.isFinite(Number(v.second))&&Number(s)>=-90&&Number(s)<=90&&Number(v.second)>=-180&&Number(v.second)<=180,'Enter valid latitude and longitude.');return`geo:${Number(s)},${Number(v.second)}`;case'vCard':{const escape=s=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/[,;]/g,'\\$&');return`BEGIN:VCARD\r\nVERSION:3.0\r\nN:;;;;\r\nFN:${escape(s)}\r\nTEL:${escape(v.second)}\r\nEMAIL:${escape(v.third)}\r\nEND:VCARD`; }default:return s;}}
export async function run(id,v){const files=[];
 if(id==='qr-generator'){const content=qrContent(v);check(content.length<=3000,'Use at most 3,000 characters; actual QR capacity may be lower.');check(contrast(parseColor(v.foreground),parseColor(v.background))>=4.5,'Use foreground/background contrast of at least 4.5:1.');const lum=a=>a.reduce((s,x)=>s+x,0);check(lum(parseColor(v.foreground))<lum(parseColor(v.background)),'Use a darker foreground than background.');const qrcode=await loadScript('qrcode-1.4.4.js','qrcode');await loadScript('qrcode-utf8-1.4.4.js','qrcode');const qr=qrcode(0,v.level);qr.addData(content,'Byte');qr.make();const n=qr.getModuleCount(),quiet=4,total=n+2*quiet;check(v.size>=total*2,'PNG is too small for this content; choose a larger size.');const canvas=document.createElement('canvas');canvas.width=canvas.height=v.size;const c=canvas.getContext('2d');c.fillStyle=v.background;c.fillRect(0,0,v.size,v.size);c.fillStyle=v.foreground;let paths=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(qr.isDark(y,x)){const x1=Math.round((x+quiet)*v.size/total),x2=Math.round((x+quiet+1)*v.size/total),y1=Math.round((y+quiet)*v.size/total),y2=Math.round((y+quiet+1)*v.size/total);c.fillRect(x1,y1,x2-x1,y2-y1);paths.push(`M${x+quiet} ${y+quiet}h1v1h-1z`);}const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" width="${v.size}" height="${v.size}" shape-rendering="crispEdges"><path fill="${v.background}" d="M0 0h${total}v${total}H0z"/><path fill="${v.foreground}" d="${paths.join('')}"/></svg>`,png=await canvasBlob(canvas,'image/png',1);return output(content,{preview:png,files:[{name:'qrcode.png',blob:png},{name:'qrcode.svg',blob:new Blob([svg],{type:'image/svg+xml'})}],note:'The QR contains the displayed payload. Scan and verify it before sharing.'});}
 if(id==='barcode-generator'){const barcode=await loadScript('jsbarcode-3.12.1.min.js','JsBarcode');check(v.input.length<=150,'Use at most 150 barcode characters.');const opts={format:v.format==='UPCA'?'UPC':v.format,width:v.width,height:v.height,displayValue:true,margin:12,valid:valid=>{check(valid,'Invalid value or check digit for this barcode format.');}};const canvas=document.createElement('canvas');barcode(canvas,v.input,opts);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');barcode(svg,v.input,opts);const png=await canvasBlob(canvas,'image/png',1);return output(v.input,{preview:png,files:[{name:'barcode.png',blob:png},{name:'barcode.svg',blob:new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'})}]});}
 throw Error('Unknown QR/barcode operation.');
}
