import {output,check,choose,shuffle,fileBytes} from '../shared/common.js';
// Exactly 256 distinct combinations; vocabulary and entropy are transparent.
const first='amber brave calm clear cool cozy crisp deep fair fine fresh glad grand green kind light'.split(' '),second='apple birch brook cloud coral dawn field fox hill lake leaf moon oak rain star wave'.split(' ');
export const passphraseWords=first.flatMap(a=>second.map(b=>a+b));
export const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
export async function run(id,v,files=[]){check(globalThis.crypto?.subtle,'Web Crypto requires HTTPS or localhost in a modern browser.');
 if(id==='secure-generator'){const basic='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';let alphabet=v.mode==='PIN'?'0123456789':v.mode==='Random string'?[...new Set(Array.from(v.alphabet))].join(''):v.mode==='Token'?'0123456789abcdef':basic+(v.symbols==='Include'?'!@#$%^&*()-_=+[]{};:,.?':'');check(alphabet.length>=2&&alphabet.length<=1000,'Use an alphabet with 2–1,000 unique characters.');const a=Array.from(alphabet);return output(Array.from({length:v.count},()=>v.mode==='UUID'?crypto.randomUUID():Array.from({length:v.length},()=>choose(a)).join('')).join('\n'),{note:'Generated secrets are not saved or transmitted. Password characters are uniformly sampled; no character class is guaranteed in an individual password.'});}
 if(id==='passphrase-generator')return output(Array.from({length:v.count},()=>choose(passphraseWords)).join(v.separator),{note:`${v.count*8} bits of selection entropy from ${v.count} independently chosen words in a 256-word public vocabulary.`});
 if(id==='password-strength'){const s=v.input;const pool=(/[a-z]/.test(s)?26:0)+(/[A-Z]/.test(s)?26:0)+(/\d/.test(s)?10:0)+(/[^A-Za-z0-9]/.test(s)?32:0);const patterns=[];if(/password|qwerty|12345|letmein|welcome|admin/i.test(s))patterns.push('common word or sequence');if(/(.)\1{2}/.test(s))patterns.push('repeated characters');return output(`Length: ${Array.from(s).length}\nCharacter classes: ${pool}\nAssessment: ${s.length<12||patterns.length?'Needs improvement':'Longer and varied; still check uniqueness'}\nPatterns: ${patterns.join(', ')||'none detected by this small heuristic'}\nRecommendation: use a unique cryptographically generated password or passphrase.`,{note:'Character-class estimates cannot account for dictionary attacks or leaked passwords. No cracking-time claim is made.'});}
 if(id==='hash-tools'){const bytes=new TextEncoder().encode(v.input);let digest;if(v.mode==='HMAC'){check(v.key,'Enter an HMAC key.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(v.key),{name:'HMAC',hash:v.algorithm},false,['sign']);digest=await crypto.subtle.sign('HMAC',key,bytes);}else digest=await crypto.subtle.digest(v.algorithm,bytes);return output(hex(digest));}
 if(id==='file-hash'){const hash=hex(await crypto.subtle.digest(v.algorithm,await fileBytes(files[0])));check(!v.expected||/^[0-9a-f]+$/i.test(v.expected),'Expected hash must be hexadecimal.');return output(hash+(v.expected?`\nComparison: ${hash===v.expected.trim().toLowerCase()?'MATCH':'DOES NOT MATCH'}`:''));}
 throw Error('Unknown security operation.');
}
