import {output,check,escapeHTML as esc} from '../shared/common.js';
export const httpURL=s=>{const u=new URL(s);check(['http:','https:'].includes(u.protocol)&&!u.username&&!u.password,'Use an HTTP(S) URL without credentials.');return u.href;};
export async function run(id,v){
 if(id==='meta-tags'){const u=httpURL(v.url),title=esc(v.title),desc=esc(v.description),image=v.image?httpURL(v.image):'';const tags=[`<title>${title}</title>`,`<meta name="description" content="${desc}">`,`<link rel="canonical" href="${esc(u)}">`,`<meta property="og:type" content="website">`,`<meta property="og:title" content="${title}">`,`<meta property="og:description" content="${desc}">`,`<meta property="og:url" content="${esc(u)}">`,`<meta name="twitter:card" content="${image?'summary_large_image':'summary'}">`,`<meta name="twitter:title" content="${title}">`,`<meta name="twitter:description" content="${desc}">`];if(image)tags.push(`<meta property="og:image" content="${esc(image)}">`,`<meta name="twitter:image" content="${esc(image)}">`);return output(tags.join('\n'),{html:`<p style="color:green">${esc(u)}</p><h2 style="color:#2453a6">${title}</h2><p>${desc}</p>`,note:`Title: ${Array.from(v.title).length} characters. Description: ${Array.from(v.description).length} characters. Search appearance is an approximation; engines may rewrite snippets and truncate by pixel width.`});}
 if(id==='robots-generator'){check(!/[\r\n]/.test(v.agent),'User agent must be one line.');const paths=s=>s.split(/\r?\n/).filter(Boolean).map(x=>{check(x.startsWith('/')&&!/[\r\n]/.test(x),'Paths must start with /.');return x;});return output(`User-agent: ${v.agent}\n`+paths(v.disallow).map(x=>'Disallow: '+x).concat(paths(v.allow).map(x=>'Allow: '+x),v.sitemap?['Sitemap: '+httpURL(v.sitemap)]:[]).join('\n'),{note:'Robots directives do not protect private content and may not be obeyed by every crawler.'});}
 if(id==='sitemap-generator'){const urls=[...new Set(v.input.split(/\r?\n/).filter(s=>s.trim()).map(s=>httpURL(s.trim())))];check(urls.length<=50000,'Limit sitemap to 50,000 URLs.');return output('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>`  <url><loc>${esc(u)}</loc></url>`).join('\n')+'\n</urlset>');}
 if(id==='hreflang-generator')return output(v.input.split(/\r?\n/).filter(Boolean).map(line=>{const [lang,url,...rest]=line.split('|').map(x=>x.trim());check(!rest.length&&/^(?:[a-z]{2,3}(?:-[a-z]{2})?|x-default)$/i.test(lang),'Use language | URL pairs with valid language codes.');return `<link rel="alternate" hreflang="${esc(lang)}" href="${esc(httpURL(url))}">`;}).join('\n'));
 if(id==='schema-generator'){const x=JSON.parse(v.input);check(x&&typeof x==='object'&&!Array.isArray(x),'Facts must be a JSON object.');check(!('@context'in x)&&!('@type'in x),'Supply facts without @context or @type; choose the type above.');if(v.type==='FAQPage')check(Array.isArray(x.mainEntity),'FAQPage requires a supplied mainEntity question/answer array.');if(v.type==='BreadcrumbList')check(Array.isArray(x.itemListElement),'BreadcrumbList requires supplied itemListElement entries.');return output(JSON.stringify({'@context':'https://schema.org','@type':v.type,...x},null,2),{note:'Only supplied facts were included. This is JSON syntax generation, not a guarantee of schema validity, rich-result eligibility or ranking.'});}
 throw Error('Unknown SEO operation.');
}
