import {output,bounded,words,graphemes,choose,check} from '../shared/common.js';
export async function run(id,v){const text=bounded(v.input||'');
 switch(id){
 case'text-counter':{const w=words(text).length;return output(`Words: ${w}\nCharacters (Unicode code points): ${Array.from(text).length}\nGrapheme clusters: ${graphemes(text).length}\nUTF-16 code units: ${text.length}\nCharacters excluding whitespace: ${Array.from(text.replace(/\s/gu,'')).length}\nSentences (punctuation heuristic): ${(text.match(/[^.!?]+(?:[.!?]+|$)/g)||[]).filter(s=>s.trim()).length}\nParagraphs: ${text.trim()?text.trim().split(/\n\s*\n/).length:0}\nReading: ${(w/v.reading).toFixed(2)} minutes\nSpeaking: ${(w/v.speaking).toFixed(2)} minutes`,{note:'Word boundaries and sentence counts are heuristics, especially for scripts without spaces and abbreviations.'});}
 case'case-converter':return output(v.mode==='UPPERCASE'?text.toUpperCase():v.mode==='lowercase'?text.toLowerCase():v.mode==='Sentence case'?text.toLowerCase().replace(/(^\s*|[.!?]\s+)(\p{L})/gu,(_,a,b)=>a+b.toUpperCase()):v.mode==='Capitalize Words'?text.replace(/(^|[^\p{L}\p{N}\p{M}])(\p{L})/gu,(_,a,b)=>a+b.toUpperCase()):text.toLowerCase().replace(/(^|[^\p{L}\p{N}\p{M}])(\p{L})/gu,(_,a,b)=>a+b.toUpperCase()));
 case'line-editor':{const lines=text.replace(/\r\n?/g,'\n').split('\n');let result;switch(v.mode){case'Remove Extra Spaces':result=text.replace(/[^\S\r\n]+/g,' ').split(/\r?\n/).map(s=>s.trim()).join('\n');break;case'Remove Line Breaks':result=lines.join(' ');break;case'Add Line Breaks':{const a=text.trim().split(/\s+/);result=Array.from({length:Math.ceil(a.length/v.width)},(_,k)=>a.slice(k*v.width,(k+1)*v.width).join(' ')).join('\n');break;}case'Remove Duplicate Lines':result=[...new Set(lines)].join('\n');break;case'Remove Empty Lines':result=lines.filter(s=>s.trim()).join('\n');break;case'Sort Lines A-Z':result=lines.sort((a,b)=>a.localeCompare(b)).join('\n');break;case'Sort Lines Z-A':result=lines.sort((a,b)=>b.localeCompare(a)).join('\n');break;case'Reverse Text':result=graphemes(text).reverse().join('');break;case'Reverse Lines':result=lines.reverse().join('\n');break;case'Prefix Each Line':result=lines.map(s=>v.affix+s).join('\n');break;case'Suffix Each Line':result=lines.map(s=>s+v.affix).join('\n');break;case'Line Number Generator':result=lines.map((s,k)=>`${k+1}. ${s}`).join('\n');break;default:result=text.replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\r\n?/g,'\n').split('\n').map(s=>s.trim().replace(/[\t ]+/g,' ')).filter(Boolean).join('\n');}return output(result);}
 case'text-repeater':check(text.length*v.count+(v.separator||'').length*Math.max(0,v.count-1)<=1000000,'Repeated output must stay below 1,000,000 characters.');return output(Array(v.count).fill(text).join(v.separator));
 case'find-replace':{check(v.find.length>0,'Enter text to find.');const pattern=v.find.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return output(text.replace(new RegExp(pattern,v.case==='Match case'?'g':'gi'),()=>v.replacement));}
 case'text-frequency':{const units=v.mode==='Characters'?graphemes(text):words(text.toLocaleLowerCase()),map=new Map();for(const unit of units)map.set(unit,(map.get(unit)||0)+1);const rows=[...map].filter(([,n])=>v.mode!=='Duplicate words'||n>1).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));check(rows.length<=20000,'Use fewer than 20,000 distinct words/characters.');return output(rows.map(([word,n])=>`${JSON.stringify(word)}\t${n}\t${(n/units.length*100).toFixed(2)}%`).join('\n')||'No duplicate words found.');}
 case'text-diff':{const a=bounded(text,100000).split('\n'),b=bounded(v.second,100000).split('\n');check(a.length<=500&&b.length<=500,'Use at most 500 lines in each text.');const dp=Array.from({length:a.length+1},()=>new Uint16Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,rows=[];while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){rows.push('  '+a[i++]);j++;}else if(j<b.length&&(i===a.length||dp[i][j+1]>=dp[i+1][j]))rows.push('+ '+b[j++]);else rows.push('- '+a[i++]);}return output(rows.join('\n'));}
 case'lorem-ipsum':{check(v.count*v.length<=10000,'Generate at most 10,000 words.');const bank=(v.mode==='Lorem Ipsum'?'lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua':'sample example interface layout browser local testing content simple readable design useful words').split(' ');return output(Array.from({length:v.count},()=>{const a=Array.from({length:v.length},()=>choose(bank));a[0]=a[0][0].toUpperCase()+a[0].slice(1);return a.join(' ')+'.';}).join('\n\n'));}
 default:throw new Error('Unknown text operation.');
 }
}
