import {output,check} from '../shared/common.js';
import {httpURL} from './seo.js';
export async function run(id,v){
 if(id==='slug-generator')return output(v.input.normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,''));
 if(id==='url-tools'){if(v.mode==='Clean link list'){const list=v.input.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(s=>{const u=new URL(httpURL(s));for(const key of [...u.searchParams.keys()])if(/^utm_/i.test(key)||['fbclid','gclid','msclkid','mc_cid','mc_eid'].includes(key.toLowerCase()))u.searchParams.delete(key);return u.href;});return output([...new Set(list)].join('\n'));}const u=new URL(httpURL(v.input));if(v.mode==='Parse')return output(JSON.stringify({protocol:u.protocol,hostname:u.hostname,port:u.port,path:u.pathname,fragment:u.hash,query:[...u.searchParams]},null,2));if(v.mode==='Clean tracking'){for(const key of [...u.searchParams.keys()])if(/^utm_/i.test(key)||['fbclid','gclid','msclkid','mc_cid','mc_eid'].includes(key.toLowerCase()))u.searchParams.delete(key);}else{for(const line of v.params.split(/\r?\n/).filter(Boolean)){const i=line.indexOf('=');check(i>0,'Use key=value pairs.');const key=line.slice(0,i),value=line.slice(i+1);if(v.mode==='UTM')check(/^utm_(source|medium|campaign|term|content)$/.test(key),'Use supported utm_ parameter names.');u.searchParams.set(key,value);}}return output(u.href);}
 if(id==='extract-links'){const trimEnd=x=>{let n=x.length;while(n&&'.,;)'.includes(x[n-1]))n--;return x.slice(0,n);};let a;if(v.mode==='URLs')a=v.input.match(/https?:\/\/[^\s<>\"']+/gi)||[];else if(v.mode==='Emails')a=(v.input.match(/[A-Z0-9._%+@-]+/gi)||[]).filter(x=>x.length<=325).map(trimEnd).filter(x=>x.length<=320&&/^[A-Z0-9._%+-]{1,64}@[A-Z0-9-]{1,63}(?:\.[A-Z0-9-]{1,63})*\.[A-Z]{2,63}$/i.test(x));else a=(v.input.match(/[a-z0-9.-]+/gi)||[]).filter(x=>x.length<=260).map(trimEnd).filter(x=>x.length<=253&&/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(x));const matches=[...new Set(a.map(trimEnd))];return output(matches.join('\n'),{note:`${matches.length} candidates found. Common ASCII email/domain forms only; existence, ownership and deliverability are not checked.`});}
 if(id==='web-reference'){const http={200:'OK',201:'Created',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',409:'Conflict',413:'Content Too Large',429:'Too Many Requests',500:'Internal Server Error',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout'},mime={txt:'text/plain',html:'text/html',css:'text/css',js:'text/javascript',json:'application/json',xml:'application/xml',csv:'text/csv',pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',svg:'image/svg+xml',zip:'application/zip',mp3:'audio/mpeg',mp4:'video/mp4'};const key=v.input.trim().replace(/^\./,'').toLowerCase();check((v.mode==='HTTP'?http:mime)[key],'No entry in the embedded common-values reference.');return output(key+': '+(v.mode==='HTTP'?http:mime)[key]);}
 if(id==='social-links'){const s=v.input.trim(),m=encodeURIComponent(v.message);if(['WhatsApp','Phone','SMS'].includes(v.mode))check(/^\+?\d{6,15}$/.test(s),'Use 6–15 phone digits, optionally starting with +.');if(v.mode==='Email')check(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s),'Enter a valid email address.');if(v.mode==='Telegram')check(/^[a-z][a-z0-9_]{4,31}$/i.test(s),'Use a 5–32 character Telegram username.');return output(v.mode==='WhatsApp'?'https://wa.me/'+s.replace(/^\+/,'')+'?text='+m:v.mode==='Telegram'?'https://t.me/'+s:v.mode==='Email'?'mailto:'+s+'?subject='+encodeURIComponent(v.subject)+'&body='+m:v.mode==='Phone'?'tel:'+s:v.mode==='SMS'?'sms:'+s+'?body='+m:'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(httpURL(s)));}
 if(id==='youtube-links'){let video=v.input.trim();if(/^https?:/i.test(video)){const u=new URL(httpURL(video));check(['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname),'Use a YouTube URL.');video=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([^/]+)/)?.[1]||'';}check(/^[A-Za-z0-9_-]{11}$/.test(video),'Use an 11-character video ID.');return output(v.mode==='Embed HTML'?`<iframe width="560" height="315" src="https://www.youtube.com/embed/${video}?start=${v.seconds}" title="YouTube video" allowfullscreen></iframe>`:`https://www.youtube.com/watch?v=${video}&t=${v.seconds}s`);}
 if(id==='hashtag-generator')return output([...new Set(v.input.split(/[,\n]/).map(s=>'#'+s.replace(/[^\p{L}\p{N}_]/gu,'')).filter(s=>s.length>1))].join(' '));
 throw Error('Unknown web operation.');
}
