import {reusedCalculatorAliases} from './tools/aliases.js';
import {tools,toolCategories} from './tools/catalog.js';
import {toolPage,clearTool} from './tools/view.js';
import { config } from './config.js';
import { calculators, categories, directory } from './catalog.js';
import { compute } from './calculators/compute.js';
import { validateField } from './validation.js';
import { assertRows } from './calculators/shared.js';
import { findCalculators } from './utils/search.js';
import { money,num,formatResult } from './utils/formatting.js';

const utilityCalculators=calculators.map(c=>({...c,aliases:[...(c.aliases||[]),...(reusedCalculatorAliases[c.id]||[])]}));
const main = document.querySelector('#main');
const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tone = category => category==='Health'?'tone-green':category==='Math'?'tone-purple':category==='Date & Time'?'tone-orange':'';
document.querySelectorAll('[data-brand]').forEach(el=>el.textContent=config.name);
document.querySelector('.brand').setAttribute('aria-label',`${config.name} home`);
document.querySelector('#year').textContent=new Date().getFullYear();
const themeButton = document.querySelector('#theme-toggle');
function setTheme(theme) {
  document.documentElement.dataset.theme=theme;
  themeButton.textContent=theme==='dark'?'☀':'☾';
  themeButton.setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} mode`);
  document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#101723':'#f7f9fc';
}
let storedTheme;try{storedTheme=localStorage.getItem('calchub-theme');}catch{}
setTheme(storedTheme || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
themeButton.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';setTheme(theme);try{localStorage.setItem('calchub-theme',theme);}catch{}});
function seo(title,description){document.title=`${title} — ${config.name}`;document.querySelector('meta[name="description"]').content=description;document.querySelector('meta[property="og:title"]').content=document.title;document.querySelector('meta[property="og:description"]').content=description;}
function card(tool){
  return `<a class="calculator-card" href="${tool.route||`#/calculator/${tool.id}`}" aria-label="Open ${escape(tool.name)}"><span class="tool-icon ${tone(tool.category)}" aria-hidden="true">${tool.icon}</span><div><h3>${escape(tool.name)}</h3><p>${escape(tool.description)}</p><div class="card-bottom"><span class="tag">${tool.category}</span><span class="utility-kind">${tool.kind||'Calculator'}</span><span class="arrow" aria-hidden="true">↗</span></div></div></a>`;
}
function home(params,full=false) {
  seo(full?'All Calculators':'Calculators & Online Tools','Free calculators and browser-local online tools for text, PDF, images, code, CSV and everyday tasks.');
  main.innerHTML=`<section class="hero"><div class="container"><div class="eyebrow"><span class="status-dot"></span> Small tools. Big possibilities.</div><h1>Calculators &amp; <span>Online Tools</span></h1><p>From planning your finances to solving everyday math.<br>Find the right calculator or online tool. Get answers that add up.</p><div class="search-wrap"><span class="search-icon" aria-hidden="true">⌕</span><input id="search" type="search" aria-label="Search calculators and tools" placeholder="What would you like to calculate?" autocomplete="off"><kbd aria-hidden="true">/</kbd></div><div class="quick-search">Try: <button data-search="GST">GST</button> · <button data-search="EMI">EMI</button> · <button data-search="BMI">BMI</button> · <button data-search="Age">Age</button></div><div class="form-actions hero-actions"><a class="primary" href="#/directory">Browse calculators</a><a class="secondary" href="#/tools">Browse online tools</a></div><div class="trust-row"><span><b>✓</b>Always free</span><span><b>✓</b>No sign-up needed</span><span><b>✓</b>Fast & easy to use</span></div></div></section>
  <div class="container"><section class="section" id="popular"><div class="section-heading"><div><h2>Popular calculators</h2><p>The tools you reach for most.</p></div><a class="text-link" href="#/directory" id="view-all">View all calculators →</a></div><div class="grid">${['gst','emi','sip','bmi'].map(id=>card(calculators.find(c=>c.id===id))).join('')}</div></section>
  <section class="section"><div class="section-heading"><div><h2>Explore by category</h2><p>A useful tool for every part of your day.</p></div></div><div class="category-grid">${categories.filter(([name])=>['Finance','Math','Health','Business','Date & Time','Converters','Construction'].includes(name)).map(([name,icon,count])=>`<button class="category-card" data-category="${name}"><span class="category-icon" aria-hidden="true">${icon}</span><strong>${name}</strong><small>${count} tools in directory</small></button>`).join('')}</div></section>
  <section class="section directory" id="all-calculators"><div class="section-heading"><div><h2>All calculators <span id="result-count" class="tag"></span></h2><p>${calculators.length} calculators, ready when you need them.</p></div></div><div class="filters" aria-label="Filter by category">${['All',...categories.map(c=>c[0])].map(name=>`<button class="filter" data-filter="${name}" aria-pressed="false">${name}</button>`).join('')}</div><div class="grid" id="directory-results" aria-live="polite"></div><div class="pagination" id="pagination"></div><div class="info-banner"><span aria-hidden="true">◇</span><div><h3>Your calculations, your business.</h3><p>All calculations run in your browser. We don’t send your inputs to a server.</p></div></div></section></div>`;
  let category = categories.some(c=>c[0]===params.get('category'))?params.get('category'):'All';
  const search=document.querySelector('#search');
  search.value=params.get('q')||'';
  let pageNumber=1;
  const pageSize=full?24:6;
  function filter(reset=true){
    if(reset)pageNumber=1;
    const found=findCalculators(search.value&&category==='All'?[...utilityCalculators,...tools]:directory,search.value,category);
    const shown=found.slice((pageNumber-1)*pageSize,pageNumber*pageSize);
    document.querySelector('#directory-results').innerHTML=shown.length?shown.map(c=>card(c)).join(''):'<p class="empty">No calculators found. Try another search or choose All.</p>';
    document.querySelector('#result-count').textContent=`${found.length} available`;document.querySelector('#all-calculators h2').firstChild.textContent=search.value.trim()?'Search results ':'All calculators ';
    document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===category);b.setAttribute('aria-pressed',b.dataset.filter===category);});
    document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===category));
    const pages=Math.ceil(found.length/pageSize);
    document.querySelector('#pagination').innerHTML=full?`<button class="secondary" data-page="-1" ${pageNumber<=1?'disabled':''}>← Previous</button><span>Page ${pageNumber} of ${Math.max(1,pages)}</span><button class="secondary" data-page="1" ${pageNumber>=pages?'disabled':''}>Next →</button>`:`<a class="text-link" href="#/directory?q=${encodeURIComponent(search.value)}&category=${encodeURIComponent(category)}">Browse all ${found.length} ${search.value.trim()?'utilities':'calculators'} →</a>`;
    document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{pageNumber+=Number(b.dataset.page);filter(false);document.querySelector('#all-calculators').scrollIntoView({behavior:'smooth'});}));
  }
  search.addEventListener('input',filter);
  document.querySelectorAll('[data-search]').forEach(b=>b.addEventListener('click',()=>{search.value=b.dataset.search;category='All';filter();document.querySelector('#all-calculators').scrollIntoView({behavior:'smooth'});}));
  document.querySelectorAll('[data-filter],[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter||b.dataset.category;filter();if(b.dataset.category)document.querySelector('#all-calculators').scrollIntoView({behavior:'smooth'});}));
  if(full){document.querySelector('#popular').remove();document.querySelector('.category-grid').closest('section').remove();document.querySelector('.hero h1').textContent='All Calculators';document.querySelector('.hero p').textContent=`Explore ${calculators.length} working tools. Search by name, topic or an everyday alias.`;}
  document.querySelectorAll('[data-category]').forEach(b=>{b.addEventListener('click',()=>{location.hash=`/directory?category=${encodeURIComponent(b.dataset.category)}`;});});
  filter();
  if(category!=='All'||params.get('section')==='all')requestAnimationFrame(()=>document.querySelector('#all-calculators').scrollIntoView());
}
function fieldHTML(f){const id=`field-${f.name}`;return `<div class="field"><label for="${id}">${escape(f.label)}</label>${f.multiline?`<textarea id="${id}" name="${f.name}" rows="3" required>${escape(f.value)}</textarea>`:f.type==='select'?`<select id="${id}" name="${f.name}">${f.options.map(([v,label])=>`<option value="${v}" ${String(f.value)===v?'selected':''}>${label}</option>`).join('')}</select>`:`<input id="${id}" name="${f.name}" type="${f.type}" value="${escape(f.value)}" ${f.name==='expression'?'class="basic-display"':''} ${f.type==='number'?`step="${f.integer?'1':'any'}" inputmode="decimal"`:''} ${f.min!==undefined?`min="${f.min}"`:''} ${f.max!==undefined?`max="${f.max}"`:''} required>`}</div>`;}
function calculatorPage(tool) {
  seo(tool.name,`${tool.description} Free ${tool.name.toLowerCase()} with clear results, formula, examples and a practical guide.`);
  main.innerHTML=`<div class="container"><div class="breadcrumb"><a href="#/">Home</a> / <a href="#/directory?category=${encodeURIComponent(tool.category)}">${tool.category}</a> / ${tool.name}</div><div class="tool-heading"><h1>${tool.name}</h1><p>${tool.description}</p></div><div class="tool-layout"><section class="panel"><h2>Make it yours</h2><form id="calculator-form" novalidate><div class="form-grid">${tool.fields.map(fieldHTML).join('')}</div>${['gst','gst-inclusive'].includes(tool.id)?'<div class="tool-presets" aria-label="GST rate presets">'+[5,12,18,28].map(r=>`<button type="button" data-rate="${r}">${r}%</button>`).join('')+'</div>':''}${['basic','scientific'].includes(tool.id)?'<div class="keypad">'+[...(tool.id==='scientific'?['sin(','cos(','tan(','log(','ln(','sqrt(','^','^2','%','pi']:[]),'C','(',')','⌫','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','=','+'].map(key=>`<button type="${key==='='?'submit':'button'}" data-key="${key}" class="${key==='='?'equals':/[÷×−+]/.test(key)?'operator':''}" aria-label="${({'C':'Clear','⌫':'Backspace','=':'Calculate','÷':'Divide','×':'Multiply','−':'Subtract','+':'Add'})[key]||key}">${key}</button>`).join('')+'</div>':''}<p id="error" class="error" role="alert"></p><div class="form-actions"><button class="primary" type="submit">Calculate ${tool.id==='length'||tool.id==='temperature'?'conversion':'result'} <span aria-hidden="true">→</span></button><button class="secondary" type="reset">Reset</button></div></form></section><section class="panel results" aria-label="Calculation results" aria-live="polite" aria-atomic="true" id="results"></section></div><article class="guide"><h2>About the ${tool.name}</h2><p>${tool.description} Enter your values above to get an instant result. Your inputs stay on this device.</p><h2>How to use it</h2><p>${tool.how}</p><h2>The formula</h2><div class="formula">${tool.formula}</div>${tool.source?`<p><a class="text-link" href="${escape(tool.source.url)}" target="_blank" rel="noopener noreferrer">Formula source: ${escape(tool.source.title)} ↗</a></p>`:''}<h2>A quick example</h2><p>${tool.example}</p><h2>Frequently asked questions</h2><details><summary>${tool.faq[0]}</summary><p>${tool.faq[1]}</p></details><details><summary>Can I use this calculator for free?</summary><p>Yes. All available ${config.name} calculators are free to use, with no account required.</p></details><p><a class="text-link" href="#/directory">← Explore all calculators</a></p></article></div>`;
  const form=document.querySelector('#calculator-form'),error=document.querySelector('#error'),results=document.querySelector('#results');
  function calculate(){
    error.textContent='';form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));
    try{const values={};for(const f of tool.fields){const input=form.elements.namedItem(f.name);try{values[f.name]=validateField(f,input.value);}catch(e){input.setAttribute('aria-invalid','true');input.focus();throw e;}}
      const output=assertRows(compute(tool.id,values));if(output.some(row=>typeof row[1]==='number'&&!Number.isFinite(row[1])))throw new Error('Result is too large. Please use smaller values.');
      const rows=output.map(([label,value,format])=>[label,formatResult(value,format)]);
      results.innerHTML=`<h2>Your results</h2><div class="result-main"><span>${rows[0][0]}</span><strong>${escape(rows[0][1])}</strong></div>${rows.slice(1).map(([label,value])=>`<div class="result-row"><span>${label}</span><strong>${escape(value)}</strong></div>`).join('')}<p class="result-note">${tool.note?escape(tool.note):tool.id==='sip'?'An illustrative projection, not a guaranteed return. Monthly deposits at the start of the month.':tool.id==='bmi'?'Standard adult categories. BMI is a screening measure, not a diagnosis.':tool.id==='emi'||tool.category==='Finance'?'Estimates based on the values entered. Fees and applicable taxes are excluded unless specified.':'Results are rounded for display.'}</p>`;
    }catch(e){error.textContent=e.message;results.innerHTML='<h2>Your results</h2><p class="result-note">Correct the input to see your result.</p>';}
  }
  form.addEventListener('submit',e=>{e.preventDefault();calculate();});
  form.addEventListener('reset',()=>setTimeout(calculate,0));
  document.querySelectorAll('[data-rate]').forEach(b=>b.addEventListener('click',()=>{form.elements.rate.value=b.dataset.rate;calculate();}));
  document.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.key,input=form.elements.expression;if(key==='=')return;if(key==='C')input.value='';else if(key==='⌫')input.value=input.value.slice(0,-1);else input.value+=key==='−'?'-':key;input.focus();}));
  calculate();
}
function route(){clearTool();const hash=location.hash.slice(1)||'/';const [path,query]=hash.split('?');if(path==='/'||path==='')home(new URLSearchParams(query));else if(path==='/tools'||path==='/favorites')utilityDirectory(new URLSearchParams(query),path==='/favorites');else if(path.startsWith('/tool/')){const t=tools.find(t=>path===`/tool/${t.id}`);if(t){seo(t.name,t.description);toolPage(main,t);remember(t);favorite(t);}else utilityDirectory(new URLSearchParams());}else if(path==='/directory')home(new URLSearchParams(query),true);else{const tool=calculators.find(c=>path===`/calculator/${c.id}`);if(tool){calculatorPage(tool);remember(tool);favorite(tool);}else{seo('Calculator not found','Explore our free calculator directory.');main.innerHTML='<div class="container guide"><h1>Calculator not found</h1><p>This tool may not be available yet.</p><a class="text-link" href="#/">Explore available calculators →</a></div>';}}if(!query)window.scrollTo(0,0);}
window.addEventListener('hashchange',route);
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){const input=document.querySelector('#search');if(input){e.preventDefault();input.focus();}}});

const storageList=key=>{try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?[...new Set(a.filter(x=>typeof x==='string'&&validUtilityIds.has(x)))].slice(0,validUtilityIds.size):[];}catch{return[];}};
const utilityKey=t=>(t.kind==='Tool'?'tool:':'calculator:')+t.id;
const validUtilityIds=new Set([...utilityCalculators,...tools].map(utilityKey));
function saveList(key,a){try{localStorage.setItem(key,JSON.stringify(a));}catch{}}
function remember(t){const id=utilityKey(t);saveList('calchub-recent',[id,...storageList('calchub-recent').filter(x=>x!==id)].slice(0,10));}
function favorite(t){const b=document.createElement('button');b.className='secondary favorite-toggle';const refresh=()=>{const active=storageList('calchub-favorites').includes(utilityKey(t));b.textContent=active?'★ Saved to favorites':'☆ Add to favorites';b.setAttribute('aria-pressed',active);};b.onclick=()=>{const a=storageList('calchub-favorites'),id=utilityKey(t);saveList('calchub-favorites',a.includes(id)?a.filter(x=>x!==id):[...a,id]);refresh();};refresh();main.querySelector('.tool-heading').append(b);}
function utilityDirectory(params,favorites=false){seo(favorites?'Favorites':'Online Tools','Free browser-local online tools for text, files, images, code and everyday work.');main.innerHTML='<div class="container tools-directory"><div class="tool-heading"><h1>'+ (favorites?'Favorites':'Online Tools')+'</h1><p>Process text and files locally. Search all calculators and tools.</p></div><div class="search-wrap"><input id="search" type="search" aria-label="Search calculators and tools" placeholder="Search tools and calculators"></div><div class="filters">'+['All',...toolCategories].map(c=>'<button class="filter" data-filter="'+escape(c)+'">'+escape(c)+'</button>').join('')+'</div><p id="result-count"></p><div class="grid" id="directory-results"></div><div class="pagination" id="pagination"></div><section id="recent-section"><h2>Recently used</h2><div class="grid" id="recent-results"></div></section></div>';let category='All',page=1;const search=main.querySelector('#search');search.value=params.get('q')||'';const all=[...utilityCalculators,...tools];function draw(){const base=favorites?all.filter(t=>storageList('calchub-favorites').includes(utilityKey(t))):search.value&&category==='All'?all:tools;const found=findCalculators(base,search.value,category);main.querySelector('#directory-results').innerHTML=found.slice((page-1)*24,page*24).map(card).join('')||'<p>No utilities found. Add favorites from a utility page.</p>';main.querySelector('#result-count').textContent=found.length+' available';main.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===category);b.setAttribute('aria-pressed',b.dataset.filter===category);});main.querySelector('#pagination').innerHTML='<button class="secondary" data-step="-1" '+(page===1?'disabled':'')+'>Previous</button><span>Page '+page+' of '+Math.max(1,Math.ceil(found.length/24))+'</span><button class="secondary" data-step="1" '+(page*24>=found.length?'disabled':'')+'>Next</button>';main.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{page+=Number(b.dataset.step);draw();});}search.oninput=()=>{page=1;draw();};main.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;page=1;draw();});main.querySelector('#recent-results').innerHTML=storageList('calchub-recent').map(id=>all.find(t=>utilityKey(t)===id)).filter(Boolean).map(card).join('')||'<p>Your recently opened utilities will appear here.</p>';draw();}

route();
