import {advancedAliases,aliasInstructions} from './data/advanced-aliases.js';
import { aliasesById } from './data/aliases.js';
import { expansionTools } from './data/expansion.js';
import { extendedCalculators } from './extended-catalog.js';
const number = (name,label,value,min=0,extra={}) => ({name,label,value,min:min===null?undefined:min,type:'number',...extra});
const select = (name,label,options,value) => ({name,label,options,value,type:'select'});
const date = (name,label,value) => ({name,label,value,type:'date'});
export const today = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const originalCategories = [ ['Finance','₹',10], ['Business','▥',6], ['Math','∑',9], ['Date & Time','◷',5], ['Health','♡',4], ['Converters','⇄',7], ['Construction','▱',5] ];
export const calculators = [
 {id:'gst',name:'GST Calculator',category:'Finance',icon:'₹',description:'Add or remove GST in a few simple steps.',fields:[number('amount','Amount (₹)',10000),number('rate','GST rate (%)',18,0,{max:100}),select('mode','Calculation type',[['add','Add GST'],['remove','Remove GST (inclusive)']],'add')],formula:'GST = Base amount × Rate / 100; Inclusive base = Total / (1 + Rate / 100)',example:'₹10,000 at 18% GST gives ₹1,800 tax and a final amount of ₹11,800.',how:'Enter your amount, choose a tax rate, then select whether to add GST or extract it from an inclusive amount.',faq:['Why are CGST and SGST equal?','For an intra-state supply, the total GST is split equally into CGST and SGST. For an inter-state supply, the same total tax is generally IGST.']},
 {id:'emi',name:'EMI Calculator',category:'Finance',icon:'▥',description:'Plan your loan with a clear monthly payment.',fields:[number('principal','Loan amount (₹)',500000,0,{exclusiveMin:true}),number('rate','Annual interest rate (%)',8.5),number('tenure','Loan tenure',5,0,{exclusiveMin:true}),select('unit','Tenure unit',[['years','Years'],['months','Months']],'years')],formula:'EMI = P × r / (1 − (1 + r)⁻ⁿ), where r = annual rate / 1200',example:'A ₹5,00,000 loan at 8.5% for 5 years has an EMI of approximately ₹10,258.',how:'Enter the loan principal, annual interest rate and tenure. Choose years or months to see the monthly payment and total interest.',faq:['Does this include bank fees?','No. This estimate uses a fixed rate and monthly repayments. Processing fees, insurance and lender rounding are excluded.']},
 {id:'sip',name:'SIP Calculator',category:'Finance',icon:'↗',description:'See how regular investments could grow.',fields:[number('payment','Monthly investment (₹)',5000,0,{exclusiveMin:true}),number('rate','Expected annual return (%)',12),number('years','Investment duration (years)',10,0,{exclusiveMin:true})],formula:'FV = M × ((1 + r)ⁿ − 1) / r × (1 + r); r = annual return / 1200',example:'₹5,000 invested monthly for 10 years at an assumed 12% annual return grows to about ₹11,61,695.',how:'Enter your monthly contribution, assumed annual return and duration. Contributions are assumed at the start of each month.',faq:['Are the returns guaranteed?','No. Returns are hypothetical, use a constant monthly growth rate and exclude taxes, fees and market fluctuations.']},
 {id:'percentage',name:'Percentage Calculator',category:'Math',icon:'%',description:'Find a percentage of any number instantly.',fields:[number('percent','Percentage (%)',20,null),number('value','Number',250,null)],formula:'Result = Percentage × Number / 100',example:'20% of 250 is 50.',how:'Enter the percentage and the number to find that portion. Negative numbers and percentages above 100 are supported.',faq:['Can I use a percentage greater than 100?','Yes. For example, 150% of 200 is 300.']},
 {id:'discount',name:'Discount Calculator',category:'Finance',icon:'%',description:'Know what you save and what you pay.',fields:[number('price','Original price (₹)',2000),number('rate','Discount (%)',15,0,{max:100})],formula:'Savings = Price × Discount / 100; Final price = Price − Savings',example:'A 15% discount on ₹2,000 saves ₹300. You pay ₹1,700.',how:'Enter the original price and discount percentage to see your savings and the final price.',faq:['Is tax included?','This calculator applies only the discount. Any additional tax or shipping must be calculated separately.']},
 {id:'simple-interest',name:'Simple Interest Calculator',category:'Finance',icon:'₹',description:'Calculate interest on your original principal.',fields:[number('principal','Principal (₹)',10000),number('rate','Annual interest rate (%)',5),number('years','Time (years)',3)],formula:'Interest = Principal × Annual rate × Years / 100',example:'₹10,000 at 5% for 3 years earns ₹1,500, giving a total of ₹11,500.',how:'Enter the principal, annual interest rate and time in years. You can use decimals for part of a year.',faq:['How does this differ from compound interest?','Simple interest is calculated only on the original principal. Compound interest also earns interest on previously accumulated interest.']},
 {id:'compound-interest',name:'Compound Interest Calculator',category:'Finance',icon:'↗',description:'Explore the power of interest on interest.',fields:[number('principal','Principal (₹)',10000),number('rate','Annual interest rate (%)',5),number('years','Time (years)',3),select('frequency','Compounding frequency',[['1','Annually'],['2','Half-yearly'],['4','Quarterly'],['12','Monthly'],['365','Daily']],'1')],formula:'Final amount = P × (1 + rate / (100 × n))^(n × years)',example:'₹10,000 at 5%, compounded annually for 3 years, becomes ₹11,576.25.',how:'Enter the principal, annual rate and duration, then choose how often interest compounds.',faq:['Does this account for extra deposits?','No. This calculator assumes one initial deposit and no withdrawals or additional contributions.']},
 {id:'age',name:'Age Calculator',category:'Date & Time',icon:'◷',description:'Your exact age in years, months and days.',fields:[date('birth','Date of birth','2000-01-01'),date('reference','Age as of',today())],formula:'Calendar age = complete years + complete months + remaining days',example:'From 1 January 2000 to 1 January 2025 is exactly 25 years.',how:'Choose your date of birth and a reference date. The result also shows the next birthday relative to that reference date.',faq:['How are leap-day birthdays handled?','A 29 February birthday is treated as 28 February in non-leap years. Month-end dates are clamped to the last valid day of the destination month.']},
 {id:'bmi',name:'BMI Calculator',category:'Health',icon:'♡',description:'Understand your body mass index in seconds.',fields:[number('weight','Weight (kg)',70,0,{exclusiveMin:true}),number('height','Height',175,0,{exclusiveMin:true}),select('unit','Height unit',[['cm','Centimeters (cm)'],['m','Meters (m)']],'cm')],formula:'BMI = Weight (kg) / Height (m)²',example:'At 70 kg and 175 cm, BMI is 22.9, within the standard healthy weight category.',how:'Enter your weight in kilograms and height in centimeters or meters. This calculator uses standard adult BMI categories.',note:'Informational adult screening measure, not medical advice. BMI does not account for muscle mass, pregnancy or individual health.',faq:['Is BMI a diagnosis?','No. BMI is a general adult screening measure and does not account for muscle mass, pregnancy or individual health. Children and teens need age-specific assessment.']},
 {id:'length',name:'Length Converter',category:'Converters',icon:'⇄',description:'Convert metric and imperial measurements.',fields:[number('value','Length',1),select('from','From',[['mm','Millimeters'],['cm','Centimeters'],['m','Meters'],['km','Kilometers'],['in','Inches'],['ft','Feet'],['yd','Yards'],['mi','Miles']],'m'),select('to','To',[['mm','Millimeters'],['cm','Centimeters'],['m','Meters'],['km','Kilometers'],['in','Inches'],['ft','Feet'],['yd','Yards'],['mi','Miles']],'ft')],formula:'Converted value = Value × Source factor in meters / Target factor in meters',example:'1 meter equals approximately 3.28084 feet.',how:'Enter a length and select the source and target units. The result updates when you calculate.',faq:['Which definition of a foot is used?','The international foot is used: exactly 0.3048 meters.']},
 {id:'temperature',name:'Temperature Converter',category:'Converters',icon:'°',description:'Switch between Celsius, Fahrenheit and Kelvin.',fields:[number('value','Temperature',25,null),select('from','From',[['C','Celsius (°C)'],['F','Fahrenheit (°F)'],['K','Kelvin (K)']],'C'),select('to','To',[['C','Celsius (°C)'],['F','Fahrenheit (°F)'],['K','Kelvin (K)']],'F')],formula:'°F = °C × 9/5 + 32; K = °C + 273.15',example:'25°C equals 77°F or 298.15 K.',how:'Enter a temperature and choose its current unit and the target unit. Values below absolute zero are rejected.',faq:['Can temperatures be negative?','Yes, Celsius and Fahrenheit can be negative. Kelvin cannot be below zero.']},
 {id:'basic',name:'Basic Calculator',category:'Math',icon:'+',description:'The everyday essentials, all in one place.',fields:[{name:'expression',label:'Expression',type:'text',value:'12 × (8 + 2)'}],formula:'Parentheses first, then multiplication and division, then addition and subtraction.',example:'12 × (8 + 2) = 120.',how:'Type an expression or use the keypad. Press Enter or the equals button to calculate. Use parentheses to group operations.',faq:['Does it follow the order of operations?','Yes. Multiplication and division take precedence over addition and subtraction. Parentheses override that order.']}
];
calculators.push(...extendedCalculators);
calculators.push(...expansionTools);
for(const c of calculators){
  c.aliases=[...new Set([...(c.aliases||[]),...(aliasesById[c.id]||[]),...(advancedAliases[c.id]||[]),...(c.advanced?c.name.replace(/ Calculator$/, '').split(' / '):[])])];
  if(aliasInstructions[c.id])c.how+=' '+aliasInstructions[c.id];
  for(const field of c.fields)if(field.type==='text'&&['numbers','weights','values'].includes(field.name))field.multiline=true;
  if(c.category==='Health'&&!c.note?.includes('For informational purposes only. This is not medical advice.'))c.note='For informational purposes only. This is not medical advice. '+(c.note||'');
}
const icons=Object.fromEntries(originalCategories.map(([name,icon])=>[name,icon]));
export const categories=[...new Set(calculators.map(c=>c.category))].map(name=>[name,icons[name]||expansionTools.find(c=>c.category===name)?.icon||'◇',calculators.filter(c=>c.category===name).length]);
export const directory = calculators;
