import {tools,toolCategories} from '../js/tools/catalog.js';
import {calculators} from '../js/catalog.js';
const frame=document.querySelector('#site'),out=document.querySelector('#output'),rows=[],errors=[];
const saved=Object.fromEntries(['calchub-favorites','calchub-recent','calchub-theme'].map(k=>[k,localStorage.getItem(k)]));
const pause=()=>new Promise(r=>setTimeout(r,25)),doc=()=>frame.contentDocument;
async function wait(fn){for(let i=0;i<400;i++){if(fn())return;await pause();}throw Error('Timed out waiting for tool state');}
function check(name,x){rows.push((x?'PASS ':'FAIL ')+name);out.textContent=rows.join('\n');}
async function go(hash){frame.contentWindow.location.hash=hash;await pause();await wait(()=>doc()?.querySelector('#main'));}
async function dropFixture(t){const choices=t.id==='pdf-image-watermark'?['sample.pdf','sample.png']:t.id==='pdf-merge'?['sample.pdf','sample.pdf']:t.module==='pdf'&&t.id!=='images-to-pdf'?['sample.pdf']:t.module==='image'||t.id==='images-to-pdf'?['sample.png']:['sample.csv'];const transfer=new DataTransfer();for(const name of choices){const bytes=await (await fetch('fixtures/'+name)).arrayBuffer();transfer.items.add(new File([bytes],name,{type:name.endsWith('.pdf')?'application/pdf':name.endsWith('.png')?'image/png':'text/csv'}));}doc().querySelector('#drop-zone').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}));}
try{await wait(()=>doc()?.querySelector('#search'));check('Homepage loads no heavy vendor libraries',!frame.contentWindow.performance.getEntriesByType('resource').some(e=>e.name.includes('/assets/vendor/')));check('Homepage resources are local',frame.contentWindow.performance.getEntriesByType('resource').every(e=>e.name.startsWith(location.origin))); frame.contentWindow.addEventListener('error',e=>errors.push(e.message));frame.contentWindow.addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
 await go('/tools');const routes=new Set();for(let page=0;page<20;page++){doc().querySelectorAll('#directory-results a').forEach(a=>routes.add(a.getAttribute('href')));const next=doc().querySelector('[data-step="1"]');if(next.disabled)break;next.click();await pause();}check('Tool pagination exposes all routes',routes.size===tools.length&&tools.every(t=>routes.has(t.route)));
 for(const c of toolCategories){doc().querySelector(`[data-filter="${c}"]`).click();check(c+' category count',doc().querySelector('#result-count').textContent===tools.filter(t=>t.category===c).length+' available');}
 await go('/');for(const query of ['GST','EMI','PDF merge','image compressor','JSON','QR','password','word counter','SEO','CSV']){const s=doc().querySelector('#search');s.value=query;s.dispatchEvent(new Event('input',{bubbles:true}));check('Global search '+query,doc().querySelectorAll('#directory-results a').length>0);check('Search kind label '+query,[...doc().querySelectorAll('.utility-kind')].every(x=>['Tool','Calculator'].includes(x.textContent)));}
 for(const t of tools){await go('/tool/'+t.id);await wait(()=>doc().querySelector('h1')?.textContent===t.name);check(t.id+' unique H1 and title',doc().querySelectorAll('h1').length===1&&doc().title.includes(t.name));check(t.id+' mobile has no horizontal overflow',doc().documentElement.scrollWidth<=390);check(t.id+' privacy and controls',doc().querySelector('#tool-clear')&&doc().querySelector('#tool-download')&&doc().body.textContent.includes('Input content is not saved'));const required=t.fields.find(f=>!f.optional&&f.type!=='color');if(required){doc().querySelector('#tool-'+required.name).value='';doc().querySelector('#tool-form').requestSubmit();check(t.id+' empty required input rejected',!!doc().querySelector('#tool-error').textContent);doc().querySelector('[type=\"reset\"]').click();}else if(t.files&&!t.optionalFiles){doc().querySelector('#tool-form').requestSubmit();check(t.id+' missing file rejected',!!doc().querySelector('#tool-error').textContent);}const numeric=t.fields.find(f=>f.type==='number');if(numeric){doc().querySelector('#tool-'+numeric.name).value=String(numeric.max+1);doc().querySelector('#tool-form').requestSubmit();check(t.id+' out-of-range number rejected',!!doc().querySelector('#tool-error').textContent);doc().querySelector('[type=\"reset\"]').click();}if(t.module==='timers')continue;if(t.files&&!t.optionalFiles){await dropFixture(t);check(t.id+' file info shown',doc().querySelector('#file-info').textContent.includes('sample.'));}if(t.id==='password-strength')doc().querySelector('#tool-input').value='LongDemoPassword123!';doc().querySelector('#tool-form').requestSubmit();await wait(()=>doc().querySelector('#tool-status').textContent.startsWith('Done')||doc().querySelector('#tool-error').textContent);check(t.id+' Process succeeds',!doc().querySelector('#tool-error').textContent);if(doc().querySelector('#tool-output').value)check(t.id+' copy/download enabled',!doc().querySelector('#tool-copy').disabled&&!doc().querySelector('#tool-download').disabled);doc().querySelector('#tool-clear').click();check(t.id+' Clear discards result',!doc().querySelector('#tool-output').value&&doc().querySelector('#tool-copy').disabled);doc().querySelector('[type="reset"]').click();check(t.id+' Reset restores examples',t.fields.every(f=>String(doc().querySelector('#tool-'+f.name).value)===String(f.value??'')));}
 await go('/tool/csv-tools');doc().querySelector('#tool-clear').click();const transfer=new DataTransfer();transfer.items.add(new File(['name,score\nAlex,10'],'sample.csv',{type:'text/csv'}));doc().querySelector('#drop-zone').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}));doc().querySelector('#tool-form').requestSubmit();await wait(()=>doc().querySelector('#tool-status').textContent.startsWith('Done')||doc().querySelector('#tool-error').textContent);check('CSV file works after Clear without pasted input',!doc().querySelector('#tool-error').textContent);check('Structured download uses JSON extension',doc().querySelector('#tool-download').textContent==='Download .json');
 await go('/tool/text-counter');doc().querySelector('.favorite-toggle').click();check('Tool favorite saved as ID',JSON.parse(localStorage.getItem('calchub-favorites')).includes('tool:text-counter'));await go('/calculator/gst');doc().querySelector('.favorite-toggle').click();check('Calculator favorite saved as ID',JSON.parse(localStorage.getItem('calchub-favorites')).includes('calculator:gst'));await go('/favorites');check('Favorites includes both kinds',doc().querySelector('#directory-results').textContent.includes('GST')&&doc().querySelector('#directory-results').textContent.includes('Word'));check('Recent includes both kinds',doc().querySelector('#recent-results').textContent.includes('GST')&&doc().querySelector('#recent-results').textContent.includes('Word'));const recent=JSON.parse(localStorage.getItem('calchub-recent'));check('Recent stores only IDs, bounded at ten',recent.length<=10&&recent.every(x=>/^(tool|calculator):[a-z0-9-]+$/.test(x)));
 await go('/tool/browser-timer');const form=doc().querySelector('#tool-form');form.elements.seconds.value='1';form.requestSubmit();await wait(()=>doc().querySelector('.timer-display'));doc().querySelector('#tool-preview button').click();await new Promise(r=>setTimeout(r,1200));check('Countdown completes visibly',doc().querySelector('#tool-preview').textContent.includes('Time is up.'));check('Completed countdown holds zero',doc().querySelector('.timer-display').textContent==='00:00:00');doc().querySelector('#tool-clear').click();check('Clear removes timer controls',!doc().querySelector('.timer-display'));await go('/tools');const theme=doc().documentElement.dataset.theme;doc().querySelector('#theme-toggle').click();check('Tools dark/light mode toggles',doc().documentElement.dataset.theme!==theme);check('No unhandled application errors',errors.length===0);
}catch(e){check('Integration completes: '+e.message,false);}finally{for(const [k,v]of Object.entries(saved))v===null?localStorage.removeItem(k):localStorage.setItem(k,v);}
out.textContent=rows.join('\n')+'\n\n'+rows.filter(x=>x.startsWith('PASS')).length+'/'+rows.length+' passed';
