import {tool,n,p,i,r,txt,divide,requireCondition as check} from './shared.js';
const A='Algebra';
const signed=(name,label,value)=>n(name,label,value,null);
const points=()=>[signed('x1','First x',0),signed('y1','First y',0),signed('x2','Second x',3),signed('y2','Second y',4)];
export const algebraTools=[
  tool('quadratic','Quadratic Equation',A,'Find real roots of ax² + bx + c = 0 and its discriminant.',[signed('a','Coefficient a',1),signed('b','Coefficient b',-3),signed('c','Coefficient c',2)],'D = b² − 4ac; roots = (−b ± sqrt(D)) / (2a)',v=>{check(v.a!==0,'Coefficient a must be nonzero; use Linear Equation otherwise.');const D=v.b*v.b-4*v.a*v.c;if(D<0)return[txt('Real roots','No real roots'),r('Discriminant',D)];const q=-.5*(v.b+(v.b>=0?1:-1)*Math.sqrt(D));const x1=q/v.a,x2=q===0?x1:v.c/q;return[r('First real root',x1),r('Second real root',x2),r('Discriminant',D)];},2),
  tool('linear-equation','Linear Equation',A,'Solve ax + b = c with a substitution breakdown.',[signed('a','Coefficient a',2),signed('b','Constant b',3),signed('c','Right-hand side c',11)],'x = (c − b) / a',v=>[r('Solution x',divide(v.c-v.b,v.a)),txt('Rearranged equation',`${v.a}x = ${v.c-v.b}`)],4),
  tool('linear-two','Two-Variable Linear Equation',A,'Solve two simultaneous linear equations with unique solutions.',[signed('a','Equation 1 x coefficient',1),signed('b','Equation 1 y coefficient',1),signed('c','Equation 1 right side',3),signed('d','Equation 2 x coefficient',1),signed('e','Equation 2 y coefficient',-1),signed('f','Equation 2 right side',1)],'D = ae−bd; x = (ce−bf)/D; y = (af−cd)/D',v=>{const D=v.a*v.e-v.b*v.d;check(D!==0,'The equations do not have a unique solution (determinant is zero).');return[r('Solution x',(v.c*v.e-v.b*v.f)/D),r('Solution y',(v.a*v.f-v.c*v.d)/D),r('Determinant',D)];},2),
  tool('slope','Slope',A,'Compute rise over run between two points.',points(),'Slope = (y₂ − y₁) / (x₂ − x₁)',v=>{check(v.x1!==v.x2,'A vertical line has no finite slope.');return[r('Slope',(v.y2-v.y1)/(v.x2-v.x1))];},4/3),
  tool('point-slope','Point-Slope',A,'Convert a point and slope into slope-intercept form.',[signed('x','Point x',2),signed('y','Point y',5),signed('slope','Slope m',3)],'b = y₁ − m×x₁; equation y = mx + b',v=>[r('Y-intercept b',v.y-v.slope*v.x),txt('Line equation',`y = ${v.slope}x + (${v.y-v.slope*v.x})`)],-1),
  tool('point-distance','Distance Between Two Points',A,'Calculate straight-line distance in a Cartesian plane.',points(),'Distance = sqrt((x₂−x₁)² + (y₂−y₁)²)',v=>[r('Distance (coordinate units)',Math.hypot(v.x2-v.x1,v.y2-v.y1))],5),
  tool('midpoint','Midpoint',A,'Find the point halfway between two coordinates.',points(),'Midpoint = ((x₁+x₂)/2, (y₁+y₂)/2)',v=>[r('Midpoint x',v.x1/2+v.x2/2),r('Midpoint y',v.y1/2+v.y2/2)],1.5),
  tool('line-equation','Equation of Line',A,'Construct a general-form equation from two different points.',points(),'A = y₁−y₂; B = x₂−x₁; C = x₁y₂−x₂y₁; Ax+By+C = 0',v=>{check(v.x1!==v.x2||v.y1!==v.y2,'Choose two different points.');const a=v.y1-v.y2,b=v.x2-v.x1,c=v.x1*v.y2-v.x2*v.y1;return[txt('General-form equation',`${a}x + (${b})y + (${c}) = 0`),r('Coefficient A',a),r('Coefficient B',b),r('Constant C',c)];},'-4x + (3)y + (0) = 0'),
  tool('arithmetic-sequence','Arithmetic Sequence',A,'Find the nth term and finite sum of equally spaced terms.',[signed('a','First term',2),signed('difference','Common difference',3),i('n','Term count n',5,1)],'aₙ = a + (n−1)d; Sum = n×(a+aₙ)/2',v=>{const last=v.a+(v.n-1)*v.difference;return[r('Nth term',last),r('Sum of n terms',v.n*(v.a+last)/2)];},14),
  tool('geometric-sequence','Geometric Sequence',A,'Find a term and sum in a constant-ratio sequence.',[signed('a','First term',2),signed('ratio','Common ratio',3),i('n','Term count n',4,1)],'aₙ = a×ratio^(n−1); Sum = a×(ratio^n−1)/(ratio−1)',v=>[r('Nth term',v.a*v.ratio**(v.n-1)),r('Sum of n terms',v.ratio===1?v.a*v.n:v.a*(v.ratio**v.n-1)/(v.ratio-1))],54)
];
