import {make,n,p,i,r,check} from './advanced-shared.js';
import {m} from './shared.js';
const T=make('Automotive');
export const automotiveTools=[
 T('vehicle-depreciation','Vehicle Depreciation','Estimate value after constant percentage depreciation and a chosen residual floor.',[n('price','Starting vehicle value (₹)',1000000),n('rate','Annual depreciation (%)',20,0,{max:100}),n('years','Years elapsed',3),n('floor','Assumed minimum residual value (₹)',0)],'Estimated value=max(Residual floor, Starting value×(1−Rate)^Years)',v=>{check(v.floor<=v.price,'Residual floor cannot exceed starting value.');const value=Math.max(v.floor,v.price*(1-v.rate/100)**v.years);return[m('Estimated vehicle value',value),m('Value lost',v.price-value)];},512000,{note:'Illustrative constant-rate model, not a vehicle appraisal. Market demand, condition, mileage and depreciation tax rules are excluded.'}),
 T('ev-range','EV / Battery Range','Estimate range from nominal energy, usable fraction and vehicle consumption.',[n('energy','Battery nominal energy (kWh)',60),n('usable','Usable fraction / available charge (%)',90,0,{max:100}),p('consumption','Consumption (kWh/100 km)',15)],'Range(km)=Nominal kWh×Usable fraction×100/Consumption',v=>[r('Estimated range (km)',v.energy*v.usable/100*100/v.consumption),r('Usable energy (kWh)',v.energy*v.usable/100)],360,{aliases:['EV range','battery range'],note:'Constant consumption assumption; actual range depends on speed, terrain, temperature, degradation and accessories.'}),
 T('ev-cost','EV Charging Cost','Estimate wall-energy charging cost including entered charging losses.',[n('energy','Battery energy to add (kWh)',30),p('efficiency','Charging efficiency (%)',90,{max:100}),n('tariff','Electricity tariff (₹/kWh)',8)],'Wall energy=Battery energy/Efficiency; Cost=Wall energy×Tariff',v=>[m('Estimated charging cost',v.energy/(v.efficiency/100)*v.tariff),r('Wall energy required (kWh)',v.energy/(v.efficiency/100))],266.6666666667,{aliases:['EV charging cost'],note:'Single entered energy tariff; session fees, time-based charges, taxes and demand/slab charges are excluded.'}),
 T('tire-size','Tire Size / Diameter / Speedometer Error','Compare metric tire dimensions and resulting theoretical road-speed change.',[p('width','Original tire width (mm)',205),p('aspect','Original aspect ratio (%)',55,{max:100}),p('rim','Original rim diameter (inches)',16),p('newWidth','New tire width (mm)',225),p('newAspect','New aspect ratio (%)',45,{max:100}),p('newRim','New rim diameter (inches)',17),n('speed','Indicated speed (km/h)',100)],'Diameter(mm)=Rim(in)×25.4+2×Width×Aspect/100; Actual speed=Indicated×New diameter/Old diameter',v=>{const old=v.rim*25.4+2*v.width*v.aspect/100,next=v.newRim*25.4+2*v.newWidth*v.newAspect/100;return[r('Original theoretical diameter (mm)',old),r('New theoretical diameter (mm)',next),r('Theoretical actual speed (km/h)',v.speed*next/old),r('Diameter change (%)',(next/old-1)*100)];},631.9,{aliases:['tire size','tire diameter','speedometer error'],note:'Nominal geometry only; loaded rolling radius, tire wear and OEM speedometer calibration differ. Does not establish tire fitment, clearance or safety approval.'})
];
