import { tool,n,p,i,s,r,m,divide,requireCondition as check } from './shared.js';
const B='Business';
export const businessTools=[
  tool('revenue','Revenue',B,'Estimate revenue from quantity sold and unit selling price.',[n('quantity','Units sold',100),n('price','Price per unit (₹)',20)],'Revenue = Units × Unit price',v=>[m('Revenue',v.quantity*v.price)],2000),
  tool('net-profit','Net Profit',B,'Calculate profit after direct and operating costs.',[n('revenue','Revenue (₹)',10000),n('cost','Cost of goods (₹)',4000),n('expense','Other expenses (₹)',2000)],'Net profit = Revenue − Cost of goods − Other expenses',v=>[m('Net profit / loss',v.revenue-v.cost-v.expense)],4000),
  tool('operating-margin','Operating Margin',B,'Express operating profit as a percentage of revenue.',[p('revenue','Revenue (₹)',10000),n('goods','Cost of goods (₹)',4000),n('operating','Operating expenses (₹)',2000)],'Operating margin (%) = (Revenue − Goods cost − Operating expenses) / Revenue × 100',v=>[r('Operating margin (%)',(v.revenue-v.goods-v.operating)/v.revenue*100)],40,{note:'Excludes interest and income tax; expenses must be operating expenses.'}),
  tool('contribution-margin','Contribution Margin',B,'Measure the contribution of a unit toward fixed costs.',[p('price','Unit selling price (₹)',100),n('variable','Variable cost per unit (₹)',60)],'Contribution = Unit price − Variable cost; Ratio = Contribution / Price × 100',v=>[m('Contribution per unit',v.price-v.variable),r('Contribution ratio (%)',(v.price-v.variable)/v.price*100)],40),
  tool('unit-price','Unit Price',B,'Compare cost per measured unit or item.',[n('price','Total price (₹)',300),p('quantity','Quantity (same unit for comparisons)',2)],'Unit price = Total price / Quantity',v=>[m('Price per unit',v.price/v.quantity)],150,{aliases:['cost per unit','price per unit']}),
  tool('selling-price','Selling Price',B,'Find the selling price required for a target gross margin.',[n('cost','Unit cost (₹)',80),n('margin','Target margin (%)',20,0,{max:99.999})],'Selling price = Cost / (1 − Margin/100)',v=>[m('Required selling price',v.cost/(1-v.margin/100))],100),
  tool('cost-price','Cost Price',B,'Recover cost price from selling price and markup.',[n('selling','Selling price (₹)',120),n('markup','Markup on cost (%)',20)],'Cost = Selling price / (1 + Markup/100)',v=>[m('Cost price',v.selling/(1+v.markup/100))],100),
  tool('target-profit','Target Profit',B,'Estimate sales needed to cover fixed costs and a profit target.',[n('fixed','Fixed costs (₹)',1000),n('target','Target profit (₹)',1000),p('price','Unit selling price (₹)',100),n('variable','Variable unit cost (₹)',50)],'Required units = ceil((Fixed costs + Target profit) / (Price − Variable cost))',v=>{check(v.price>v.variable,'Selling price must exceed variable unit cost.');return[r('Required units',Math.ceil((v.fixed+v.target)/(v.price-v.variable)),'number')];},40),
  tool('sales-tax','Sales Tax',B,'Add or extract a user-supplied sales tax or VAT rate.',[n('amount','Amount (₹)',100),n('rate','Tax rate supplied by you (%)',10),s('mode','Amount type',[['net','Before tax'],['gross','Tax inclusive']],'net')],'Gross = Net × (1 + Rate/100); Net = Gross / (1 + Rate/100)',v=>{const net=v.mode==='net'?v.amount:v.amount/(1+v.rate/100);return[m('Total including tax',net*(1+v.rate/100)),m('Net amount',net),m('Tax amount',net*v.rate/100)];},110,{aliases:['VAT'],note:'No statutory rate is assumed; enter the rate applicable to your transaction. Currency is a display choice.'}),
  tool('roas','ROAS',B,'Compare attributable ad revenue with advertising spend.',[n('revenue','Attributable revenue (₹)',10000),p('spend','Ad spend (₹)',2000)],'ROAS = Ad revenue / Ad spend',v=>[r('Revenue per rupee spent',v.revenue/v.spend),r('ROAS (%)',v.revenue/v.spend*100)],5),
  tool('cpm','CPM',B,'Calculate advertising cost per thousand impressions.',[n('cost','Campaign cost (₹)',500),p('impressions','Impressions',10000)],'CPM = Cost / Impressions × 1000',v=>[m('Cost per 1,000 impressions',v.cost/v.impressions*1000)],50),
  tool('cpc','CPC',B,'Calculate the average cost of an advertising click.',[n('cost','Ad spend (₹)',1000),p('clicks','Clicks',100)],'CPC = Ad spend / Clicks',v=>[m('Cost per click',v.cost/v.clicks)],10),
  tool('cpa','CPA',B,'Find advertising cost per recorded acquisition or lead.',[n('cost','Campaign cost (₹)',1000),p('actions','Acquisitions or leads',20)],'CPA = Campaign cost / Actions',v=>[m('Cost per action',v.cost/v.actions)],50,{aliases:['cost per lead']}),
  tool('customer-acquisition','Customer Acquisition Cost',B,'Allocate total sales and marketing expense across new customers.',[n('marketing','Marketing expense (₹)',1000),n('sales','Sales expense (₹)',1000),p('customers','New customers',20)],'CAC = (Marketing + Sales expense) / New customers',v=>[m('Cost per new customer',(v.marketing+v.sales)/v.customers)],100),
  tool('conversion-rate','Conversion Rate',B,'Measure conversions as a fraction of total eligible visits.',[n('conversions','Conversions',25),p('visits','Visits',1000)],'Conversion rate (%) = Conversions / Visits × 100',v=>{check(v.conversions<=v.visits,'Conversions cannot exceed visits when measuring a per-visit conversion rate.');return[r('Conversion rate (%)',v.conversions/v.visits*100)];},2.5)
];
export const salaryTools=[
  tool('salary','Salary','Tax & Salary','Convert gross annual salary into monthly, weekly and hourly equivalents.',[n('annual','Annual gross pay (₹)',624000),p('weeks','Paid weeks per year',52),p('hours','Hours per paid week',40)],'Monthly = Annual/12; Weekly = Annual/Weeks; Hourly = Annual/(Weeks×Hours)',v=>[m('Monthly gross pay',v.annual/12),m('Weekly gross pay',v.annual/v.weeks),m('Hourly gross pay',v.annual/(v.weeks*v.hours))],52000,{note:'Gross-pay conversion only; does not apply income tax or labor-law rules.'}),
  tool('take-home','Take-Home Salary','Tax & Salary','Estimate cash salary after deductions that you enter.',[n('ctc','Annual compensation / CTC (₹)',600000),n('noncash','Annual non-cash employer benefits (₹)',24000),n('deductions','Annual tax and employee deductions (₹)',36000)],'Monthly cash = (Annual CTC − Non-cash benefits − Annual deductions) / 12',v=>{check(v.noncash+v.deductions<=v.ctc,'Benefits plus deductions cannot exceed annual compensation.');return[m('Estimated monthly take-home',(v.ctc-v.noncash-v.deductions)/12)];},45000,{aliases:['CTC to in-hand salary'],note:'Manual-deduction estimate. Does not infer tax slabs, PF deductions, exemptions or current law.'}),
  tool('overtime','Overtime','Tax & Salary','Calculate overtime pay from hours and your agreed pay multiplier.',[n('hours','Overtime hours',10),n('rate','Base hourly pay (₹)',200),p('multiplier','Agreed overtime multiplier',1.5)],'Overtime pay = Hours × Base hourly rate × Multiplier',v=>[m('Overtime pay',v.hours*v.rate*v.multiplier)],3000,{note:'Multiplier is user-supplied; no statutory entitlement or labor-law rate is assumed.'})
];
