import {make,n,p,t,s,r,txt,check} from './advanced-shared.js';
import {atomicWeights} from '../data/atomic-weights.js';
const T=make('Chemistry'),note='Educational calculation tool. Not a laboratory preparation procedure, chemical handling instruction or clinical recommendation.';
export function molarMass(formula){check(formula.length<=200,'Use a formula with at most 200 characters.');let at=0;function count(){const match=formula.slice(at).match(/^\d+/);if(!match)return 1;at+=match[0].length;const n=Number(match[0]);check(n>=1&&n<=1000000,'Subscripts must be integers from 1 to 1,000,000.');return n;}function group(depth=0){check(depth<=10,'Use at most 10 nested groups.');let total=0,terms=0;while(at<formula.length&&formula[at]!==')'){if(formula[at]==='('){at++;const value=group(depth+1);check(formula[at]===')','Close every formula parenthesis.');at++;total+=value*count();}else{const match=formula.slice(at).match(/^[A-Z][a-z]?/);check(!!match,'Use element symbols, integer subscripts and parentheses only.');const symbol=match[0];check(atomicWeights[symbol]!==undefined,`Unsupported element ${symbol}. Supported symbols: ${Object.keys(atomicWeights).join(', ')}.`);at+=symbol.length;total+=atomicWeights[symbol]*count();}terms++;}check(terms>0,'Formula groups must contain elements.');return total;}const value=group();check(at===formula.length,'Unexpected closing parenthesis in formula.');return value;}
export const chemistryTools=[
 T('molar-mass','Molar Mass','Calculate molar mass for formulas using supported elements and nested parentheses.',[t('formula','Chemical formula (case sensitive)','H2O')],'Molar mass = Σ(element atom count × standard atomic weight)',v=>[r('Molar mass (g/mol)',molarMass(v.formula))],18.015,{note:note+' Selected common elements from CIAAW 2024 abridged weights; unsupported elements, isotope labels, charges and hydrate-dot notation are rejected. Supported symbols: '+Object.keys(atomicWeights).join(', ')+'.',source:{title:'CIAAW abridged atomic weights 2024',url:'https://www.ciaaw.org/abridged-atomic-weights.htm'}}),
 T('moles-mass','Moles / Mass Conversion','Convert amount of substance and mass with a supplied molar mass.',[n('mass','Mass (g)',18),n('moles','Amount (mol)',1),p('molar','Molar mass (g/mol)',18),s('solve','Convert to',[['moles','Moles from mass'],['mass','Mass from moles']],'moles')],'n=Mass/Molar mass; Mass=n×Molar mass',v=>[r(v.solve==='moles'?'Amount (mol)':'Mass (g)',v.solve==='moles'?v.mass/v.molar:v.moles*v.molar)],1,{aliases:['moles','mole to mass','mass to mole'],note}),
 T('solution-concentration','Molarity / Molality','Calculate molarity from solution volume or molality from solvent mass.',[n('amount','Solute amount (mol)',2),p('volume','Total solution volume (L; molarity mode)',1),p('solvent','Solvent mass (kg; molality mode)',1),s('basis','Concentration basis',[['molarity','Molarity'],['molality','Molality']],'molarity')],'Molarity=n/Total solution L; Molality=n/Solvent kg',v=>[r(v.basis==='molarity'?'Molarity (mol/L)':'Molality (mol/kg)',v.amount/(v.basis==='molarity'?v.volume:v.solvent))],2,{aliases:['molarity','molality'],note:note+' Solution volume and solvent mass are different denominators; molality uses solvent mass, not total solution mass.'}),
 T('dilution','Dilution','Calculate final volume or concentration for ideal solvent-only dilution.',[p('initial','Initial concentration (matching units)',2),p('volume1','Initial solution volume (L)',.1),p('final','Desired final concentration (same units)',.5),p('volume2','Final solution volume (L; concentration mode)',.4),s('solve','Solve for',[['volume','Final volume'],['concentration','Final concentration']],'volume')],'C₁V₁=C₂V₂; Added solvent volume=V₂−V₁',v=>{const volume=v.solve==='volume'?v.initial*v.volume1/v.final:v.volume2;check(volume>=v.volume1,'Solvent-only dilution cannot reduce the total volume or increase concentration.');return[r(v.solve==='volume'?'Final solution volume (L)':'Final concentration (input units)',v.solve==='volume'?volume:v.initial*v.volume1/volume),r('Ideal added solvent volume (L)',volume-v.volume1)];},.4,{note:note+' Conservation of solute and additive-volume approximation; mixing reactions, activity effects and volume contraction are excluded.'}),
 T('ph-poh','pH / pOH / Hydrogen Ion','Convert pH, pOH or hydrogen ion concentration under a supplied water-ion constant.',[n('value','pH / pOH / hydrogen concentration',7,null),s('kind','Input quantity',[['ph','pH'],['poh','pOH'],['hydrogen','[H⁺] in mol/L']],'ph'),p('pkw','pKw (14 at approximately 25°C)',14)],'pH=−log₁₀[H⁺]; pOH=pKw−pH; [H⁺]=10^(−pH)',v=>{if(v.kind==='hydrogen')check(v.value>0,'Hydrogen ion concentration must be positive.');const ph=v.kind==='ph'?v.value:v.kind==='poh'?v.pkw-v.value:-Math.log10(v.value),h=10**(-ph),oh=10**(-(v.pkw-ph));check(h>0&&oh>0,'Ion concentrations are outside the supported numerical range.');return[r('pH',ph),r('pOH',v.pkw-ph),r('Hydrogen ion concentration (mol/L)',h),r('Hydroxide ion concentration (mol/L)',oh)];},7,{aliases:['pH','pOH','pH to hydrogen ion','hydrogen ion to pH'],note:note+' Dilute aqueous concentration approximation to ion activity. pKw depends on temperature; default 14 applies around 25°C. Negative pH values are not automatically invalid.',source:{title:'OpenStax: pH and pOH',url:'https://openstax.org/books/chemistry-2e/pages/14-2-ph-and-poh'}})
];
