import {tool,n,p,r,txt,requireCondition as check,constructionNote} from './shared.js';
const C='Construction';
export const constructionTools=[
  tool('concrete-mix','Cement / Sand / Gravel',C,'Estimate nominal concrete mix ingredients using explicitly chosen assumptions.',[n('volume','Wet concrete volume (m³)',2),p('dry','Assumed dry-volume factor',1.54),p('cement','Cement volume parts',1),p('sand','Sand volume parts',2),p('gravel','Gravel volume parts',4),p('density','Assumed bulk cement density (kg/m³)',1440),p('bag','Bag mass (kg)',50)],'Dry volume = Wet volume × Factor; Ingredient volume = Dry volume × Ingredient parts / Total parts',v=>{const total=v.cement+v.sand+v.gravel,dry=v.volume*v.dry,cement=dry*v.cement/total;return[r('Estimated cement mass (kg)',cement*v.density),r('Estimated cement bags',Math.ceil(cement*v.density/v.bag),'number'),r('Estimated sand volume (m³)',dry*v.sand/total),r('Estimated gravel volume (m³)',dry*v.gravel/total)];},633.6,{aliases:['cement calculator','sand calculator','gravel calculator'],note:constructionNote+' Nominal bulk-volume model only, not structural mix design. Dry factor, mix ratios and bulk density are user assumptions and must match supplier specifications.'}),
  tool('flooring','Flooring',C,'Estimate floor material area and material-only cost with waste.',[n('length','Room length (m)',5),n('width','Room width (m)',4),n('waste','Wastage (%)',10),n('price','Material price (₹ per m²)',500)],'Required area = Length × Width × (1 + Waste/100); Cost = Required area × Unit price',v=>{const area=v.length*v.width*(1+v.waste/100);return[r('Estimated material cost',area*v.price,'money'),r('Estimated purchase area (m²)',area)];},11000,{note:constructionNote+' Excludes labor, underlay and package-size rounding.'}),
  tool('roofing','Roofing',C,'Estimate material area for a constant-pitch roof from its horizontal footprint.',[n('length','Horizontal footprint length (m)',10),n('width','Horizontal footprint width (m)',5),n('pitch','Roof angle (degrees)',30,0,{max:89}),n('waste','Wastage (%)',10)],'Sloped area = Horizontal area / cos(pitch); Required area = Sloped area × (1 + Waste/100)',v=>[r('Estimated roofing area (m²)',v.length*v.width/Math.cos(v.pitch*Math.PI/180)*(1+v.waste/100))],63.508529611,{note:constructionNote+' Assumes all roof sections have the same pitch; overhangs must be included in the footprint.'}),
  tool('wallpaper','Wallpaper',C,'Estimate whole wallpaper rolls from vertical strips and usable roll length.',[n('width','Combined wall width / perimeter (m)',10),p('height','Wall height (m)',2.5),p('rollWidth','Roll width (m)',.5),p('rollLength','Roll length (m)',10),n('pattern','Extra length per strip for pattern/cuts (m)',0)],'Strips = ceil(Wall width/Roll width); Strips per roll = floor(Roll length/(Height+Allowance)); Rolls = ceil(Strips/Strips per roll)',v=>{const perRoll=Math.floor(v.rollLength/(v.height+v.pattern));check(perRoll>0,'Roll length must accommodate at least one complete strip.');return[r('Estimated rolls',Math.ceil(Math.ceil(v.width/v.rollWidth)/perRoll),'number')];},5,{note:constructionNote+' Does not deduct windows or doors; pattern allowance is per strip and supplied by you.'}),
  tool('stairs','Stair',C,'Plan equal risers and a simple straight stair run.',[p('rise','Total rise (m)',3),p('maxRiser','Chosen maximum riser height (m)',.18),p('tread','Chosen tread depth (m)',.28)],'Risers = ceil(Total rise / Max riser); Actual riser = Rise / Risers; Run = (Risers−1) × Tread',v=>{const risers=Math.ceil(v.rise/v.maxRiser);return[r('Estimated riser count',risers,'number'),r('Equal riser height (m)',v.rise/risers),r('Straight run (m)',Math.max(0,risers-1)*v.tread)];},17,{note:constructionNote+' Geometry only; local building codes, landings, headroom, handrails and structural design are not evaluated.'}),
  tool('fence','Fence',C,'Estimate posts and span count for one straight fence section.',[n('length','Fence length (m)',20),p('spacing','Maximum post spacing (m)',2)],'Spans = ceil(Length / Maximum spacing); Posts = Spans + 1 for a nonzero straight fence',v=>{const spans=Math.ceil(v.length/v.spacing);return[r('Estimated posts',v.length===0?0:spans+1,'number'),r('Spans',spans,'number')];},11,{note:constructionNote+' Straight run with an end post at each end; gates, corners and post foundations are excluded.'}),
  tool('water-tank','Water Tank Volume',C,'Calculate internal cylindrical tank capacity from radius and water depth.',[n('radius','Internal radius (m)',1),n('height','Water depth (m)',2)],'Capacity (L) = π × Radius² × Depth × 1000',v=>[r('Estimated capacity (L)',Math.PI*v.radius**2*v.height*1000)],6283.18530718,{note:constructionNote+' Internal dimensions; tank wall thickness and freeboard are not included.'}),
  tool('earth-material','Excavation / Soil / Mulch',C,'Estimate bulk volume and mass for a rectangular layer or excavation.',[n('length','Length (m)',5),n('width','Width (m)',4),n('depth','Depth (cm)',10),n('waste','Additional volume allowance (%)',10),n('density','Assumed material bulk density (kg/m³)',1500)],'Volume = Length × Width × Depth/100 × (1 + Allowance/100); Mass = Volume × Density',v=>{const volume=v.length*v.width*v.depth/100*(1+v.waste/100);return[r('Estimated volume (m³)',volume),r('Estimated mass (kg)',volume*v.density)];},2.2,{aliases:['excavation volume','soil','mulch','asphalt'],note:constructionNote+' Uses your bulk-density assumption; compaction, moisture, bulking and loose-vs-compacted density must be checked with the supplier.'})
];
