import {tool,n,s,r,requireCondition as check} from './shared.js';
export const converterSets={
  pressure:{name:'Pressure',units:[['Pa','Pascals',1],['kPa','Kilopascals',1000],['bar','Bar',100000],['atm','Standard atmospheres',101325],['psi','PSI',6894.757293168]],from:'bar',to:'kPa',expected:100},
  energy:{name:'Energy',units:[['J','Joules',1],['kJ','Kilojoules',1000],['kWh','Kilowatt-hours',3600000],['cal','Thermochemical calories',4.184],['kcal','Kilocalories',4184]],from:'kWh',to:'J',expected:3600000},
  power:{name:'Power',units:[['W','Watts',1],['kW','Kilowatts',1000],['MW','Megawatts',1000000],['hp','Mechanical horsepower',745.6998715822702]],from:'kW',to:'W',expected:1000},
  force:{name:'Force',units:[['N','Newtons',1],['kN','Kilonewtons',1000],['lbf','Pound-force',4.4482216152605],['kgf','Kilogram-force',9.80665]],from:'kN',to:'N',expected:1000},
  torque:{name:'Torque',units:[['N·m','Newton-meters',1],['lbf·ft','Pound-force feet',1.3558179483314],['lbf·in','Pound-force inches',.11298482902762]],from:'lbf·ft',to:'N·m',expected:1.3558179483314},
  angle:{name:'Angle',units:[['deg','Degrees',Math.PI/180],['rad','Radians',1],['grad','Gradians',Math.PI/200],['turn','Turns',2*Math.PI]],from:'turn',to:'deg',expected:360,signed:true},
  frequency:{name:'Frequency',units:[['Hz','Hertz',1],['kHz','Kilohertz',1000],['MHz','Megahertz',1000000],['GHz','Gigahertz',1000000000],['rpm','Cycles per minute',1/60]],from:'kHz',to:'Hz',expected:1000},
  density:{name:'Density',units:[['kg/m³','Kilograms per cubic meter',1],['g/cm³','Grams per cubic centimeter',1000],['lb/ft³','Pounds per cubic foot',16.01846337396]],from:'g/cm³',to:'kg/m³',expected:1000},
  acceleration:{name:'Acceleration',units:[['m/s²','Meters per second squared',1],['ft/s²','Feet per second squared',.3048],['g','Standard gravity',9.80665]],from:'g',to:'m/s²',expected:9.80665,signed:true},
  cooking:{name:'Cooking Measurement',units:[['mL','Milliliters',1],['L','Liters',1000],['tsp','US teaspoons',4.92892159375],['tbsp','US tablespoons',14.78676478125],['cup','US customary cups',236.5882365]],from:'cup',to:'mL',expected:236.5882365},
  time:{name:'Time Unit',units:[['s','Seconds',1],['min','Minutes',60],['h','Hours',3600],['d','24-hour days',86400],['wk','7-day weeks',604800]],from:'h',to:'min',expected:60},
  transfer:{name:'Digital Transfer Rate',units:[['bps','Bits per second',1],['kbps','Kilobits per second',1000],['Mbps','Megabits per second',1000000],['Gbps','Gigabits per second',1000000000],['MB/s','Megabytes per second',8000000]],from:'MB/s',to:'Mbps',expected:8}
};
export function factorConvert(set,value,from,to){const fromUnit=set.units.find(u=>u[0]===from),toUnit=set.units.find(u=>u[0]===to);check(fromUnit&&toUnit,'Select supported units.');return value*fromUnit[2]/toUnit[2];}
export const converterTools=Object.entries(converterSets).map(([id,set])=>tool(`${id}-units`,`${set.name} Converter`,'Converters',`Convert ${set.name.toLowerCase()} using the selected unit definitions.`,[n('value','Value',1,set.signed?null:0),s('from','From',set.units.map(([id,label])=>[id,label]),set.from),s('to','To',set.units.map(([id,label])=>[id,label]),set.to)],'Result = Value × Source factor / Destination factor',v=>[r(`Converted value (${v.to})`,factorConvert(set,v.value,v.from,v.to))],set.expected,{note:id==='cooking'?'US customary volume units. This is a volume-to-volume conversion, not a volume-to-weight conversion; ingredient density is not inferred.':id==='transfer'?'Decimal prefixes are used. One byte = 8 bits; MB/s and Mbps are different units.':id==='power'?'Horsepower is mechanical horsepower (745.699871582 W), not metric PS.':'Uses the definitions shown in the unit labels; time days are fixed 24-hour durations.',aliases:id==='power'?['kw to hp','hp to kw']:id==='time'?['hours calculator','minutes calculator','seconds calculator']:[]}));
converterTools.push(tool('fuel-economy','Fuel Economy Converter','Converters','Convert economy or consumption with explicit US/imperial gallon definitions.',[n('value','Positive economy / consumption',10,0,{exclusiveMin:true}),s('from','From',[['kmL','Kilometers per liter'],['L100','Liters per 100 km'],['mpgUS','US miles per gallon'],['mpgUK','Imperial miles per gallon']],'kmL'),s('to','To',[['kmL','Kilometers per liter'],['L100','Liters per 100 km'],['mpgUS','US miles per gallon'],['mpgUK','Imperial miles per gallon']],'L100')],'km/L = 100/(L/100km); US mpg = km/L × 2.352145833; imperial mpg = km/L × 2.824809363',v=>{const factors={kmL:1,mpgUS:3.785411784/1.609344,mpgUK:4.54609/1.609344};const k=v.from==='L100'?100/v.value:v.value/factors[v.from];return[r(`Converted economy (${v.to})`,v.to==='L100'?100/k:k*factors[v.to])];},10,{aliases:['fuel consumption'],note:'Consumption and economy are reciprocals; a zero value cannot be converted reciprocally.'}));
