import {tool,n,i,d,s,r,txt,requireCondition as check} from './shared.js';
import {utcDate,offsetDate,isoWeek} from '../utils/dates.js';
import {workingDays} from './extended.js';
const D='Date & Time';
export const dateTools=[
  tool('add-days','Add / Subtract Days',D,'Move a calendar date forward or backward by a signed day count.',[d('date','Starting date'),i('offset','Days to add (negative to subtract)',30,-1000000,1000000)],'Result date = Starting date + Signed calendar-day offset',v=>[txt('Resulting date',offsetDate(v.date,v.offset))],'2026-01-31',{aliases:['add days to date','subtract days from date']}),
  tool('add-months','Add Months to Date',D,'Add a signed number of calendar months while preserving month-end validity.',[d('date','Starting date','2026-01-31'),i('offset','Months to add',1,-100000,100000)],'Add months, then clamp original day to last valid day of resulting month',v=>[txt('Resulting date',offsetDate(v.date,0,v.offset))],'2026-02-28'),
  tool('add-years','Add Years to Date',D,'Add calendar years, clamping leap-day anniversaries to February 28.',[d('date','Starting date','2024-02-29'),i('offset','Years to add',1,-9999,9999)],'Add years; clamp day to the resulting month length',v=>[txt('Resulting date',offsetDate(v.date,0,0,v.offset))],'2025-02-28',{aliases:['anniversary']}),
  tool('weekend-days','Weekend Days',D,'Count Saturdays and Sundays in an inclusive date range.',[d('start','Start date','2026-01-01'),d('end','End date','2026-01-07')],'Weekend days = Inclusive calendar days − Monday-to-Friday working days',v=>{const result=workingDays(v.start,v.end);return[r('Weekend days',result.calendar-result.work,'number')];},2),
  tool('week-number','Week Number',D,'Find the ISO week number and ISO week-year of a date.',[d('date','Date','2026-01-01')],'ISO weeks begin Monday; week 1 contains January 4 (the first Thursday)',v=>{const result=isoWeek(v.date);return[r('ISO week number',result.week,'number'),r('ISO week-year',result.year,'number')];},1),
  tool('leap-year','Leap Year',D,'Check the Gregorian leap-year rule.',[i('year','Calendar year',2024,1,9999)],'Leap if divisible by 4, except centuries must be divisible by 400',v=>[txt('Leap year?',v.year%4===0&&(v.year%100!==0||v.year%400===0)?'Yes':'No')],'Yes'),
  tool('time-arithmetic','Time Addition / Subtraction',D,'Add or subtract durations entered as hours and minutes.',[i('h1','First duration hours',2),i('m1','First duration minutes',30,0,59),i('h2','Second duration hours',1),i('m2','Second duration minutes',45,0,59),s('op','Operation',[['add','Add'],['subtract','Subtract']],'add')],'Total minutes = First duration minutes ± Second duration minutes',v=>{const total=v.h1*60+v.m1+(v.op==='add'?1:-1)*(v.h2*60+v.m2);return[r('Signed total minutes',total,'number'),txt('Duration',`${total<0?'-':''}${Math.floor(Math.abs(total)/60)}h ${Math.abs(total)%60}m`)];},255),
  tool('decimal-hours','Decimal Hours',D,'Convert decimal hours into hours, minutes and seconds.',[n('hours','Decimal hours',1.5)],'Total seconds = round(Decimal hours × 3600); split into h, m, s',v=>{const seconds=Math.round(v.hours*3600);return[txt('Clock-style duration',`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`),r('Total minutes',v.hours*60)];},'1h 30m 0s',{aliases:['hours to decimal'],note:'Converts duration rather than a clock time; seconds round to the nearest whole second. For the reverse conversion use Time Duration or Time Unit Converter.'})
];
