import {make,n,p,i,s,r,txt,check,gcd} from './advanced-shared.js';
const T=make('Digital');
export const digitalTools=[
 T('uptime','Website Uptime / Downtime','Convert monitored downtime into availability or calculate downtime from uptime.',[p('total','Monitoring interval (minutes)',1000),n('down','Downtime (minutes; availability mode)',10),n('percent','Uptime (%) (downtime mode)',99,0,{max:100}),s('solve','Solve for',[['uptime','Uptime percentage'],['downtime','Downtime minutes']],'uptime')],'Uptime=100×(Total−Downtime)/Total; Downtime=Total×(1−Uptime/100)',v=>{check(v.solve!=='uptime'||v.down<=v.total,'Downtime cannot exceed the monitoring interval.');return[r(v.solve==='uptime'?'Uptime (%)':'Downtime (minutes)',v.solve==='uptime'?(v.total-v.down)/v.total*100:v.total*(1-v.percent/100))];},99,{aliases:['website uptime percentage','website downtime'],note:'One monitoring interval; no SLA exclusion windows or compensation calculation.'}),
 T('website-bandwidth','Website Bandwidth Usage','Estimate transfer volume and average bandwidth from traffic and page payload.',[n('visits','Visits per day',1000),n('pages','Pages per visit',3),n('size','Transferred payload per page (MB)',2),i('days','Period days',30,1)],'Transferred MB=Visits/day×Pages/visit×MB/page×Days; Average Mbps=Total MB×8/(Days×86400)',v=>{const mb=v.visits*v.pages*v.size*v.days;return[r('Estimated transfer (decimal GB)',mb/1000),r('Average bandwidth (Mbps)',mb*8/(v.days*86400))];},180,{aliases:['website bandwidth usage','bandwidth'],note:'Decimal units, no caching/compression savings; average bandwidth is not peak capacity.'}),
 T('media-size','Streaming / Audio / Video Data Usage','Estimate encoded media size from constant bitrate and duration.',[n('rate','Total encoded bitrate (Mbps)',5),n('minutes','Duration (minutes)',60)],'Size (MB)=Bitrate(Mbps)×Seconds/8',v=>[r('Estimated media size (decimal MB)',v.rate*v.minutes*60/8),r('Estimated media size (decimal GB)',v.rate*v.minutes*60/8000)],2250,{aliases:['data usage','streaming data usage','video file size','audio file size','bitrate'],note:'Total bitrate includes all audio/video streams; excludes container and network overhead. Actual variable-bitrate files differ.'}),
 T('image-size','Image Uncompressed Size','Estimate raw raster payload before headers, alignment or compression.',[i('width','Image width (pixels)',1920,1,100000),i('height','Image height (pixels)',1080,1,100000),i('channels','Color channels (3 RGB, 4 RGBA)',3,1,16),i('depth','Bits per channel',8,1,64)],'Bytes=ceil(Width×Height×Channels×Bits/channel/8)',v=>[r('Raw payload (bytes)',Math.ceil(v.width*v.height*v.channels*v.depth/8)),r('Raw payload (decimal MB)',Math.ceil(v.width*v.height*v.channels*v.depth/8)/1e6)],6220800,{aliases:['image uncompressed size'],note:'Tightly packed raw samples, no row padding, metadata, palettes or compression.'}),
 T('ppi','Screen Resolution / PPI','Measure display pixel density from raster dimensions and diagonal size.',[i('width','Horizontal pixels',1920,1,100000),i('height','Vertical pixels',1080,1,100000),p('diagonal','Display diagonal (inches)',24)],'PPI=√(Width²+Height²)/Diagonal inches',v=>{const g=Number(gcd(BigInt(v.width),BigInt(v.height)));return[r('Pixels per inch',Math.hypot(v.width,v.height)/v.diagonal),r('Total pixels',v.width*v.height),txt('Aspect ratio',`${v.width/g}:${v.height/g}`)];},91.7877987534,{aliases:['screen resolution'],note:'Physical pixel density; OS scaling and marketing DPI labels do not alter the hardware pixel count.'}),
 T('print-dpi','Print DPI','Calculate print sampling density from pixels and physical print width.',[i('pixels','Image width (pixels)',3000,1,1000000),p('width','Printed width',10),s('unit','Printed width unit',[['in','Inches'],['cm','Centimeters']],'in')],'Image sampling PPI=Pixels/Printed inches',v=>[r('Required image pixels per printed inch',v.pixels/(v.unit==='cm'?v.width/2.54:v.width))],300,{aliases:['DPI'],note:'Image sampling density, often called DPI; printer ink-dot resolution is a separate hardware specification.'})
];
