import {make,n,p,i,r,s,check} from './advanced-shared.js';
import {m} from './shared.js';
const T=make('Ecommerce');
export const ecommerceTools=[
 T('product-profit','Product Profit / Pricing','Calculate unit profit after configurable fees and fulfillment, or solve a target-margin price.',[n('price','Selling price per unit (₹)',200),n('cost','Product cost per unit (₹)',100),n('shipping','Shipping/fulfillment cost per unit (₹)',20),n('fixed','Fixed transaction fee per unit (₹)',5),n('fee','Variable fee (%)',10,0,{max:100}),n('margin','Target profit margin (%) (pricing mode)',20,0,{max:100}),s('solve','Calculate',[['profit','Profit at entered price'],['price','Price for target margin']],'profit')],'Profit=Price×(1−Fee%)−Cost−Shipping−Fixed fee; Target price=(Cost+Shipping+Fixed)/(1−Fee%−Margin%)',v=>{check(v.solve!=='price'||v.fee+v.margin<100,'Fee plus target margin must be less than 100%.');const price=v.solve==='price'?(v.cost+v.shipping+v.fixed)/(1-(v.fee+v.margin)/100):v.price,profit=price*(1-v.fee/100)-v.cost-v.shipping-v.fixed;const result=[m(v.solve==='price'?'Required selling price':'Unit net profit',v.solve==='price'?price:profit),m('Total variable/fixed fees',price*v.fee/100+v.fixed),m('Unit net profit',profit)];if(price>0)result.push(r('Profit margin (%)',profit/price*100));return result;},55,{aliases:['product pricing','ecommerce profit margin'],note:'Fees are user-entered, not current marketplace schedules. Excludes tax, advertising, returns and overhead unless incorporated into the cost fields.'}),
 T('transaction-fee','Marketplace / Payment Gateway Fee','Estimate a variable plus fixed payment fee and net proceeds.',[n('amount','Transaction amount (₹)',1000),n('percent','Entered fee (%)',2,0,{max:100}),n('fixed','Entered fixed fee (₹)',5),i('count','Number of transactions',1,1)],'Fees=Amount×Percentage/100+Fixed×Transaction count',v=>{const fee=v.amount*v.percent/100+v.fixed*v.count;return[m('Total entered fees',fee),m('Net proceeds',v.amount-fee)];},25,{aliases:['marketplace fee','payment gateway fee','transaction fee'],note:'Percentage applies to total gross amount; fixed fee applies once per transaction. User supplies every fee; taxes on fees and refund policies are excluded.'}),
 T('customer-lifetime','Customer Lifetime Value','Estimate gross contribution across an assumed customer lifetime.',[n('order','Average order value (₹)',1000),n('frequency','Orders per year',4),n('years','Expected relationship years',3),n('margin','Contribution margin (%)',20,0,{max:100}),n('acquisition','Acquisition cost per customer (₹)',500)],'CLV=Average order×Annual frequency×Years×Margin−Acquisition cost',v=>[m('Estimated net lifetime contribution',v.order*v.frequency*v.years*v.margin/100-v.acquisition)],1900,{aliases:['customer lifetime value'],note:'Simple undiscounted fixed-lifetime model; frequency, margin and lifetime are assumptions, not customer-level forecasts.'}),
 T('inventory-planning','Inventory Reorder Point / Safety Stock','Plan safety stock and reorder point for a fixed supplier lead time.',[n('demand','Mean daily demand (units/day)',100),n('sd','Daily demand standard deviation (units/day)',10),p('lead','Fixed lead time (days)',5),n('z','Chosen normal service factor',1.65)],'Safety stock=z×Daily SD×√Lead days; Reorder point=Mean daily demand×Lead days+Safety stock',v=>{const ss=v.z*v.sd*Math.sqrt(v.lead);return[r('Estimated safety stock (units)',ss),r('Estimated reorder point (units)',v.demand*v.lead+ss)];},36.8951216287,{aliases:['inventory reorder point','safety stock'],note:'Independent identically distributed daily demand, fixed lead time and normal approximation. No supplier variability, seasonality or order batching.'})
];
