import {tool,n,p,t,s,r,divide,requireCondition as check} from './shared.js';
import {numberList} from './extended.js';
const E='Electrical';
const note='Ideal low-voltage/DC model unless stated otherwise. Component tolerance, temperature, AC power factor and wiring losses are not inferred.';
export const electricalTools=[
  tool('ohms-law',"Ohm's Law",E,'Solve voltage, current or resistance in an ideal DC circuit.',[s('solve','Solve for',[['voltage','Voltage'],['current','Current'],['resistance','Resistance']],'voltage'),n('voltage','Voltage (V)',12),n('current','Current (A)',2),p('resistance','Resistance (Ω)',6)],'V = I×R; I = V/R; R = V/I',v=>[r(v.solve==='voltage'?'Voltage (V)':v.solve==='current'?'Current (A)':'Resistance (Ω)',v.solve==='voltage'?v.current*v.resistance:v.solve==='current'?v.voltage/v.resistance:divide(v.voltage,v.current))],12,{note,aliases:['voltage calculator','current calculator','resistance calculator','ohm']}),
  tool('electrical-power','Electrical Power',E,'Calculate DC electrical power from voltage and current.',[n('voltage','Voltage (V)',12),n('current','Current (A)',2)],'DC power = Voltage × Current',v=>[r('Electrical power (W)',v.voltage*v.current)],24,{note}),
  tool('electrical-energy','Electrical Energy',E,'Calculate consumed energy from constant wattage and runtime.',[n('power','Power (W)',1000),n('hours','Operating duration (hours)',2)],'Energy (kWh) = Power (W) × Hours / 1000',v=>[r('Energy (kWh)',v.power*v.hours/1000),r('Energy (J)',v.power*v.hours*3600)],2,{aliases:['kwh calculator'],note}),
  tool('electricity-cost','Electricity Cost',E,'Estimate a device’s energy cost using your tariff.',[n('power','Device power (W)',1000),n('hours','Hours used',2),n('tariff','Tariff (₹ per kWh)',8)],'Cost = Power(W) × Hours / 1000 × Tariff',v=>[r('Estimated electricity cost (₹)',v.power*v.hours/1000*v.tariff,'money')],16,{note:'Single constant energy tariff supplied by you; no slabs, taxes, demand charges or minimum bills.'}),
  tool('battery-runtime','Battery Runtime',E,'Estimate runtime from nominal energy and usable efficiency.',[n('capacity','Battery capacity (Ah)',10),p('voltage','Nominal voltage (V)',12),p('load','Load power (W)',24),n('efficiency','Usable energy (%)',80,0,{max:100})],'Runtime (h) = Ah × V × Usable fraction / Load watts',v=>[r('Estimated runtime (hours)',v.capacity*v.voltage*v.efficiency/100/v.load)],4,{note:'Ideal constant-load estimate. Usable percentage is your assumption; discharge rate, cutoff voltage, aging and temperature can change runtime.'}),
  tool('battery-capacity','Battery Capacity',E,'Estimate amp-hour capacity required for a planned runtime.',[n('load','Load power (W)',24),n('hours','Target runtime (hours)',4),p('voltage','Battery voltage (V)',12),p('efficiency','Usable energy (%)',80,{max:100})],'Required Ah = Load × Hours / (Voltage × Usable fraction)',v=>[r('Estimated required capacity (Ah)',v.load*v.hours/(v.voltage*v.efficiency/100))],10,{note:'Sizing estimate only; does not choose chemistry, protection, wiring or safe charge settings.'}),
  tool('battery-energy','Battery Energy',E,'Convert battery amp-hours and watt-hours at a nominal voltage.',[n('capacity','Capacity (Ah)',10),n('voltage','Nominal voltage (V)',12),n('energy','Energy (Wh; inverse mode)',120),s('solve','Convert to',[['energy','Wh from Ah'],['capacity','Ah from Wh']],'energy')],'Energy(Wh)=Capacity(Ah)×Voltage; Capacity(Ah)=Energy(Wh)/Voltage',v=>{if(v.solve==='capacity'){check(v.voltage>0,'Nominal voltage must be positive for Wh-to-Ah conversion.');return[r('Nominal capacity (Ah)',v.energy/v.voltage)];}return[r('Nominal energy (Wh)',v.capacity*v.voltage),r('Nominal energy (kWh)',v.capacity*v.voltage/1000)];},120,{note}),
  tool('voltage-divider','Voltage Divider',E,'Find unloaded output voltage of a two-resistor divider.',[n('voltage','Input voltage (V)',12),n('r1','Top resistor R1 (Ω)',1000),n('r2','Bottom resistor R2 (Ω)',1000)],'Vout = Vin × R2 / (R1 + R2)',v=>[r('Unloaded output voltage (V)',divide(v.voltage*v.r2,v.r1+v.r2))],6,{note:'Assumes no load across R2; loaded dividers require a parallel-load calculation.'}),
  tool('led-resistor','LED Resistor',E,'Estimate a series resistor and dissipation for a low-voltage LED.',[p('supply','Supply voltage (V)',5),n('forward','LED forward voltage (V)',2),p('current','Desired LED current (mA)',20)],'Resistance = (Supply − Forward voltage)/(Current/1000); Dissipation = Voltage drop × Current',v=>{check(v.supply>v.forward,'Supply voltage must exceed LED forward voltage.');return[r('Calculated series resistance (Ω)',(v.supply-v.forward)/(v.current/1000)),r('Resistor dissipation (W)',(v.supply-v.forward)*v.current/1000)];},150,{note:'Low-voltage ideal estimate; choose a suitable standard resistor and power-rating margin from component specifications.'}),
  tool('resistor-network','Resistors in Series / Parallel',E,'Combine positive resistances for either connection topology.',[t('values','Resistances (Ω, comma separated)','100, 100'),s('mode','Connection',[['series','Series'],['parallel','Parallel']],'series')],'Series R = Sum(R); Parallel R = 1 / Sum(1/R)',v=>{const a=numberList(v.values);check(a.every(x=>x>0),'Every resistor must have a positive resistance.');return[r('Equivalent resistance (Ω)',v.mode==='series'?a.reduce((a,b)=>a+b,0):1/a.reduce((s,x)=>s+1/x,0))];},200,{note,aliases:['resistors in series','resistors in parallel']}),
  tool('capacitor-network','Capacitors in Series / Parallel',E,'Combine positive capacitances under an ideal model.',[t('values','Capacitances (µF, comma separated)','100, 100'),s('mode','Connection',[['series','Series'],['parallel','Parallel']],'series')],'Series C = 1 / Sum(1/C); Parallel C = Sum(C)',v=>{const a=numberList(v.values);check(a.every(x=>x>0),'Every capacitor must have a positive capacitance.');return[r('Equivalent capacitance (µF)',v.mode==='parallel'?a.reduce((a,b)=>a+b,0):1/a.reduce((s,x)=>s+1/x,0))];},50,{note,aliases:['capacitors in series','capacitors in parallel']})
];
