import {make,n,p,i,s,r,check} from './advanced-shared.js';
const T=make('Engineering'),note='Ideal mechanical model with SI inputs. Estimated outputs are not structural, machinery or hydraulic design certification.';
export const engineeringTools=[
 T('rotational-power','Torque / RPM / Horsepower','Solve shaft power, torque or rotation speed for steady mechanical transmission.',[n('torque','Shaft torque (N·m)',100),n('rpm','Rotation speed (rpm)',3000),n('power','Shaft power (W)',31415.9265359),s('solve','Solve for',[['power','Power'],['torque','Torque'],['rpm','RPM']],'power')],'Power(W)=Torque(N·m)×RPM×2π/60; Mechanical hp=Power/745.699871582',v=>{const power=v.solve==='power'?v.torque*v.rpm*2*Math.PI/60:v.power;let value=power,label='Shaft power (W)';if(v.solve==='torque'){check(v.rpm>0,'RPM must be positive to solve torque.');value=v.power*60/(v.rpm*2*Math.PI);label='Shaft torque (N·m)';}if(v.solve==='rpm'){check(v.torque>0,'Torque must be positive to solve RPM.');value=v.power*60/(v.torque*2*Math.PI);label='Rotation speed (rpm)';}return[r(label,value),r('Shaft power (mechanical hp)',power/745.699871582)];},31415.9265359,{aliases:['horsepower','torque to horsepower','horsepower to torque','RPM'],note:note+' Mechanical horsepower convention; enter power in watts when solving torque or RPM.'}),
 T('gear-pulley','Gear / Pulley Ratio and Speed','Calculate an ideal gear-pair or belt-pulley speed ratio from teeth or diameters.',[p('driver','Driver teeth / diameter (same units)',20),p('driven','Driven teeth / diameter (same units)',40),n('rpm','Driver speed (rpm)',1000)],'Driven RPM=Driver RPM×Driver size/Driven size; Reduction ratio=Driven/Driver',v=>[r('Driven speed (rpm)',v.rpm*v.driver/v.driven),r('Reduction ratio',v.driven/v.driver)],500,{aliases:['gear ratio','gear speed','pulley ratio'],note:note+' No belt slip; an external gear pair reverses rotation direction. Teeth counts should be whole numbers; pulley diameters use the same units.'}),
 T('mechanical-efficiency','Mechanical Efficiency','Compare useful mechanical output with supplied input energy or power.',[p('input','Input energy/power (same units)',100),n('output','Useful output energy/power',80)],'Efficiency (%)=Useful output/Input×100',v=>{check(v.output<=v.input,'Useful output cannot exceed input for this efficiency model.');return[r('Mechanical efficiency (%)',v.output/v.input*100),r('Loss (input units)',v.input-v.output)];},80,{note}),
 T('friction','Friction','Estimate Coulomb friction from a selected coefficient and normal force.',[n('coefficient','Friction coefficient',.3),n('normal','Normal force (N)',100)],'Friction=μ×Normal force',v=>[r('Friction / limiting friction (N)',v.coefficient*v.normal)],30,{note:note+' Use kinetic coefficient for sliding friction; static coefficient gives maximum available static friction, not necessarily the actual force.'}),
 T('centripetal','Centripetal / Centrifugal Force','Calculate radial force magnitude for uniform circular motion.',[n('mass','Mass (kg)',2),n('speed','Tangential speed (m/s)',3),p('radius','Rotation radius (m)',1)],'Radial force=mv²/r',v=>[r('Radial force magnitude (N)',v.mass*v.speed**2/v.radius)],18,{aliases:['centripetal force','centrifugal force'],note:note+' Centripetal force points inward in an inertial frame; centrifugal force refers to the outward fictitious force in a rotating frame.'}),
 T('angular-motion','Angular Velocity / Linear Velocity','Convert rotation speed into angular velocity and tangential linear speed.',[n('rpm','Rotation speed (rpm)',60,null),n('radius','Radius (m)',2)],'ω=RPM×2π/60; Tangential velocity=ωr',v=>[r('Angular velocity (rad/s)',v.rpm*2*Math.PI/60),r('Tangential linear velocity (m/s)',v.rpm*2*Math.PI/60*v.radius)],2*Math.PI,{aliases:['angular velocity','linear velocity'],note}),
 T('angular-acceleration','Angular Acceleration','Calculate average angular acceleration over an elapsed time.',[n('initial','Initial angular velocity (rad/s)',0,null),n('final','Final angular velocity (rad/s)',10,null),p('time','Elapsed time (s)',2)],'α=(ωfinal−ωinitial)/Time',v=>[r('Average angular acceleration (rad/s²)',(v.final-v.initial)/v.time)],5,{note}),
 T('flow-rate','Volumetric / Mass Flow Rate','Calculate pipe flow from cross-section, mean velocity and fluid density.',[p('diameter','Internal pipe diameter (m)',.1),n('velocity','Mean axial velocity (m/s)',2),p('density','Fluid density (kg/m³)',1000)],'Volume flow=πd²v/4; Mass flow=Density×Volume flow',v=>{const q=Math.PI*v.diameter**2/4*v.velocity;return[r('Volumetric flow (m³/s)',q),r('Mass flow (kg/s)',q*v.density),r('Volumetric flow (L/min)',q*60000)];},.005*Math.PI,{aliases:['mass flow rate','volumetric flow rate','flow rate'],note:note+' Full circular pipe and mean velocity; no pressure-loss or turbulent-profile prediction.'}),
 T('hydraulic-cylinder','Hydraulic Cylinder Force / Pressure','Solve ideal hydraulic force or pressure using bore and optional rod diameter.',[p('bore','Cylinder bore diameter (m)',.1),n('rod','Rod diameter (m; 0 for cap side)',0),n('pressure','Applied gauge pressure (Pa)',1000000),n('force','Axial force (N; pressure mode)',7853.981633974),s('solve','Solve for',[['force','Force'],['pressure','Pressure']],'force')],'Effective area=π(Bore²−Rod²)/4; Force=Gauge pressure×Area',v=>{check(v.rod<v.bore,'Rod diameter must be smaller than bore diameter.');const a=Math.PI*(v.bore**2-v.rod**2)/4;return[r(v.solve==='force'?'Ideal cylinder force (N)':'Required gauge pressure (Pa)',v.solve==='force'?v.pressure*a:v.force/a),r('Effective piston area (m²)',a)];},2500*Math.PI,{aliases:['hydraulic pressure','hydraulic force','hydraulic cylinder force'],note:note+' Gauge differential pressure; friction and pressure on the opposite piston side are excluded. Rod diameter applies to the annular rod side.'})
];
