import {tool,n,p,i,s,r,m,requireCondition as check} from './shared.js';
export const travelTools=[
  tool('fuel-cost','Fuel Cost','Travel','Estimate fuel needed and its cost for a journey.',[n('distance','Journey distance (km)',100),p('economy','Economy (km/L)',20),n('price','Fuel price (₹/L)',100)],'Fuel = Distance / km-per-liter; Cost = Fuel × Price',v=>[m('Estimated fuel cost',v.distance/v.economy*v.price),r('Estimated fuel required (L)',v.distance/v.economy),m('Fuel cost per kilometer',v.price/v.economy),m('Fuel cost per mile',v.price/v.economy*1.609344)],500,{aliases:['fuel required'],note:'Assumes constant fuel economy and price; idling and detours are excluded.'}),
  tool('mileage','Mileage / Fuel Efficiency','Travel','Calculate measured fuel economy from distance and fuel used.',[n('distance','Distance traveled (km)',100),p('fuel','Fuel consumed (L)',5)],'Economy (km/L) = Distance / Fuel; Consumption = Fuel / Distance × 100',v=>{check(v.distance>0,'Distance must be positive to calculate reciprocal consumption.');return[r('Fuel economy (km/L)',v.distance/v.fuel),r('Consumption (L/100km)',v.fuel/v.distance*100)];},20,{aliases:['fuel efficiency']}),
  tool('trip-cost','Trip Cost','Travel','Combine fuel, tolls, parking and other journey expenses.',[n('distance','Distance (km)',100),p('economy','Fuel economy (km/L)',20),n('fuelPrice','Fuel price (₹/L)',100),n('tolls','Tolls (₹)',100),n('parking','Parking (₹)',50),n('other','Other costs (₹)',0),i('people','People sharing',2,1)],'Trip total = Distance/Economy × Fuel price + Tolls + Parking + Other costs',v=>{const total=v.distance/v.economy*v.fuelPrice+v.tolls+v.parking+v.other;return[m('Estimated total trip cost',total),m('Cost per person',total/v.people)];},650),
  tool('distance-cost','Cost Per Kilometer / Mile','Travel','Allocate total travel costs over distance in kilometers or miles.',[n('cost','Total journey cost (₹)',1000),p('distance','Journey distance',100),s('unit','Distance unit',[['km','Kilometers'],['mi','Miles']],'km')],'Unit distance cost = Total cost / Distance',v=>[m(`Cost per ${v.unit}`,v.cost/v.distance)],10,{aliases:['cost per kilometer','cost per mile']})
];
export const everydayTools=[
  tool('tip-split','Tip / Split Bill','Everyday','Calculate a tip and split the total equally among a group.',[n('bill','Bill subtotal (₹)',1000),n('tip','Tip (%)',10),i('people','Number of people',2,1)],'Tip = Bill × Tip/100; Per person = (Bill + Tip) / People',v=>[m('Amount per person',v.bill*(1+v.tip/100)/v.people),m('Tip amount',v.bill*v.tip/100),m('Total bill with tip',v.bill*(1+v.tip/100))],550,{aliases:['tip calculator','split bill']}),
  tool('recipe-scaling','Recipe Scaling','Everyday','Scale an ingredient quantity to a different serving count.',[p('original','Original servings',4),n('target','Target servings',6),n('quantity','Original ingredient quantity (same unit)',100)],'Scaled quantity = Ingredient quantity × Target servings / Original servings',v=>[r('Scaled quantity (original unit)',v.quantity*v.target/v.original),r('Scaling factor',v.target/v.original)],150,{note:'Applies proportional scaling; cooking time and temperature are not automatically scaled.'}),
  tool('transfer-time','Data Transfer Time','Everyday','Estimate ideal transfer duration or derive average transfer speed from size and elapsed time.',[n('size','File size (decimal MB)',100),p('speed','Transfer speed (Mbps)',10),p('seconds','Elapsed time (s; speed mode)',80),s('solve','Solve for',[['time','Transfer time'],['speed','Average transfer speed']],'time')],'Seconds=Size(MB)×8/Speed(Mbps); Speed(Mbps)=Size(MB)×8/Seconds',v=>v.solve==='speed'?[r('Average transfer speed (Mbps)',v.size*8/v.seconds)]:[r('Estimated transfer time (s)',v.size*8/v.speed),r('Estimated minutes',v.size*8/v.speed/60)],80,{aliases:['download time','upload time'],note:'Decimal MB and megabits/second; assumes sustained line speed with no protocol overhead, congestion or compression.'})
];
