import { tool,n,p,i,s,r,m,txt,divide,requireCondition as check,financeNote } from './shared.js';
import { emi } from './logic.js';

const rate=()=>n('rate','Annual assumed rate (%)',10);
const years=()=>p('years','Duration (years)',5);
export function growth(rate,years){return Math.exp(years*Math.log1p(rate/100));}
export function paymentFactor(rate,months,due=false){const q=rate/1200;return q?Math.expm1(months*Math.log1p(q))/q*(due?1+q:1):months;}
export function solveMonths(principal,rate,payment){const q=rate/1200;check(payment>principal*q,'Monthly payment must exceed the first month’s interest.');return q?-Math.log1p(-principal*q/payment)/Math.log1p(q):principal/payment;}
export function loanSchedule(principal,rate,payment,extra=0){let balance=principal,totalInterest=0,months=0;const q=rate/1200;check(payment+extra>balance*q,'Payment must exceed monthly interest.');while(balance>1e-8&&months<12000){const interest=balance*q;const paid=Math.min(payment+extra,balance+interest);balance=Math.max(0,balance+interest-paid);totalInterest+=interest;months++;}check(months<12000,'Repayment exceeds 1,000 years. Increase the payment.');return {months,interest:totalInterest,total:principal+totalInterest};}
export const financeTools=[
  tool('swp','SWP','Finance','Estimate a corpus after fixed monthly withdrawals.',[n('principal','Starting corpus (₹)',100000),n('withdrawal','Monthly withdrawal (₹)',1000),rate(),i('months','Withdrawal months',12,1)],'Balance each month = max(0, Previous balance × (1 + rate/1200) − Withdrawal)',v=>{let balance=v.principal,paid=0;for(let k=0;k<v.months;k++){balance*=1+v.rate/1200;const amount=Math.min(balance,v.withdrawal);balance-=amount;paid+=amount;}return[m('Estimated remaining corpus',balance),m('Actual modeled withdrawals',paid)];},97905.738651174,{note:financeNote+' Withdrawals occur at month end and stop at depletion; no borrowing.'}),
  tool('cagr','CAGR','Finance','Find the constant annual growth rate between two positive values.',[p('start','Starting value (₹)',100),p('end','Ending value (₹)',200),p('years','Years',2)],'CAGR (%) = ((Ending / Starting)^(1/years) − 1) × 100',v=>[r('CAGR (%)',(Math.pow(v.end/v.start,1/v.years)-1)*100)],41.421356237),
  tool('roi','ROI','Finance','Measure investment gain relative to the original cost.',[p('cost','Investment cost (₹)',1000),n('value','Final proceeds (₹)',1200),n('income','Additional income (₹)',100)],'ROI (%) = (Proceeds + Income − Cost) / Cost × 100',v=>[r('Return on investment (%)',(v.value+v.income-v.cost)/v.cost*100),m('Net gain',v.value+v.income-v.cost)],30,{aliases:['investment return']}),
  tool('inflation','Inflation','Finance','Estimate the future cost of an item as prices rise.',[n('cost','Current cost (₹)',10000),n('rate','Annual inflation (%)',5),years()],'Future cost = Current cost × (1 + inflation/100)^years',v=>[m('Estimated future cost',v.cost*growth(v.rate,v.years)),m('Purchasing power of current sum',v.cost/growth(v.rate,v.years))],12762.815625,{note:financeNote}),
  tool('future-value','Future Value','Finance','Combine a starting balance with recurring end-of-month contributions.',[n('principal','Starting balance (₹)',1000),n('payment','Monthly contribution (₹)',100),n('rate','Annual rate (%)',0),i('months','Months',12,1)],'FV = Principal × (1 + r)^months + Payment × ((1 + r)^months − 1)/r',v=>[m('Estimated future value',v.principal*(1+v.rate/1200)**v.months+v.payment*paymentFactor(v.rate,v.months))],2200,{note:financeNote}),
  tool('present-value','Present Value','Finance','Discount a future amount to its value today.',[n('future','Future amount (₹)',12100),n('rate','Annual discount rate (%)',10),p('years','Years',2)],'PV = Future amount / (1 + rate/100)^years',v=>[m('Present value',v.future/growth(v.rate,v.years))],10000),
  tool('rule-72','Rule of 72','Finance','Approximate how long an investment takes to double.',[p('rate','Annual return (%)',8)],'Approximate doubling years = 72 / Annual return (%)',v=>[r('Estimated years to double',72/v.rate)],9,{note:'A rough rule of thumb, most useful for moderate positive rates. See Doubling Time for exact annual-compounding math.'}),
  tool('doubling-time','Doubling Time','Finance','Find exact doubling or other target growth time under annual compounding.',[p('rate','Annual growth rate (%)',10),p('multiple','Target value multiple (2 doubles, 3 triples)',2)],'Growth years = ln(Target multiple) / ln(1 + rate/100)',v=>{check((v.multiple??2)>1,'Target multiple must exceed 1.');return[r((v.multiple??2)===2?'Years to double':`Years to grow ${v.multiple} times`,Math.log(v.multiple??2)/Math.log1p(v.rate/100))];},7.272540897),
  tool('goal-investment','Goal Investment','Finance','Find a monthly saving amount needed for a future goal.',[n('goal','Target amount (₹)',12000),n('principal','Starting savings (₹)',0),n('rate','Annual return (%)',0),i('months','Months to goal',12,1)],'Monthly contribution = max(0, Goal − Starting balance × (1+r)^months) / Annuity factor',v=>[m('Estimated monthly contribution',Math.max(0,v.goal-v.principal*(1+v.rate/1200)**v.months)/paymentFactor(v.rate,v.months))],1000,{note:financeNote+' Contributions at month end.',aliases:['monthly investment required','savings goal']}),
  tool('retirement-corpus','Retirement Corpus','Finance','Estimate a retirement fund from spending and a chosen withdrawal assumption.',[n('expense','Current monthly spending (₹)',30000),n('inflation','Annual inflation (%)',5),n('years','Years until retirement',20),p('withdraw','Assumed annual withdrawal rate (%)',4)],'Corpus = Monthly expense × 12 × (1 + inflation/100)^years / (withdrawal rate/100)',v=>[m('Estimated required corpus',v.expense*12*growth(v.inflation,v.years)/(v.withdraw/100))],23879679.346,{note:financeNote+' Withdrawal rate is your planning assumption, not a safe-return guarantee.',aliases:['retirement']}),
  tool('emergency-fund','Emergency Fund','Finance','Build a reserve target from expenses and desired coverage.',[n('expense','Essential monthly expenses (₹)',25000),p('months','Months of coverage',6),n('saved','Current reserve (₹)',50000)],'Target = Monthly essentials × Coverage months; Shortfall = max(0, Target − Reserve)',v=>[m('Reserve target',v.expense*v.months),m('Remaining to save',Math.max(0,v.expense*v.months-v.saved))],150000),
  tool('annuity','Annuity','Finance','Value a fixed series of end-of-period payments today.',[n('payment','Annual payment (₹)',1000),n('rate','Annual discount rate (%)',10),i('years','Number of annual payments',2,1)],'PV = Payment × (1 − (1 + r)^−n) / r',v=>[m('Present value of annuity',v.rate?v.payment*(-Math.expm1(-v.years*Math.log1p(v.rate/100)))/(v.rate/100):v.payment*v.years)],1735.537190083),
  tool('annuity-payout','Annuity Payout','Finance','Estimate equal annual withdrawals from a fixed starting fund.',[n('principal','Starting fund (₹)',10000),n('rate','Annual return (%)',0),i('years','Payout years',10,1)],'Payment = Principal × r / (1 − (1 + r)^−n)',v=>[m('Estimated annual payout',v.rate?v.principal*(v.rate/100)/(-Math.expm1(-v.years*Math.log1p(v.rate/100))):v.principal/v.years)],1000,{note:financeNote+' Payouts occur at year end and deplete the fund after the selected duration.'}),
  tool('dividend-yield','Dividend Yield','Finance','Compare annual dividends per share with the share price.',[n('dividend','Annual dividend per share (₹)',5),p('price','Share price (₹)',100)],'Dividend yield (%) = Annual dividend per share / Share price × 100',v=>[r('Dividend yield (%)',v.dividend/v.price*100)],5),
  tool('dividend','Dividend','Finance','Estimate cash dividends for the shares you hold.',[n('shares','Shares held',200),n('dividend','Dividend per share (₹)',5)],'Dividend income = Shares × Dividend per share',v=>[m('Estimated dividend income',v.shares*v.dividend)],1000,{note:'Assumes the entered per-share dividend applies to all shares; excludes withholding and taxes.'}),
  tool('stock-average','Stock Average','Finance','Compute the weighted average cost of two share purchases.',[p('a','First purchase shares',10),n('pa','First share price (₹)',100),p('b','Second purchase shares',20),n('pb','Second share price (₹)',130)],'Average cost = (Shares1 × Price1 + Shares2 × Price2) / Total shares',v=>[m('Average price per share',(v.a*v.pa+v.b*v.pb)/(v.a+v.b)),r('Total shares',v.a+v.b)],120,{aliases:['average share price']}),
  tool('stock-profit','Stock Profit/Loss','Finance','Calculate a trade’s gain after entry and exit fees.',[p('shares','Shares traded',10),n('buy','Buy price per share (₹)',100),n('sell','Sell price per share (₹)',120),n('fees','Total transaction fees (₹)',20)],'Net profit = Shares × (Sell price − Buy price) − Fees',v=>[m('Net trade profit / loss',v.shares*(v.sell-v.buy)-v.fees)],180,{note:'Fees are supplied by you; capital gains tax and corporate actions are excluded.'}),
  tool('risk-reward','Risk/Reward Ratio','Finance','Compare a long position’s target gain to its stop-loss risk.',[p('entry','Entry price',100),n('stop','Stop-loss price',90),p('target','Target price',120)],'Reward / Risk = (Target − Entry) / (Entry − Stop)',v=>{check(v.stop<v.entry&&v.target>v.entry,'For a long trade, stop must be below entry and target above entry.');return[r('Reward per unit of risk',(v.target-v.entry)/(v.entry-v.stop))];},2,{note:'Long-position scenario only; stop orders do not guarantee an execution price.'}),
  tool('bond-yield','Bond Yield','Finance','Calculate current yield from coupon income and bond price.',[n('coupon','Annual coupon income (₹)',60),p('price','Current bond price (₹)',1000)],'Current yield (%) = Annual coupon / Current price × 100',v=>[r('Current yield (%)',v.coupon/v.price*100)],6,{note:'Current yield only, not yield to maturity; ignores redemption gain/loss, taxes and default risk.'}),
  tool('effective-rate','Effective Interest Rate','Finance','Convert a nominal annual rate to an effective annual yield.',[n('rate','Nominal annual rate (%)',12),i('frequency','Compounding periods per year',12,1)],'Effective annual rate (%) = ((1 + nominal/(100×n))^n − 1) × 100',v=>[r('Effective annual rate (%)',Math.expm1(v.frequency*Math.log1p(v.rate/(100*v.frequency)))*100)],12.682503013,{aliases:['APY']}),
  tool('apr','APR','Finance','Estimate an effective annual borrowing cost including an upfront fee.',[p('principal','Face loan amount (₹)',10000),n('fee','Upfront fee (₹)',0),n('rate','Nominal annual interest (%)',12),i('months','Monthly payments',12,1)],'Solve net proceeds = sum(Payment / (1 + monthly IRR)^k); Effective APR = (1 + IRR)^12 − 1',v=>{check(v.fee<v.principal,'Upfront fee must be less than the loan amount.');const pay=emi(v.principal,v.rate,v.months).monthly;let lo=0,hi=1;const pv=q=>pay*(-Math.expm1(-v.months*Math.log1p(q)))/q;while(pv(hi)>v.principal-v.fee&&hi<1e6)hi*=2;for(let k=0;k<100;k++){const mid=(lo+hi)/2;if(pv(mid)>v.principal-v.fee)lo=mid;else hi=mid;}return[r('Estimated effective annual APR (%)',Math.expm1(12*Math.log1p((lo+hi)/2))*100)];},12.682503013,{note:'Effective annual IRR estimate with monthly repayments and one upfront fee, not a jurisdiction-specific statutory APR disclosure.'})
];

const loanFields=()=>[p('principal','Loan balance (₹)',12000),n('rate','Annual interest (%)',0),p('payment','Monthly payment (₹)',1000)];
export const loanTools=[
  tool('loan-eligibility','Loan Eligibility','Loans','Estimate principal supported by your payment budget.',[n('income','Monthly net income (₹)',50000),n('ratio','Chosen income allocation (%)',40,0,{max:100}),n('existing','Existing monthly debt payments (₹)',5000),n('rate','Annual interest (%)',0),i('months','Loan months',12,1)],'Payment budget = max(0, Income × Allocation − Existing debt); Principal = Budget × PV annuity factor',v=>{const budget=Math.max(0,v.income*v.ratio/100-v.existing);const q=v.rate/1200;return[m('Estimated supported loan amount',q?budget*(-Math.expm1(-v.months*Math.log1p(q)))/q:budget*v.months),m('Monthly payment budget',budget)];},180000,{note:'Planning estimate using your allocation assumption, not lender approval.',aliases:['loan affordability']}),
  tool('loan-comparison','Loan Comparison','Loans','Compare monthly payments and total interest on two offers.',[p('principal','Loan amount (₹)',12000),n('a','Offer A annual interest (%)',0),i('na','Offer A months',12,1),n('b','Offer B annual interest (%)',0),i('nb','Offer B months',24,1)],'Apply EMI formula independently to both offers; compare monthly payment and total interest',v=>{const a=emi(v.principal,v.a,v.na),b=emi(v.principal,v.b,v.nb);return[m('Offer A monthly EMI',a.monthly),m('Offer B monthly EMI',b.monthly),m('Offer A total interest',a.interest),m('Offer B total interest',b.interest)];},1000),
  tool('loan-prepayment','Loan Prepayment','Loans','Estimate repayment time and interest saved with extra monthly payments.',[...loanFields(),n('extra','Extra monthly payment (₹)',500)],'Simulate monthly interest and payments until balance reaches zero',v=>{const base=loanSchedule(v.principal,v.rate,v.payment),extra=loanSchedule(v.principal,v.rate,v.payment,v.extra);return[r('Estimated months after prepayment',extra.months,'number'),r('Months saved',base.months-extra.months,'number'),m('Interest saved',base.interest-extra.interest),m('Interest after prepayment',extra.interest)];},8,{note:'Monthly extras start immediately; excludes prepayment penalties and bank-specific rounding.'}),
  tool('loan-tenure','Loan Tenure','Loans','Solve how many monthly payments your loan needs.',loanFields(),'Months = −ln(1 − Principal × r / Payment) / ln(1 + r)',v=>[r('Estimated months (rounded up)',Math.ceil(solveMonths(v.principal,v.rate,v.payment)),'number')],12),
  tool('loan-rate','Interest Rate','Loans','Solve a nominal annual loan rate from payment and tenure.',[p('principal','Loan amount (₹)',12000),p('payment','Monthly payment (₹)',1000),i('months','Monthly payments',12,1)],'Numerically solve EMI(Principal, annual rate, months) = Payment',v=>{check(v.payment>=v.principal/v.months,'Payment cannot be below the zero-interest repayment for this tenure.');let lo=0,hi=1200;check(emi(v.principal,hi,v.months).monthly>=v.payment,'Implied rate exceeds the supported 1,200% annual range.');for(let k=0;k<100;k++){const mid=(lo+hi)/2;if(emi(v.principal,mid,v.months).monthly<v.payment)lo=mid;else hi=mid;}return[r('Implied annual interest (%)',(lo+hi)/2)];},0),
  tool('loan-principal','Principal','Loans','Find the loan principal corresponding to an EMI.',[n('payment','Monthly EMI (₹)',1000),n('rate','Annual interest (%)',0),i('months','Monthly payments',12,1)],'Principal = EMI × (1 − (1+r)^−months) / r',v=>[m('Supported principal',v.rate?v.payment*(-Math.expm1(-v.months*Math.log1p(v.rate/1200)))/(v.rate/1200):v.payment*v.months)],12000),
  tool('credit-card-interest','Credit Card Interest','Loans','Estimate simple daily interest on a constant revolving balance.',[n('balance','Average daily balance (₹)',10000),n('rate','Annual interest (%)',36),i('days','Interest days',30)],'Interest = Average daily balance × Annual rate / 100 × Days / 365',v=>[m('Estimated interest',v.balance*v.rate/100*v.days/365)],295.890410959,{note:'Uses a 365-day simple-interest convention. Actual statements depend on daily transactions, grace periods, compounding and issuer rules.'}),
  tool('debt-income','Debt-to-Income Ratio','Loans','Measure monthly debt payments relative to gross income.',[n('debt','Monthly debt payments (₹)',10000),p('income','Gross monthly income (₹)',50000)],'DTI (%) = Monthly debt payments / Gross monthly income × 100',v=>[r('Debt-to-income ratio (%)',v.debt/v.income*100)],20),
  tool('debt-repayment','Debt Repayment','Loans','Estimate a constant-payment debt payoff schedule.',loanFields(),'Balance next month = Balance × (1 + rate/1200) − Payment',v=>{const result=loanSchedule(v.principal,v.rate,v.payment);return[r('Estimated repayment months',result.months,'number'),m('Total interest',result.interest),m('Total repayment',result.total)];},12)
];
