import {tool,p,i,r,requireCondition as check} from './shared.js';
const G='Geometry';
const dim=(name,label,value)=>p(name,`${label} (m)`,value);
const area=(value)=>r('Area (m²)',value);
const perimeter=value=>r('Perimeter (m)',value);
const volume=value=>r('Volume (m³)',value);
const surface=value=>r('Surface area (m²)',value);
export const geometryTools=[
  tool('circle','Circle',G,'Calculate area, diameter and circumference from a radius.',[dim('radius','Radius',1)],'Area = πr²; Circumference = 2πr; Diameter = 2r',v=>[area(Math.PI*v.radius*v.radius),r('Circumference (m)',2*Math.PI*v.radius),r('Diameter (m)',2*v.radius)],Math.PI),
  tool('triangle','Triangle',G,'Calculate area and perimeter from three side lengths.',[dim('a','Side a',3),dim('b','Side b',4),dim('c','Side c',5)],'s = (a+b+c)/2; Area = sqrt(s(s−a)(s−b)(s−c))',v=>{check(v.a+v.b>v.c&&v.a+v.c>v.b&&v.b+v.c>v.a,'The sides must satisfy the triangle inequality.');const s=(v.a+v.b+v.c)/2;return[area(Math.sqrt(s*(s-v.a)*(s-v.b)*(s-v.c))),perimeter(2*s)];},6),
  tool('right-triangle','Right Triangle',G,'Solve a right triangle from its two perpendicular legs.',[dim('a','First leg',3),dim('b','Second leg',4)],'Hypotenuse = sqrt(a²+b²); Area = ab/2',v=>{const hyp=Math.hypot(v.a,v.b);return[r('Hypotenuse (m)',hyp),area(v.a*v.b/2),perimeter(v.a+v.b+hyp),r('Angle opposite first leg (degrees)',Math.atan2(v.a,v.b)*180/Math.PI)];},5,{aliases:['Pythagorean theorem']}),
  tool('rectangle','Rectangle',G,'Find rectangular area, perimeter and diagonal.',[dim('length','Length',3),dim('width','Width',4)],'Area = lw; Perimeter = 2(l+w); Diagonal = sqrt(l²+w²)',v=>[area(v.length*v.width),perimeter(2*(v.length+v.width)),r('Diagonal (m)',Math.hypot(v.length,v.width))],12),
  tool('square','Square',G,'Calculate area, perimeter and diagonal for a square.',[dim('side','Side',2)],'Area = s²; Perimeter = 4s; Diagonal = s√2',v=>[area(v.side**2),perimeter(4*v.side),r('Diagonal (m)',v.side*Math.SQRT2)],4),
  tool('parallelogram','Parallelogram',G,'Find area and perimeter from base, side and perpendicular height.',[dim('base','Base',5),dim('side','Adjacent side',3),dim('height','Perpendicular height',2)],'Area = Base × Height; Perimeter = 2(Base + Side)',v=>{check(v.height<=v.side,'Height cannot exceed the adjacent side.');return[area(v.base*v.height),perimeter(2*(v.base+v.side))];},10),
  tool('trapezoid','Trapezoid',G,'Calculate area between parallel sides from height.',[dim('a','First parallel side',3),dim('b','Second parallel side',5),dim('height','Perpendicular height',2)],'Area = (a+b) × Height / 2',v=>[area((v.a+v.b)*v.height/2)],8),
  tool('rhombus','Rhombus',G,'Calculate area and perimeter from perpendicular diagonals.',[dim('a','First diagonal',6),dim('b','Second diagonal',8)],'Area = d₁d₂/2; Side = sqrt((d₁/2)²+(d₂/2)²)',v=>[area(v.a*v.b/2),perimeter(4*Math.hypot(v.a/2,v.b/2))],24),
  tool('ellipse','Ellipse',G,'Find elliptical area and an approximate perimeter from semi-axes.',[dim('a','First semi-axis',2),dim('b','Second semi-axis',1)],'Area = πab; Ramanujan perimeter ≈ π(a+b)[1+3h/(10+√(4−3h))], h=((a−b)/(a+b))²',v=>{const h=((v.a-v.b)/(v.a+v.b))**2;return[area(Math.PI*v.a*v.b),r('Approximate perimeter (m)',Math.PI*(v.a+v.b)*(1+3*h/(10+Math.sqrt(4-3*h))))];},2*Math.PI,{note:'Enter semi-axis lengths, not full diameters. Area is exact; perimeter uses Ramanujan’s approximation.'}),
  tool('regular-polygon','Regular Polygon',G,'Calculate area and perimeter for equal-sided regular polygons.',[i('sides','Number of sides',4,3,10000),dim('side','Side length',2)],'Area = n×s² / (4tan(π/n)); Perimeter = n×s',v=>[area(v.sides*v.side**2/(4*Math.tan(Math.PI/v.sides))),perimeter(v.sides*v.side)],4),
  tool('sector','Sector',G,'Find a circular sector’s area, arc length and boundary length.',[dim('radius','Radius',2),p('angle','Central angle (degrees)',90,{max:360})],'Area = θ/360 × πr²; Arc = θ/360 × 2πr',v=>[area(v.angle/360*Math.PI*v.radius**2),r('Arc length (m)',v.angle/360*2*Math.PI*v.radius),perimeter(v.angle/360*2*Math.PI*v.radius+2*v.radius)],Math.PI,{aliases:['arc length']}),
  tool('cylinder','Cylinder',G,'Calculate volume and closed surface area of a cylinder.',[dim('radius','Radius',1),dim('height','Height',2)],'Volume = πr²h; Closed surface = 2πr(r+h)',v=>[volume(Math.PI*v.radius**2*v.height),surface(2*Math.PI*v.radius*(v.radius+v.height))],2*Math.PI),
  tool('cone','Cone',G,'Calculate volume and closed surface area of a right circular cone.',[dim('radius','Radius',3),dim('height','Height',4)],'Volume = πr²h/3; Surface = πr(r + sqrt(r²+h²))',v=>[volume(Math.PI*v.radius**2*v.height/3),surface(Math.PI*v.radius*(v.radius+Math.hypot(v.radius,v.height)))],12*Math.PI),
  tool('sphere','Sphere',G,'Calculate spherical volume and surface area.',[dim('radius','Radius',1)],'Volume = 4πr³/3; Surface = 4πr²',v=>[volume(4*Math.PI*v.radius**3/3),surface(4*Math.PI*v.radius**2)],4*Math.PI/3),
  tool('cube','Cube',G,'Find volume, surface area and space diagonal of a cube.',[dim('side','Side length',2)],'Volume = s³; Surface = 6s²; Diagonal = s√3',v=>[volume(v.side**3),surface(6*v.side**2),r('Space diagonal (m)',v.side*Math.sqrt(3))],8),
  tool('cuboid','Cuboid / Rectangular Prism',G,'Calculate a rectangular prism’s volume and closed surface.',[dim('length','Length',2),dim('width','Width',3),dim('height','Height',4)],'Volume = lwh; Surface = 2(lw+lh+wh)',v=>[volume(v.length*v.width*v.height),surface(2*(v.length*v.width+v.length*v.height+v.width*v.height))],24),
  tool('pyramid','Pyramid',G,'Calculate volume and surface of a right square pyramid.',[dim('side','Square base side',6),dim('height','Vertical height',4)],'Volume = s²h/3; Surface = s² + 2s√(h²+(s/2)²)',v=>[volume(v.side**2*v.height/3),surface(v.side**2+2*v.side*Math.hypot(v.height,v.side/2))],48,{note:'Assumes a square base and an apex directly above its center.'})
];
