import {tool,n,p,i,s,r,txt,requireCondition as check,healthNote} from './shared.js';
const H='Health';
export const healthTools=[
  tool('body-fat','Body Fat',H,'Estimate adult body-fat percentage from BMI, age and the Deurenberg regression.',[p('weight','Weight (kg)',70),p('height','Height (cm)',175),i('age','Age (years)',30,18,83),s('sex','Sex in the original formula',[['male','Male'],['female','Female']],'male')],'Body fat (%) = 1.20×BMI + 0.23×Age − 10.8×Sex − 5.4; Sex=1 male, 0 female',v=>{const bmi=v.weight/(v.height/100)**2;check(bmi>=13.9&&bmi<=40.9,'BMI is outside the reported study range (13.9–40.9); this model is not applied.');const fat=1.2*bmi+.23*v.age-(v.sex==='male'?10.8:0)-5.4;check(fat>=0&&fat<=100,'Inputs give an implausible estimate; check values.');return[r('Estimated body fat (%)',fat),r('BMI',bmi)];},18.128571429,{note:healthNote+' Population regression, not a direct body-composition measurement; can overestimate for people with obesity or substantial muscle mass.',source:{title:'Deurenberg et al. (1991), original study',url:'https://pubmed.ncbi.nlm.nih.gov/2043597/'}}),
  tool('lean-body-mass','Lean Body Mass',H,'Estimate non-fat mass using a supplied body-fat percentage.',[p('weight','Body weight (kg)',70),n('fat','Known / assumed body fat (%)',20,0,{max:100})],'Lean mass = Body weight × (1 − Body fat/100)',v=>[r('Estimated lean body mass (kg)',v.weight*(1-v.fat/100)),r('Estimated fat mass (kg)',v.weight*v.fat/100)],56,{note:healthNote+' Accuracy depends on the body-fat estimate you enter.'}),
  tool('waist-height','Waist-to-Height Ratio',H,'Compare waist circumference and height in matching metric units.',[n('waist','Waist circumference (cm)',80),p('height','Height (cm)',175)],'Ratio = Waist circumference / Height',v=>[r('Waist-to-height ratio',v.waist/v.height)],80/175,{note:healthNote+' Reports the ratio without diagnosing risk or applying a clinical cutoff.'}),
  tool('calorie-budget','Calorie Deficit / Surplus',H,'Adjust an existing maintenance estimate by a chosen daily calorie amount.',[p('maintenance','Maintenance estimate (kcal/day)',2000),n('adjustment','Chosen adjustment (kcal/day)',250),s('mode','Adjustment',[['deficit','Subtract (deficit)'],['surplus','Add (surplus)']],'deficit')],'Target = Maintenance calories ± User-chosen adjustment',v=>{const target=v.maintenance+(v.mode==='surplus'?1:-1)*v.adjustment;check(target>0,'The chosen adjustment must leave a positive calorie target.');return[r('Arithmetic calorie target (kcal/day)',target)];},1750,{note:healthNote+' Does not recommend a deficit/surplus or predict weight changes.',aliases:['calorie deficit','calorie surplus']}),
  tool('protein','Protein Intake',H,'Calculate a protein quantity from a target grams-per-kilogram assumption.',[p('weight','Body weight (kg)',70),n('factor','Your chosen target (g/kg/day)',1)],'Protein target (g/day) = Weight × Chosen g/kg/day',v=>[r('Calculated protein target (g/day)',v.weight*v.factor)],70,{note:healthNote+' The factor is a user-selected planning input, not a dietary prescription.'}),
  tool('water','Water Intake',H,'Convert a chosen milliliters-per-kilogram assumption to a daily volume.',[p('weight','Body weight (kg)',70),n('factor','Your chosen factor (mL/kg/day)',30)],'Volume (L/day) = Weight × Chosen factor / 1000',v=>[r('Calculated volume (L/day)',v.weight*v.factor/1000)],2.1,{note:healthNote+' The factor is not a universal recommendation; climate, activity, diet and medical restrictions are not modeled.'}),
  tool('macros','Macro',H,'Allocate a supplied calorie target to chosen macronutrient percentages.',[n('calories','Daily energy target (kcal)',2000),n('protein','Protein share (%)',20,0,{max:100}),n('carbs','Carbohydrate share (%)',50,0,{max:100}),n('fat','Fat share (%)',30,0,{max:100})],'Protein and carbohydrate grams = kcal share / 4; Fat grams = kcal share / 9',v=>{check(Math.abs(v.protein+v.carbs+v.fat-100)<1e-8,'Protein, carbohydrate and fat shares must total 100%.');return[r('Protein (g/day)',v.calories*v.protein/400),r('Carbohydrate (g/day)',v.calories*v.carbs/400),r('Fat (g/day)',v.calories*v.fat/900)];},100,{note:healthNote+' Uses conventional 4/4/9 kcal per gram; does not recommend macro proportions.'}),
  tool('running-pace','Running / Walking Pace',H,'Calculate pace and speed from distance and elapsed duration.',[p('distance','Distance',5),s('unit','Distance unit',[['km','Kilometers'],['mi','Miles']],'km'),p('minutes','Elapsed minutes',30)],'Pace (min/km) = Minutes / Distance(km); Speed(km/h) = Distance / (Minutes/60)',v=>{const km=v.distance*(v.unit==='mi'?1.609344:1);const pace=v.minutes/km;return[r('Pace (min/km)',pace),r('Pace (min/mile)',pace*1.609344),r('Speed (km/h)',km*60/v.minutes)];},6,{aliases:['running pace','walking pace','pace converter'],note:healthNote+' Constant average pace; excludes stops, elevation and exertion.'}),
  tool('steps-distance','Steps / Distance',H,'Convert distance and step count using your own step length.',[s('mode','Convert',[['distance','Steps to distance'],['steps','Distance to steps']],'distance'),n('steps','Step count (ignored when solving steps)',1000),n('distance','Distance (km; ignored when solving distance)',.7),p('length','Step length (cm, not two-step stride)',70)],'Distance(km) = Steps × Step length(cm) / 100000',v=>[r(v.mode==='distance'?'Estimated distance (km)':'Estimated steps',v.mode==='distance'?v.steps*v.length/100000:v.distance*100000/v.length)],.7,{aliases:['steps to distance','distance to steps'],note:healthNote+' Step length is supplied by you and assumed constant.'})
];
