import {tool,n,p,i,t,s,r,txt,divide,requireCondition as check} from './shared.js';
import { numberList,gcdBig } from './extended.js';
const list=()=>t('numbers','Numbers separated by commas','1, 2, 3, 4');
export function statistics(text,sample=false){const values=numberList(text),count=values.length;check(!sample||count>1,'Sample variance needs at least two values.');const mean=values.reduce((a,b)=>a+b,0)/count;const variance=values.reduce((a,b)=>a+(b-mean)**2,0)/(count-(sample?1:0));return {values,count,mean,variance};}
export function factorial(n){let value=1n;for(let k=2n;k<=BigInt(n);k++)value*=k;return value;}
export function prime(n){if(n<2)return false;if(n%2===0)return n===2;for(let k=3;k*k<=n;k+=2)if(n%k===0)return false;return true;}
export function exactFraction(text,percent=false){check(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(text),'Use ordinary decimal notation, not exponents.');check(text.replace(/[^0-9]/g,'').length<=100,'Use at most 100 decimal digits.');const digits=(text.split('.')[1]||'').length;let den=10n**BigInt(digits)*(percent?100n:1n);let a=BigInt(text.replace('.','').replace(/^\+/,''));const g=gcdBig(a,den);a/=g;den/=g;return den===1n?String(a):`${a}/${den}`;}
const M='Math';
const varianceFields=()=>[list(),s('kind','Dataset type',[['population','Population'],['sample','Sample']],'population')];
export const mathTools=[
  tool('median','Median',M,'Find the middle of a sorted numerical dataset.',[list()],'Sort numbers; median is middle value or average of the two middle values',v=>{const a=numberList(v.numbers).sort((a,b)=>a-b),k=Math.floor(a.length/2);return[r('Median',a.length%2?a[k]:(a[k-1]+a[k])/2)];},2.5),
  tool('mode','Mode',M,'Find values that occur most frequently.',[t('numbers','Numbers separated by commas','1, 2, 2, 3')],'Mode = value(s) with the largest frequency; no mode if all appear once',v=>{const counts=new Map();numberList(v.numbers).forEach(n=>counts.set(n,(counts.get(n)||0)+1));const max=Math.max(...counts.values());return[txt('Mode',max===1?'No repeated values':[...counts].filter(([,count])=>count===max).map(([n])=>n).sort((a,b)=>a-b).join(', ')),r('Maximum frequency',max,'number')];},'2'),
  tool('weighted-average','Weighted Average',M,'Compute a mean where each value has a different weight.',[t('numbers','Values','10, 20'),t('weights','Matching weights','1, 3')],'Weighted average = Sum(Value × Weight) / Sum(Weights)',v=>{const a=numberList(v.numbers),w=numberList(v.weights);check(a.length===w.length,'Provide one weight for each value.');check(w.every(x=>x>=0),'Weights must be nonnegative.');return[r('Weighted average',divide(a.reduce((sum,x,k)=>sum+x*w[k],0),w.reduce((a,b)=>a+b,0)))];},17.5),
  tool('geometric-mean','Geometric Mean',M,'Find the multiplicative center of positive values.',[t('numbers','Positive values','2, 8')],'Geometric mean = exp(Sum(ln(value))/Count)',v=>{const a=numberList(v.numbers);check(a.every(x=>x>0),'Geometric mean requires positive values.');return[r('Geometric mean',Math.exp(a.reduce((s,x)=>s+Math.log(x),0)/a.length))];},4),
  tool('harmonic-mean','Harmonic Mean',M,'Find the reciprocal-based mean of positive values.',[t('numbers','Positive values','2, 6')],'Harmonic mean = Count / Sum(1/value)',v=>{const a=numberList(v.numbers);check(a.every(x=>x>0),'Harmonic mean requires positive values.');return[r('Harmonic mean',a.length/a.reduce((s,x)=>s+1/x,0))];},3),
  tool('range','Range',M,'Measure the span from the smallest to largest observation.',[list()],'Range = Maximum − Minimum',v=>{const a=numberList(v.numbers),min=Math.min(...a),max=Math.max(...a);return[r('Range',max-min),r('Minimum',min),r('Maximum',max)];},3),
  tool('variance','Variance',M,'Measure the average squared deviation from the mean.',varianceFields(),'Variance = Sum((x − mean)²) / N; use N−1 for a sample',v=>[r('Variance',statistics(v.numbers,v.kind==='sample').variance)],1.25),
  tool('standard-deviation','Standard Deviation',M,'Express dataset dispersion in its original units.',varianceFields(),'Standard deviation = sqrt(Variance)',v=>[r('Standard deviation',Math.sqrt(statistics(v.numbers,v.kind==='sample').variance))],1.118033989),
  tool('factorial','Factorial',M,'Compute the exact product of all integers from 1 to n.',[i('value','Nonnegative integer n',5,0,1000)],'n! = 1 × 2 × … × n; 0! = 1',v=>[txt('Factorial',String(factorial(v.value)))],'120'),
  tool('prime-checker','Prime Number Checker',M,'Check whether an integer has exactly two positive divisors.',[i('value','Integer',97,0,1000000000000)],'Test divisibility through sqrt(n); integers below 2 are not prime',v=>[txt('Prime check',prime(v.value)?'Prime':'Not prime')],'Prime'),
  tool('prime-factorization','Prime Factorization',M,'Decompose an integer into a product of prime factors.',[i('value','Integer to factor',60,2,1000000000000)],'Repeatedly divide by each prime factor through sqrt(remaining value)',v=>{let x=v.value;const factors=[];for(let k=2;k*k<=x;k+=(k===2?1:2)){while(x%k===0){factors.push(k);x/=k;}}if(x>1)factors.push(x);return[txt('Prime factors',factors.join(' × '))];},'2 × 2 × 3 × 5'),
  tool('modulo','Remainder & Modulo',M,'Compare truncating remainder with a nonnegative modulo.',[n('a','Dividend',-7,null),p('b','Positive divisor',3)],'Remainder = a % b; Nonnegative modulo = ((a % b) + b) % b',v=>[r('Nonnegative modulo',((v.a%v.b)+v.b)%v.b),r('Truncating remainder',v.a%v.b)],2,{aliases:['remainder']}),
  tool('nth-root','nth Root',M,'Compute a real nth root, including odd roots of negative values.',[n('value','Radicand',27,null),i('degree','Root degree',3,1,1000)],'Root = sign(x) × |x|^(1/n) for odd n; x^(1/n) for nonnegative x',v=>{check(v.value>=0||v.degree%2===1,'A negative number has no real even root.');return[r('Real root',Math.sign(v.value)*Math.abs(v.value)**(1/v.degree))];},3,{aliases:['cube root']}),
  tool('permutation','Permutation',M,'Count ordered choices of r items from n without replacement.',[i('n','Available items n',5,0,1000),i('k','Chosen items r',2,0,1000)],'P(n,r) = n! / (n−r)!',v=>{check(v.k<=v.n,'Chosen items cannot exceed available items.');return[txt('Ordered arrangements',String(factorial(v.n)/factorial(v.n-v.k)))];},'20'),
  tool('combination','Combination',M,'Count unordered selections without replacement.',[i('n','Available items n',5,0,1000),i('k','Chosen items r',2,0,1000)],'C(n,r) = n! / (r! × (n−r)!)',v=>{check(v.k<=v.n,'Chosen items cannot exceed available items.');return[txt('Unordered combinations',String(factorial(v.n)/(factorial(v.k)*factorial(v.n-v.k))))];},'10'),
  tool('probability','Probability',M,'Compute probability for equally likely outcomes.',[n('favorable','Favorable outcomes',3),p('total','Total equally likely outcomes',6)],'Probability = Favorable outcomes / Total outcomes',v=>{check(v.favorable<=v.total,'Favorable outcomes cannot exceed total outcomes.');return[r('Probability',v.favorable/v.total),r('Probability (%)',v.favorable/v.total*100)];},.5),
  tool('random-number','Random Number',M,'Generate an integer within an inclusive range.',[i('min','Minimum integer',1,-1000000000,1000000000),i('max','Maximum integer',6,-1000000000,1000000000)],'Random integer = floor(U × (max−min+1)) + min',v=>{check(v.max>=v.min,'Maximum must be at least the minimum.');return[r('Random integer',Math.floor(Math.random()*(v.max-v.min+1))+v.min,'number')];},null,{random:true,note:'Uses the browser’s pseudorandom Math.random; not suitable for passwords, cryptography or gambling.'}),
  tool('significant-figures','Significant Figures',M,'Round a number to a chosen count of significant digits.',[n('value','Number',12345.67,null),i('digits','Significant digits',3,1,15)],'Round to the selected number of significant decimal digits',v=>[txt('Rounded representation',v.value.toPrecision(v.digits))],'1.23e+4'),
  tool('decimal-fraction','Decimal to Fraction',M,'Convert finite decimal or percentage notation into an exact fraction.',[t('value','Decimal digits','0.125'),s('kind','Input meaning',[['decimal','Decimal'],['percent','Percentage']],'decimal')],'Decimal fraction = Integer digits / 10^decimalPlaces; divide by 100 for percentage input',v=>[txt('Exact simplified fraction',exactFraction(v.value,v.kind==='percent'))],'1/8',{aliases:['percentage to fraction']}),
  tool('decimal-percentage','Decimal to Percentage',M,'Convert between a fractional decimal and percentage notation.',[n('value','Value',.25,null),s('mode','Direction',[['toPercent','Decimal to percent'],['toDecimal','Percent to decimal']],'toPercent')],'Percent = Decimal × 100; Decimal = Percent / 100',v=>[r(v.mode==='toPercent'?'Percentage (%)':'Decimal',v.mode==='toPercent'?v.value*100:v.value/100)],25),
  tool('percentage-change','Percentage Change',M,'Compare an old value to a new value and find the relative change.',[p('old','Original value',100),n('current','New value',120)],'Percentage change = (New − Original) / Original × 100',v=>[r('Signed change (%)',(v.current-v.old)/v.old*100),r('Absolute change',v.current-v.old)],20,{aliases:['percentage increase','percentage decrease','sales growth','revenue growth','salary hike percentage','salary increment']}),
  tool('percentage-difference','Percentage Difference',M,'Measure symmetric relative difference between two nonnegative values.',[n('a','First value',80),n('b','Second value',120)],'Difference (%) = |a−b| / ((a+b)/2) × 100',v=>[r('Symmetric difference (%)',divide(Math.abs(v.a-v.b),(v.a+v.b)/2)*100)],40),
  tool('percent-of','X Is What Percent of Y',M,'Find the percentage represented by a part of a nonzero whole.',[n('part','Part',25,null),n('whole','Whole',100,null)],'Percentage = Part / Whole × 100',v=>[r('Percentage (%)',divide(v.part,v.whole)*100)],25,{aliases:['basic salary percentage','discount percentage']}),
  tool('reverse-percentage','Reverse Percentage',M,'Recover an original amount before a percentage increase or decrease.',[n('final','Final amount',120),n('percent','Change (%)',20),s('direction','Change applied',[['increase','Increase'],['decrease','Decrease']],'increase')],'Original = Final / (1 ± percentage/100)',v=>{const factor=1+(v.direction==='increase'?1:-1)*v.percent/100;check(factor>0,'A decrease must be less than 100%.');return[r('Original value',v.final/factor)];},100,{aliases:['find original value from percentage']})
];
