import {make,n,p,i,t,s,r,txt,big,gcd,check} from './advanced-shared.js';
const T=make('Number Theory'),integerText=(name,label,value)=>t(name,label,value);
export function fibonacci(count){let a=0n,b=1n,values=[];for(let k=0;k<=count;k++){values.push(a);[a,b]=[b,a+b];}return values;}
export function extendedGcd(a,b){let oldR=a,r=b,oldS=1n,s=0n,oldT=0n,t=1n;while(r){const q=oldR/r;[oldR,r]=[r,oldR-q*r];[oldS,s]=[s,oldS-q*s];[oldT,t]=[t,oldT-q*t];}return oldR<0n?[-oldR,-oldS,-oldT]:[oldR,oldS,oldT];}
export function baseInteger(text,base){check(text.length<=1000,'Use at most 1,000 base digits.');let sign=1n;if(text.startsWith('-')){sign=-1n;text=text.slice(1);}check(text.length>0,'Enter base digits.');let value=0n;for(const char of text.toLowerCase()){const digit='0123456789abcdefghijklmnopqrstuvwxyz'.indexOf(char);check(digit>=0&&digit<base,`Invalid digit for base ${base}.`);value=value*BigInt(base)+BigInt(digit);}return sign*value;}
export function roman(value){let result='';for(const [n,d] of [[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']])while(value>=n){value-=n;result+=d;}return result;}
export const numberTheoryTools=[
 T('fibonacci','Fibonacci / Sequence Generator','Compute an exact Fibonacci number and the sequence from F₀.',[i('index','Index (0–500)',10,0,500)],'F₀=0; F₁=1; Fₙ=Fₙ₋₁+Fₙ₋₂',v=>{const a=fibonacci(v.index);return[txt(`F${v.index}`,String(a[v.index])),txt('Sequence',a.join(', '))];},'55',{aliases:['fibonacci sequence generator']}),
 T('power-sums','Natural Number / Squares / Cubes Sum','Sum the first n positive integers or their squares/cubes exactly.',[i('count','Number of terms',10,0,1000000000),s('power','Power',[['1','Natural numbers'],['2','Squares'],['3','Cubes']],'1')],'Σk=n(n+1)/2; Σk²=n(n+1)(2n+1)/6; Σk³=[n(n+1)/2]²',v=>{const n=BigInt(v.count),a=n*(n+1n)/2n;return[txt('Exact sum',String(v.power==='1'?a:v.power==='2'?n*(n+1n)*(2n*n+1n)/6n:a*a))];},'55',{aliases:['sum of natural numbers','sum of squares','sum of cubes']}),
 T('divisibility','Divisibility','Check whether one exact integer divides another.',[integerText('a','Integer','120'),integerText('b','Divisor','6')],'a divisible by b iff a mod b = 0',v=>{const a=big(v.a),b=big(v.b);check(b!==0n,'Divisor must not be zero.');return[txt('Divisible?',a%b===0n?'Yes':'No'),txt('Remainder',String(a%b))];},'Yes'),
 T('factors','Factors / Common Factors','List positive divisors of an integer or divisors common to two integers.',[i('a','First positive integer',12,1,1000000000000),i('b','Second integer (used for common factors)',18,1,1000000000000),s('mode','Find',[['single','Factors of first integer'],['common','Common factors']],'single')],'Common factors are divisors of GCD(a,b)',v=>{const value=v.mode==='common'?Number(gcd(BigInt(v.a),BigInt(v.b))):v.a,low=[],high=[];for(let d=1;d*d<=value;d++)if(value%d===0){low.push(d);if(d*d!==value)high.unshift(value/d);}return[txt('Positive factors',[...low,...high].join(', '))];},'1, 2, 3, 4, 6, 12',{aliases:['common factors']}),
 T('multiples','Multiples / Common Multiples','Generate a bounded list of positive multiples or common multiples.',[i('a','First integer',3,1,1000000000),i('b','Second integer',4,1,1000000000),i('count','Terms to generate',5,1,100),s('mode','Find',[['single','Multiples of first integer'],['common','Common multiples']],'single')],'Common multiples = k×LCM(a,b); LCM=ab/GCD',v=>{const a=BigInt(v.a),b=BigInt(v.b),step=v.mode==='common'?a/gcd(a,b)*b:a;return[txt('Generated multiples',Array.from({length:v.count},(_,k)=>String(step*BigInt(k+1))).join(', '))];},'3, 6, 9, 12, 15',{aliases:['common multiples']}),
 T('extended-gcd','Extended GCD / Coprime Checker','Find Bézout coefficients and check coprimality of exact integers.',[t('a','First integer','30'),t('b','Second integer','18')],'a×x+b×y=gcd(a,b); coprime iff gcd=1',v=>{const a=big(v.a),b=big(v.b);check(a!==0n||b!==0n,'At least one integer must be nonzero.');const[g,x,y]=extendedGcd(a,b);return[txt('GCD',String(g)),txt('Coefficient x',String(x)),txt('Coefficient y',String(y)),txt('Coprime?',g===1n?'Yes':'No')];},'6',{aliases:['gcd extended','coprime checker']}),
 T('modular-arithmetic','Modular Arithmetic / Exponentiation','Perform exact modular addition, subtraction, multiplication or nonnegative exponentiation.',[t('a','First integer / base','5'),t('b','Second integer / exponent','3'),t('modulus','Positive modulus','7'),s('operation','Operation',[['power','Power'],['add','Add'],['subtract','Subtract'],['multiply','Multiply']],'power')],'Normalize x mod m to [0,m); powers use repeated squaring',v=>{let a=big(v.a),b=big(v.b),m=big(v.modulus);check(m>0n,'Modulus must be positive.');const mod=x=>(x%m+m)%m;let x;if(v.operation==='power'){check(b>=0n,'Exponent must be nonnegative.');x=1n%m;a=mod(a);while(b){if(b%2n)x=x*a%m;a=a*a%m;b/=2n;}}else x=mod(v.operation==='add'?a+b:v.operation==='subtract'?a-b:a*b);return[txt('Exact modular result',String(x))];},'6',{aliases:['modular exponentiation']}),
 T('number-base','Number Base Converter','Convert exact signed integers between bases 2 through 36.',[t('value','Integer digits in source base','255'),i('from','Source base',10,2,36),i('to','Target base',16,2,36)],'Accumulate source digits in source radix, then express integer in target radix',v=>[txt('Converted integer',baseInteger(v.value,v.from).toString(v.to).toUpperCase())],'FF',{aliases:['decimal to binary','binary to decimal','decimal to octal','octal to decimal','decimal to hex','hex to decimal','binary to hex','hex to binary']}),
 T('base-arithmetic','Binary / Octal / Hex Arithmetic','Add, subtract, multiply or divide exact integers in a selected radix.',[t('a','First operand','101'),t('b','Second operand','10'),s('base','Radix',[['2','Binary'],['8','Octal'],['16','Hexadecimal']],'2'),s('operation','Operation',[['add','Add'],['subtract','Subtract'],['multiply','Multiply'],['divide','Integer divide']],'add')],'Parse operands in selected radix; calculate exact integer result',v=>{const a=baseInteger(v.a,Number(v.base)),b=baseInteger(v.b,Number(v.base));check(v.operation!=='divide'||b!==0n,'Divisor must not be zero.');const x=v.operation==='add'?a+b:v.operation==='subtract'?a-b:v.operation==='multiply'?a*b:a/b;return[txt('Result in selected base',x.toString(Number(v.base)).toUpperCase()),...(v.operation==='divide'?[txt('Remainder',(a%b).toString(Number(v.base)))]:[])];},'111',{aliases:['binary calculator','octal calculator','hex calculator'],note:'Signed integers only. Division truncates toward zero and reports the remainder.'}),
 T('roman-numerals','Roman Numeral Converter','Convert canonical Roman numerals and integers from 1 to 3999.',[t('value','Decimal integer or Roman numeral','1994')],'Canonical subtractive notation: IV, IX, XL, XC, CD, CM',v=>{const text=v.value.trim().toUpperCase();if(/^\d+$/.test(text)){const x=Number(text);check(x>=1&&x<=3999,'Use an integer from 1 to 3999.');return[txt('Roman numeral',roman(x))];}check(/^[IVXLCDM]+$/.test(text),'Use a canonical Roman numeral.');const vals={I:1,V:5,X:10,L:50,C:100,D:500,M:1000};let x=0;for(let k=0;k<text.length;k++)x+=vals[text[k]]<(vals[text[k+1]]||0)?-vals[text[k]]:vals[text[k]];check(x>=1&&x<=3999&&roman(x)===text,'Use canonical Roman notation from I to MMMCMXCIX.');return[r('Decimal integer',x)];},'MCMXCIV'),
 T('notation','Scientific / Engineering Notation','Express a finite number using powers of ten or powers divisible by three.',[n('value','Number',12345,null),s('mode','Notation',[['scientific','Scientific'],['engineering','Engineering']],'scientific')],'x = mantissa×10^exponent; engineering exponent is a multiple of 3',v=>{if(v.value===0)return[txt('Notation','0 × 10^0')];let e=Math.floor(Math.log10(Math.abs(v.value)));if(v.mode==='engineering')e=Math.floor(e/3)*3;const mantissa=Number(v.value.toExponential(12).split('e')[0])*10**(Number(v.value.toExponential().split('e')[1])-e);return[txt('Notation',`${Number(mantissa.toPrecision(12))} × 10^${e}`)];},'1.2345 × 10^4',{aliases:['scientific notation','engineering notation']})
];
