import {tool,n,p,s,r,divide,requireCondition as check} from './shared.js';
const P='Physics';
export const physicsTools=[
  tool('speed-distance-time','Speed Distance Time',P,'Solve one motion quantity from the other two for constant speed.',[s('solve','Solve for',[['speed','Speed'],['distance','Distance'],['time','Time']],'speed'),n('distance','Distance (m; ignored when solving distance)',100),n('speed','Speed (m/s; ignored when solving speed)',10),p('time','Time (s; ignored when solving time)',10)],'Speed = Distance/Time; Distance = Speed×Time; Time = Distance/Speed',v=>[r(v.solve==='speed'?'Speed (m/s)':v.solve==='distance'?'Distance (m)':'Time (s)',v.solve==='speed'?v.distance/v.time:v.solve==='distance'?v.speed*v.time:divide(v.distance,v.speed))],10,{aliases:['travel time','average speed','distance calculator']}),
  tool('acceleration','Acceleration',P,'Calculate average acceleration from a velocity change.',[n('initial','Initial velocity (m/s)',0,null),n('final','Final velocity (m/s)',20,null),p('time','Elapsed time (s)',5)],'Acceleration = (Final velocity − Initial velocity) / Time',v=>[r('Acceleration (m/s²)',(v.final-v.initial)/v.time)],4),
  tool('force','Force',P,'Calculate net force from mass and acceleration.',[n('mass','Mass (kg)',10),n('acceleration','Acceleration (m/s²)',2,null)],'Force = Mass × Acceleration',v=>[r('Force (N)',v.mass*v.acceleration)],20),
  tool('work','Work',P,'Calculate work by a constant force at an angle to displacement.',[n('force','Force magnitude (N)',10),n('distance','Displacement magnitude (m)',5),n('angle','Angle (degrees)',0,0,{max:180})],'Work = Force × Displacement × cos(angle)',v=>[r('Work (J)',v.force*v.distance*Math.cos(v.angle*Math.PI/180))],50),
  tool('mechanical-power','Mechanical Power',P,'Calculate average power from work and elapsed time.',[n('work','Work (J)',100,null),p('time','Elapsed time (s)',5)],'Power = Work / Time',v=>[r('Average power (W)',v.work/v.time)],20,{aliases:['power calculator']}),
  tool('momentum','Momentum',P,'Find linear momentum along one direction.',[n('mass','Mass (kg)',10),n('velocity','Velocity (m/s)',2,null)],'Momentum = Mass × Velocity',v=>[r('Momentum (kg·m/s)',v.mass*v.velocity)],20),
  tool('kinetic-energy','Kinetic Energy',P,'Calculate classical kinetic energy from mass and speed.',[n('mass','Mass (kg)',2),n('speed','Speed (m/s)',3)],'Kinetic energy = ½ × Mass × Speed²',v=>[r('Kinetic energy (J)',.5*v.mass*v.speed**2)],9,{note:'Classical, nonrelativistic translational motion.'}),
  tool('potential-energy','Potential Energy',P,'Estimate gravitational potential energy relative to a chosen height datum.',[n('mass','Mass (kg)',1),n('height','Height relative to datum (m)',10,null),p('gravity','Local gravity (m/s²)',9.80665)],'Potential energy = Mass × Gravity × Height',v=>[r('Potential energy (J)',v.mass*v.gravity*v.height)],98.0665,{note:'Assumes uniform gravity; height may be negative relative to the chosen reference.'}),
  tool('density','Density',P,'Solve bulk density, mass or volume using consistent SI units.',[n('mass','Mass (kg)',10),p('volume','Volume (m³)',2),p('density','Density (kg/m³; inverse modes)',5),s('solve','Solve for',[['density','Density'],['mass','Mass'],['volume','Volume']],'density')],'Density=Mass/Volume; Mass=Density×Volume; Volume=Mass/Density',v=>[r(v.solve==='mass'?'Mass (kg)':v.solve==='volume'?'Volume (m³)':'Density (kg/m³)',v.solve==='mass'?v.density*v.volume:v.solve==='volume'?v.mass/v.density:v.mass/v.volume)],5),
  tool('pressure','Pressure',P,'Calculate average pressure from perpendicular force and area.',[n('force','Normal force (N)',100),p('area','Contact area (m²)',2)],'Pressure = Normal force / Area',v=>[r('Pressure (Pa)',v.force/v.area)],50),
  tool('wave','Frequency / Wavelength',P,'Solve wave frequency, wavelength or speed from the other two.',[s('solve','Solve for',[['frequency','Frequency'],['wavelength','Wavelength'],['speed','Wave speed']],'frequency'),p('speed','Wave speed (m/s)',300),p('wavelength','Wavelength (m)',3),p('frequency','Frequency (Hz)',100)],'Wave speed = Frequency × Wavelength',v=>[r(v.solve==='frequency'?'Frequency (Hz)':v.solve==='wavelength'?'Wavelength (m)':'Wave speed (m/s)',v.solve==='frequency'?v.speed/v.wavelength:v.solve==='wavelength'?v.speed/v.frequency:v.frequency*v.wavelength)],100,{aliases:['frequency calculator','wavelength']}),
  tool('torque','Torque',P,'Calculate torque from force, lever length and included angle.',[n('force','Force magnitude (N)',10),n('length','Lever arm length (m)',2),n('angle','Force/lever angle (degrees)',90,0,{max:180})],'Torque = Force × Lever length × sin(angle)',v=>[r('Torque magnitude (N·m)',v.force*v.length*Math.sin(v.angle*Math.PI/180))],20),
  tool('mechanical-advantage','Mechanical Advantage',P,'Calculate actual force amplification by a machine.',[p('input','Input effort force (N)',10),n('output','Output load force (N)',50)],'Actual mechanical advantage = Output force / Input force',v=>[r('Mechanical advantage',v.output/v.input)],5)
];
