import {make,n,p,i,s,r,txt,data,list,sum,mean,paired,quantile,sampleSD,check} from './advanced-shared.js';
const T=make('Statistics');
export const statisticsTools=[
 T('mean-absolute-deviation','Mean Absolute Deviation','Measure average absolute distance from the arithmetic mean.',[data()],'MAD = Σ|x − mean| / n',v=>{const a=list(v.numbers),m=mean(a);return[r('Mean absolute deviation',mean(a.map(x=>Math.abs(x-m)))),r('Dataset mean',m)];},1),
 T('coefficient-variation','Coefficient of Variation','Compare population or sample standard deviation with a positive mean.',[data(),s('kind','Standard deviation basis',[['population','Population'],['sample','Sample']],'population')],'CV (%) = SD / Mean × 100',v=>{const a=list(v.numbers),m=mean(a);check(m>0,'Coefficient of variation requires a positive mean.');const sd=v.kind==='sample'?sampleSD(a):Math.sqrt(mean(a.map(x=>(x-m)**2)));return[r('Coefficient of variation (%)',sd/m*100)];},44.72135955,{note:'Meaningful for ratio-scale data with a nonzero origin; near-zero means make CV unstable.'}),
 T('z-score','Z-Score','Standardize an observation using a supplied reference mean and standard deviation.',[n('x','Observation',70,null),n('mean','Reference mean',50,null),p('sd','Reference standard deviation',10)],'z = (x − μ)/σ',v=>[r('Z-score',(v.x-v.mean)/v.sd)],2),
 T('standard-error','Standard Error','Estimate standard error of the sample mean from independent observations.',[data()],'SE = Sample SD / √n',v=>{const a=list(v.numbers);return[r('Standard error',sampleSD(a)/Math.sqrt(a.length)),r('Sample standard deviation',sampleSD(a))];},0.6454972244,{note:'Independent observations; describes precision of the mean, not spread of individual observations.'}),
 T('confidence-interval','Confidence Interval / Margin of Error','Compute a normal-reference interval for a mean using a chosen critical value.',[n('mean','Estimated mean',100,null),p('sd','Known population SD / assumed SD',10),i('count','Sample size',100,1),p('z','Normal critical value',1.95996398454)],'Margin = z × σ/√n; Interval = Mean ± Margin',v=>{const e=v.z*v.sd/Math.sqrt(v.count);return[r('Margin of error',e),r('Lower bound',v.mean-e),r('Upper bound',v.mean+e)];},1.95996398454,{aliases:['margin of error'],note:'Normal interval: known population SD, or a large-sample approximation. Not a Student-t interval for small samples with unknown SD. Enter the critical value appropriate to your chosen confidence level.'}),
 T('sample-size','Sample Size','Plan an independent binomial-proportion sample under a normal approximation.',[p('z','Normal critical value',1.96),n('proportion','Expected proportion (0–1)',0.5,0,{max:1}),p('error','Absolute margin (0–1)',0.05,{max:1})],'n = ceil(z² p(1−p)/e²)',v=>[r('Required sample size',Math.max(1,Math.ceil(v.z**2*v.proportion*(1-v.proportion)/v.error**2)))],385,{note:'Simple random independent sampling; no finite-population correction, clustering, nonresponse or multiple-testing adjustment. Use p=0.5 when uncertain.'}),
 T('quartiles','Quartiles / Five Number Summary','Summarize a sorted dataset with interpolated quartiles and IQR.',[data()],'R type 7: h=(n−1)p; interpolate adjacent sorted values; IQR=Q3−Q1',v=>{const a=list(v.numbers);return[r('Interquartile range',quantile(a,.75)-quantile(a,.25)),r('Minimum',Math.min(...a)),r('Q1',quantile(a,.25)),r('Median',quantile(a,.5)),r('Q3',quantile(a,.75)),r('Maximum',Math.max(...a))];},1.5,{aliases:['quartile','interquartile range','five number summary'],note:'Linear interpolation (R quantile type 7). Other quartile conventions may differ.'}),
 T('percentile','Percentile','Find a selected interpolated percentile in a numerical dataset.',[data(),n('percent','Percentile (0–100)',75,0,{max:100})],'h=(n−1) × Percentile/100; linear interpolation',v=>[r('Percentile value',quantile(list(v.numbers),v.percent/100))],3.25),
 T('outliers','Outlier','Identify values outside Tukey fences from interpolated quartiles.',[data('numbers','Dataset','1 2 3 4 100'),n('factor','IQR fence multiplier',1.5)],'Fences = Q1 − k×IQR and Q3 + k×IQR',v=>{const a=list(v.numbers),q1=quantile(a,.25),q3=quantile(a,.75),lo=q1-v.factor*(q3-q1),hi=q3+v.factor*(q3-q1),outside=a.filter(x=>x<lo||x>hi);return[txt('Values outside fences',outside.length?outside.join(', '):'None'),r('Lower fence',lo),r('Upper fence',hi)];},'100'),
 T('covariance','Covariance','Measure joint variation of paired observations.',[data('x','X dataset','1 2 3'),data('y','Y dataset','2 4 6'),s('kind','Covariance basis',[['sample','Sample'],['population','Population']],'sample')],'Covariance = Σ(x−x̄)(y−ȳ) / (n−1 for sample; n for population)',v=>{const[a,b]=paired(v.x,v.y),mx=mean(a),my=mean(b);return[r('Covariance',sum(a.map((x,k)=>(x-mx)*(b[k]-my)))/(a.length-(v.kind==='sample'?1:0)))];},2),
 T('linear-regression','Linear Regression / Pearson Correlation','Fit an ordinary least-squares line and report correlation and R-squared.',[data('x','X dataset','1 2 3'),data('y','Y dataset','2 4 6')],'Slope=Sxy/Sxx; Intercept=ȳ−Slope×x̄; r=Sxy/√(Sxx×Syy); R²=r²',v=>{const[a,b]=paired(v.x,v.y),mx=mean(a),my=mean(b),xx=sum(a.map(x=>(x-mx)**2)),yy=sum(b.map(y=>(y-my)**2)),xy=sum(a.map((x,k)=>(x-mx)*(b[k]-my)));check(xx>0&&yy>0,'Both datasets must contain varying values to report correlation.');const slope=xy/xx,corr=Math.max(-1,Math.min(1,xy/Math.sqrt(xx*yy)));return[r('Slope',slope),r('Intercept',my-slope*mx),r('Pearson correlation',corr),r('R-squared',corr*corr)];},2,{aliases:['correlation coefficient','pearson correlation','regression line','r squared','r-squared'],note:'Unweighted OLS with an intercept; paired observations. Association does not establish causation.'}),
 T('rms','RMS','Calculate the root mean square of a numerical dataset.',[data()],'RMS = √(Σx²/n)',v=>[r('Root mean square',Math.sqrt(mean(list(v.numbers).map(x=>x*x))))],2.7386127875),
 T('frequency-distribution','Frequency Distribution / Relative Frequency','Count exact distinct dataset values and their relative frequencies.',[data('numbers','Dataset','1 2 2 3')],'Relative frequency (%) = Count of value / Total × 100',v=>{const a=list(v.numbers),counts=new Map();a.forEach(x=>counts.set(x,(counts.get(x)||0)+1));check(counts.size<=100,'Use at most 100 distinct values for the frequency table.');return[r('Total observations',a.length),...[...counts].sort((a,b)=>a[0]-b[0]).map(([x,c])=>txt(`Value ${x}`,`${c} observations; ${(c/a.length*100).toFixed(4)}%`))];},4,{aliases:['relative frequency'],note:'Exact-value counts; values are not grouped into histogram bins.'}),
 T('odds','Odds','Convert a probability into event-to-non-event odds.',[n('probability','Event probability (0 ≤ p < 1)',.75,0,{max:1})],'Odds = p/(1−p)',v=>{check(v.probability<1,'Probability must be below 1 for finite odds.');return[r('Odds in favor',v.probability/(1-v.probability))];},3),
 T('odds-ratio','Odds Ratio','Compare exposure odds in a positive 2×2 contingency table.',[p('a','Exposed events',20),p('b','Exposed non-events',10),p('c','Unexposed events',10),p('d','Unexposed non-events',20)],'OR = (a×d)/(b×c)',v=>[r('Odds ratio',v.a*v.d/(v.b*v.c))],4,{note:'Positive cell counts, no continuity correction. Odds ratio is not relative risk or a causal estimate.'})
];
