import {make,n,p,s,r,check} from './advanced-shared.js';
const T=make('Thermodynamics'),note='Educational ideal model. Material properties and boundary conditions are supplied by you; not a thermal-system or pressure-vessel design.';
export const thermodynamicsTools=[
 T('heat-energy','Heat Energy / Specific Heat','Solve sensible heat or specific heat using mass and temperature change.',[p('mass','Mass (kg)',2),p('specific','Specific heat (J/kg/K)',4180),n('delta','Temperature change (K or °C)',10,null),n('heat','Heat energy (J; specific-heat mode)',83600,null),s('solve','Solve for',[['heat','Heat energy'],['specific','Specific heat']],'heat')],'Q=mcΔT; c=Q/(mΔT)',v=>{if(v.solve==='specific'){check(v.delta!==0,'Temperature change must be nonzero.');const c=v.heat/(v.mass*v.delta);check(c>0,'The inputs must give a positive specific heat.');return[r('Specific heat (J/kg/K)',c)];}return[r('Sensible heat (J)',v.mass*v.specific*v.delta)];},83600,{aliases:['heat energy','specific heat'],note:note+' Constant specific heat; no phase transition or heat loss.'}),
 T('heat-conduction','Heat Transfer (Conduction)','Estimate steady heat flow through a homogeneous planar layer.',[n('conductivity','Thermal conductivity (W/m/K)',.5),n('area','Layer area (m²)',10),p('thickness','Thickness (m)',.1),n('delta','Temperature difference (K)',20,null)],'Heat rate(W)=Conductivity×Area×Temperature difference/Thickness',v=>[r('Estimated conductive heat rate (W)',v.conductivity*v.area*v.delta/v.thickness)],1000,{aliases:['heat transfer'],note:note+' One-dimensional steady conduction; no radiation, convection, thermal bridges or contact resistance.'}),
 T('temperature-difference','Temperature Difference','Subtract temperatures and express the interval in Celsius/Kelvin or Fahrenheit.',[n('initial','Initial temperature',20,null),n('final','Final temperature',30,null),s('unit','Input unit',[['C','Celsius'],['F','Fahrenheit'],['K','Kelvin']],'C')],'ΔK=Δ°C; Δ°F=Δ°C×9/5',v=>{const absolute=x=>v.unit==='K'?x:v.unit==='C'?x+273.15:(x-32)*5/9+273.15;check(absolute(v.initial)>=0&&absolute(v.final)>=0,'Temperatures must not be below absolute zero.');const d=(v.final-v.initial)*(v.unit==='F'?5/9:1);return[r('Temperature change (K or °C)',d),r('Temperature change (°F)',d*9/5)];},10,{note}),
 T('thermal-expansion','Thermal Expansion','Estimate a small linear expansion or contraction from an entered coefficient.',[p('length','Initial length (m)',10),n('coefficient','Linear expansion coefficient (1/K)',.000012),n('delta','Temperature change (K)',50,null)],'ΔL=αL₀ΔT; Final length=L₀+ΔL',v=>{const change=v.coefficient*v.length*v.delta;check(v.length+change>0,'Final modeled length must be positive.');return[r('Estimated length change (m)',change),r('Estimated final length (m)',v.length+change)];},.006,{note:note+' Constant linear coefficient and small strain; large temperature ranges may invalidate the approximation.'}),
 T('ideal-gas','Ideal Gas Law','Solve one ideal gas state quantity with absolute pressure and temperature.',[p('pressure','Absolute pressure (Pa)',100000),p('volume','Volume (m³)',.01),p('moles','Amount (mol)',1),p('temperature','Absolute temperature (K)',300),s('solve','Solve for',[['pressure','Pressure'],['volume','Volume'],['moles','Moles'],['temperature','Temperature']],'pressure')],'PV=nRT; R=8.31446261815324 J/(mol·K)',v=>{const R=8.31446261815324;return[r(v.solve==='pressure'?'Absolute pressure (Pa)':v.solve==='volume'?'Volume (m³)':v.solve==='moles'?'Amount (mol)':'Absolute temperature (K)',v.solve==='pressure'?v.moles*R*v.temperature/v.volume:v.solve==='volume'?v.moles*R*v.temperature/v.pressure:v.solve==='moles'?v.pressure*v.volume/(R*v.temperature):v.pressure*v.volume/(v.moles*R))];},249433.8785446,{aliases:['ideal gas chemistry','pressure volume'],note:note+' SI units, ideal gas; gauge pressure and Celsius temperature must be converted to absolute values.'}),
 T('combined-gas','Combined Gas / Boyle’s / Charles’s Law','Calculate a final gas volume for a fixed gas amount across two states.',[p('pressure1','Initial absolute pressure (Pa)',100000),p('volume1','Initial volume (m³)',1),p('temperature1','Initial temperature (K)',300),p('pressure2','Final absolute pressure (Pa)',200000),p('temperature2','Final temperature (K)',300)],'V₂=P₁V₁T₂/(P₂T₁)',v=>[r('Final volume (m³)',v.pressure1*v.volume1*v.temperature2/(v.pressure2*v.temperature1))],.5,{aliases:['combined gas law','boyles law','charles law'],note:note+' Fixed gas amount. Equal temperatures yield Boyle’s law; equal pressures yield Charles’s law.'})
];
