import {tool,text,line,select} from '../shared/definitions.js';
const csvOptions={files:true,optionalFiles:true,accept:'.csv,.tsv,.txt,application/json',limits:'Paste data or optionally select a UTF-8 file (selected file takes precedence). Tables are limited to 10,000 rows and 200 columns.'};
export default [
tool('Data','data','csv-tools','CSV / JSON / TSV Converter & Viewer','Parse quoted CSV fields reliably, validate tables, and convert between CSV, JSON and TSV.',[text('input','Data','name,score\nAlex,10\nSam,20'),select('source','Input format',['CSV','TSV','JSON'],'CSV'),select('mode','Output',['CSV','TSV','JSON','View / Validate'],'JSON')],['CSV to JSON','JSON to CSV','CSV to TSV','TSV to CSV','CSV viewer','CSV formatter','CSV validator'],csvOptions),
tool('Data','data','csv-editor','CSV Cleaner, Sorter & Column Editor','Deduplicate or sort rows, filter values, select/rename columns, or remove empty rows from quoted CSV.',[text('input','CSV','name,score\nAlex,10\nSam,20\nAlex,10'),select('mode','Operation',['Deduplicate rows','Sort ascending','Sort descending','Filter contains','Select columns','Rename columns','Remove empty rows'],'Deduplicate rows'),line('column','Column name','name'),line('value','Filter text / comma-separated column names / new name','Alex',true)],['CSV duplicate remover','CSV sorter','CSV filter','CSV column selector','CSV column renamer','CSV empty row remover'],csvOptions),
tool('Data','data','csv-statistics','CSV Counts & Numeric Statistics','Count rows, columns and empty cells; summarize a chosen numeric column.',[text('input','CSV','name,score\nAlex,10\nSam,20'),line('column','Numeric column','score')],['CSV row counter','CSV column counter','CSV basic statistics'],csvOptions),
tool('Files','data','file-viewer','Local File Size, MIME & Text Viewer','Inspect file facts and optionally decode UTF-8 text or encode a file as Base64.',[select('mode','Operation',['Info','UTF-8 text','Base64'],'Info')],['file size checker','file extension checker','file MIME checker','file to base64','text file viewer'],{files:true}),
tool('Files','data','base64-file','Base64 to File','Decode Base64 bytes into a local downloadable file.',[text('input','Base64','SGVsbG8='),line('filename','Download filename','decoded.txt'),line('mime','MIME type','application/octet-stream')],['base64 to file']),
tool('Files','data','filename-cleaner','Filename Cleaner','Clean reserved filename characters and Windows device names, without changing files on disk.',[text('input','One filename per line','report: draft?.txt\nCON.txt')],['file name cleaner'])
];
