import {tool,line,number,select,color} from '../shared/definitions.js';
const t=(id,name,desc,fields,aliases=[])=>tool('Design','design',id,name,desc,fields,aliases);
export default [
t('color-tools','Color Picker & HEX / RGB / HSL Converter','Convert valid opaque HEX, RGB and HSL colors into equivalent CSS values.',[line('input','Color (#hex, rgb(), hsl()) — used for Text mode','#3865e9',true),color('picker','Color picker (use Picker mode)','#3865e9'),select('mode','Input',['Text','Picker'],'Text')],['HEX to RGB','RGB to HEX','RGB to HSL','HSL to RGB','color converter']),
t('color-palette','Color Palette, Shades & Tints Generator','Generate random palettes, complements, shades or tints from a base color.',[color('input','Base color','#3865e9'),select('mode','Palette',['Random','Complementary','Shades','Tints'],'Complementary'),number('count','Colors',5,2,20)],['random color generator','palette generator','complementary colors','color shades','color tints']),
t('gradient-generator','CSS Gradient Generator','Generate a two-color linear CSS gradient with a live preview.',[color('first','First color','#3865e9'),color('second','Second color','#9b5de5'),number('angle','Angle',135,0,360)],['gradient generator']),
t('contrast-checker','WCAG Contrast Checker','Compute sRGB relative luminance and contrast ratios for opaque text and background colors.',[color('first','Text color','#111827'),color('second','Background color','#ffffff')],['color contrast','WCAG checker']),
t('css-design','CSS Shadow, Radius & Button Generator','Generate CSS declarations and preview a button or box with editable geometry.',[select('mode','Output',['Box shadow','Text shadow','Border radius','Button'],'Button'),number('x','Horizontal shadow (px)',0,-100,100),number('y','Vertical shadow (px)',6,-100,100),number('blur','Blur (px)',20,0,200),number('spread','Spread (px)',0,-100,100),number('radius','Radius (px)',12,0,200),color('background','Background','#3865e9'),color('foreground','Text / shadow color','#ffffff')],['CSS box shadow generator','CSS text shadow','border radius generator','CSS button generator'])
];
