import {tool,text,line,number,select} from '../shared/definitions.js';
const t=(id,name,desc,fields,aliases=[],o={})=>tool('Developer','developer',id,name,desc,fields,aliases,o);
export default [
t('sql-formatter','SQL Formatter','Format SQL locally without executing queries.',[text('input','SQL','select id,name from users where active=true;')],['SQL formatter']),
t('json-tools','JSON Formatter, Validator & Viewer','Validate JSON, format, minify, or escape it as a JSON string.',[text('input','JSON','{"name":"CalcHub","items":[1,2]}'),select('mode','Operation',['Format','Minify','Validate','Tree','Escape','Unescape'],'Format')],['JSON formatter','JSON validator','JSON minifier','JSON viewer','JSON escape unescape']),
t('xml-tools','XML Formatter & Validator','Parse XML locally, report syntax errors, and format or conservatively remove inter-element whitespace.',[text('input','XML','<root><item>Hello</item></root>'),select('mode','Operation',['Format','Validate','Minify'],'Format')],['XML formatter','XML validator','XML minifier']),
t('code-formatter','HTML, CSS & JavaScript Formatter','Format source code with locally bundled Prettier; JavaScript minification uses Terser without executing input.',[text('input','Source','const data={value:42};'),select('language','Language',['JavaScript','HTML','CSS'],'JavaScript'),select('mode','Operation',['Format','Minify'],'Format')],['HTML formatter','CSS formatter','JavaScript formatter','JS minifier','HTML minifier','CSS minifier'],{limits:'Source is limited to 100,000 characters. CSS minification uses a parser, JavaScript uses Terser, and HTML preserves significant text whitespace.'}),
t('markdown-tools','Markdown Preview & HTML Converter','Convert Markdown to sanitized HTML with an isolated preview, or convert HTML to Markdown.',[text('input','Source','# Hello\n\n**Local** Markdown.'),select('mode','Operation',['Markdown to HTML','HTML to Markdown'],'Markdown to HTML')],['Markdown preview','Markdown to HTML','HTML to Markdown']),
t('encoding-tools','Text Encoding & Escape Converter','Convert UTF-8 text using Base64, URI components, HTML entities, Unicode escapes, hexadecimal or binary.',[text('input','Text','Hello 🌍'),select('encoding','Encoding',['Base64','URL','HTML entities','Unicode escapes','Hex UTF-8','Binary UTF-8','JSON string','ASCII decimal'],'Base64'),select('mode','Direction',['Encode','Decode'],'Encode')],['base64 encode decode','URL encode decode','HTML escape unescape','Unicode ASCII converter','hex to text','binary to text','string escape unescape']),
t('jwt-decoder','JWT Payload Decoder','Decode JWT header and payload locally. This does not verify signatures or establish trust.',[text('input','JWT','eyJhbGciOiJub25lIn0.eyJzdWIiOiJkZW1vIn0.')],['JWT decoder']),
t('timestamp-tools','Timestamp & ISO Date Converter','Convert Unix seconds, Unix milliseconds and explicit-zone ISO dates.',[line('input','Timestamp or ISO date','2026-01-01T00:00:00Z'),select('mode','Input type',['ISO date','Unix seconds','Unix milliseconds'],'ISO date')],['epoch converter','timestamp converter','ISO date converter','Unix timestamp']),
t('regex-tester','Regex Tester & Replacer','Test patterns in a dedicated worker with a one-second timeout and match limits.',[text('input','Text','one two one'),line('pattern','Pattern','one'),line('flags','Flags','g',true),line('replacement','Replacement','1',true),select('mode','Operation',['Matches','Replace'],'Matches')],['regex tester']),
t('cron-reader','Cron Expression Reader','Describe five-field numeric cron syntax without pretending to support every scheduler dialect.',[line('input','Five-field cron','*/15 9-17 * * 1-5')],['cron expression reader'],{limits:'Five fields only: minute hour day-of-month month day-of-week. Numeric lists, ranges, *, and steps are supported; names, macros, L/W/# and seconds are rejected. Scheduling depends on server timezone and cron dialect.'})
];
