import {tool,line,number,select,color,text} from '../shared/definitions.js';
const common=[select('format','Output format',['PNG','JPEG','WebP'],'JPEG'),number('quality','Quality (%)',85,1,100)];
const t=(id,name,desc,fields,aliases=[],o={})=>tool('Image','image',id,name,desc,fields,aliases,{files:true,accept:'image/png,image/jpeg,image/webp',...o,limits:'PNG, JPEG and WebP inputs only, at most 20 images / 50 MB each and 24 megapixels per image. Batch operations run sequentially. Re-encoding edits discard animation and EXIF metadata. Base64 conversion preserves original file bytes and metadata. Output size is not guaranteed to be smaller.'});
export default [
t('image-compressor','Image Compressor & Format Converter','Re-encode images locally, choose format and quality, and compare actual output sizes.',common,['image compressor','JPG compressor','PNG compressor','WebP converter','JPG to PNG','PNG to JPG','image converter','batch image compressor','image quality adjuster'],{multiple:true}),
t('image-resizer','Image Resizer & Aspect Ratio Tool','Resize within a bounding box while preserving aspect ratio; upscaling requires an explicit option.',[number('width','Maximum width',1200,1,8000),number('height','Maximum height',1200,1,8000),select('upscale','Allow upscaling',['No','Yes'],'No'),...common],['batch image resizer','image dimensions','aspect ratio'],{multiple:true}),
t('image-editor','Image Crop, Rotate & Flip','Crop by explicit pixel coordinates, rotate in 90-degree steps, and flip horizontally or vertically.',[number('x','Crop left',0,0,8000),number('y','Crop top',0,0,8000),number('width','Crop width (0 = remaining)',0,0,8000),number('height','Crop height (0 = remaining)',0,0,8000),select('rotation','Rotate degrees',['0','90','180','270'],'0'),select('flip','Flip',['None','Horizontal','Vertical','Both'],'None'),...common],['image cropper','image rotate','image flip']),
t('image-filters','Image Filters & Watermark','Apply canvas filters, a sharpen convolution, or text watermark to a local image.',[select('effect','Effect',['None','Grayscale','Brightness','Contrast','Saturation','Blur','Sharpen'],'None'),number('amount','Effect amount (%) / blur pixels',100,0,300),line('watermark','Watermark text','',true),number('font','Watermark font size',32,8,300),color('color','Text color','#ffffff'),...common],['image grayscale','brightness contrast saturation','brightness adjuster','contrast adjuster','saturation adjuster','image blur sharpen','image text overlay','image watermark']),
t('image-info','Image Metadata & Size Viewer','Read decoded dimensions, file size, MIME type and aspect ratio without uploading.',[],['image dimension checker','image file size checker','image metadata viewer']),
t('image-base64','Image to Base64','Encode the selected image as a Base64 data URL.',[],['image to base64']),
tool('Image','image','base64-image','Base64 to Image','Decode a PNG, JPEG or WebP data URL and download it locally.',[text('input','Image data URL','data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=')],['base64 to image'])
];
