import {tool,line,number,select} from '../shared/definitions.js';
const t=(id,name,desc,fields,aliases=[],o={})=>tool('PDF','pdf',id,name,desc,fields,aliases,{files:true,accept:'application/pdf',limits:'Unencrypted PDFs only. At most 20 files / 50 MB each and 500 pages per input. Existing signatures, document outlines, forms and cross-document links may not survive copied-page operations. Review your downloaded result. No compression or password protection is claimed.',...o});
export default [
t('pdf-to-images','PDF to Images','Render selected PDF pages locally as PNG images with a bundled PDF.js worker.',[line('pages','Pages: 1,3-5 (blank = all)','',true),number('scale','Render scale',1,1,3)],['PDF to PNG'],{limits:'Unencrypted PDFs only. Up to 20 selected pages, 12 megapixels per rendered page. Font substitution may affect appearance; review output. No external font or document URLs are fetched.'}),
t('pdf-merge','PDF Merger','Merge PDFs in the order shown in the selected file list.',[],['merge PDF'],{multiple:true}),
t('pdf-organizer','PDF Page Organizer','Extract, delete, reorder, rotate, or split PDF pages using explicit page numbers.',[select('mode','Operation',['Extract / Reorder','Delete','Rotate','Split every page'],'Extract / Reorder'),line('pages','Pages: 1,3-5 (blank = all)','',true),select('rotation','Rotation (degrees)',['90','180','270'],'90')],['PDF splitter','PDF extract pages','PDF delete pages','PDF reorder pages','PDF rotate','PDF page organizer']),
t('pdf-info','PDF Metadata & Page Counter','Read PDF title, author, producer, dates and page dimensions locally.',[],['PDF metadata viewer','PDF page counter']),
t('pdf-overlay','PDF Page Numbers & Text Watermark','Add page numbers or a text watermark to every page of a local PDF.',[select('mode','Overlay',['Page numbers','Text watermark'],'Page numbers'),line('text','Watermark text','DRAFT'),number('size','Font size',24,8,150)],['PDF page number tool','PDF text watermark']),
t('pdf-image-watermark','PDF Image Watermark','Apply a local PNG or JPEG watermark image to each PDF page. Select one PDF and one image in either order.',[number('width','Watermark width (PDF points)',150,10,1000),number('opacity','Opacity (%)',35,1,100)],['PDF watermark image'],{multiple:true,accept:'application/pdf,image/png,image/jpeg'}),
t('images-to-pdf','Images to PDF','Build a PDF from local PNG, JPEG or WebP images, one image per page.',[],['JPG to PDF','PNG to PDF','image to PDF'],{multiple:true,accept:'image/png,image/jpeg,image/webp'})
];
