import {tool,text,line,number,select} from '../shared/definitions.js';
const t=(id,name,desc,fields,aliases=[],o={})=>tool('Security','security',id,name,desc,fields,aliases,o);
export default [
t('secure-generator','Secure Password, PIN & Token Generator','Generate uniformly sampled passwords, PINs, UUIDs or random strings with Web Crypto.',[select('mode','Output',['Password','PIN','UUID','Token','Random string'],'Password'),number('length','Length (UUID ignores this)',20,4,256),number('count','Count',1,1,100),select('symbols','Password symbols',['Include','Exclude'],'Include'),line('alphabet','Random string alphabet (used for Random string)','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',true)],['password generator','PIN generator','UUID generator','GUID generator','random token','random string generator']),
t('passphrase-generator','Passphrase Generator','Generate words from a visible, fixed 256-word list using cryptographic randomness.',[number('count','Words',16,10,30),line('separator','Separator','-',true)],['secure passphrase'],{limits:'The 256-word vocabulary provides 8 bits per independently chosen word: 10 words give 80 bits; the default 16 words give 128 bits. The word list is public. Do not shorten the generated phrase.'}),
t('password-strength','Password Strength Estimator','Inspect length and common patterns locally. The estimate is a heuristic, not a cracking-time prediction.',[{...line('input','Password',''),type:'password'}],['password strength checker'],{limits:'No breached-password lookup or cracking is performed. Do not treat this heuristic as proof of security.'}),
t('hash-tools','SHA & HMAC Generator','Compute SHA-256, SHA-384 or SHA-512 and optional HMAC using Web Crypto.',[text('input','Message','Hello'),select('algorithm','Algorithm',['SHA-256','SHA-384','SHA-512'],'SHA-256'),select('mode','Operation',['Digest','HMAC'],'Digest'),line('key','HMAC key','example-key',true)],['SHA256 generator','SHA384 generator','SHA512 generator','HMAC generator']),
t('file-hash','File Hash Checker','Compute a local SHA digest and optionally compare it to an expected hexadecimal hash.',[select('algorithm','Algorithm',['SHA-256','SHA-384','SHA-512'],'SHA-256'),line('expected','Expected hash (optional)','',true)],['file hash generator','file checksum'],{files:true})
];
