import {tool,text,line,number,select} from '../shared/definitions.js';
const T=(...args)=>tool('Text','text',...args);
export const textTools=[
 T('text-counter','Word / Character / Reading Counter','Count words, Unicode characters, sentences and paragraphs; estimate reading or speaking time.',[text('input','Text','Hello world.\n\nA second paragraph.'),number('reading','Reading words per minute',200,1,1000),number('speaking','Speaking words per minute',130,1,1000)],['word counter','character counter','sentence counter','paragraph counter','reading time calculator','speaking time calculator','caption character counter','title length checker','meta description length checker']),
 T('case-converter','Case Converter','Convert letter case while keeping the text available to copy or download.',[text('input','Text','hello WORLD. a new sentence.'),select('mode','Case',['UPPERCASE','lowercase','Title Case','Sentence case','Capitalize Words'],'Title Case')],['UPPERCASE converter','lowercase converter','title case converter','sentence case converter','capitalize words']),
 T('line-editor','Line Editor / Text Cleaner','Clean, sort, transform or number text lines without sending the text elsewhere.',[text('input','Text lines','  apple  \nbanana\n\napple'),select('mode','Operation',['Remove Extra Spaces','Remove Line Breaks','Add Line Breaks','Remove Duplicate Lines','Remove Empty Lines','Sort Lines A-Z','Sort Lines Z-A','Reverse Text','Reverse Lines','Text Cleaner','Prefix Each Line','Suffix Each Line','Line Number Generator'],'Remove Duplicate Lines'),line('affix','Prefix or suffix','• ',true),number('width','Words per line (Add Line Breaks)',8,1,1000)],['remove extra spaces','remove line breaks','add line breaks','remove duplicate lines','remove empty lines','sort lines A-Z','sort lines Z-A','reverse text','reverse lines','text cleaner','prefix each line','suffix each line','line number generator']),
 T('text-repeater','Text Repeater','Repeat text with a chosen separator and a bounded output size.',[text('input','Text','Hello'),number('count','Repetitions',3,1,10000),line('separator','Separator',' ',true)]),
 T('find-replace','Find and Replace','Replace literal text occurrences, optionally matching letter case.',[text('input','Text','Hello world, hello again.'),line('find','Find literal text','hello'),line('replacement','Replacement','Hi',true),select('case','Case matching',['Ignore case','Match case'],'Ignore case')]),
 T('text-frequency','Word / Character Frequency','Count repeated words or Unicode characters and display their frequencies.',[text('input','Text','red blue red green blue red'),select('mode','Count',['Words','Duplicate words','Characters'],'Words')],['duplicate word finder','word frequency counter','character frequency counter','keyword frequency counter','keyword density checker']),
 T('text-diff','Text Difference','Compare two texts line by line and display additions and removals.',[text('input','Original text','one\ntwo\nthree'),text('second','Changed text','one\nnew\nthree')],[],{instructions:'Paste original and changed text. Comparison uses line-level longest common subsequence, limited to 500 lines and 100,000 characters per side.'}),
 T('lorem-ipsum','Lorem Ipsum / Random Text','Generate sample prose for layout testing, with an explicit word or paragraph count.',[number('count','Paragraphs',2,1,100),number('length','Words per paragraph',40,1,1000),select('mode','Text type',['Lorem Ipsum','Random test prose'],'Lorem Ipsum')],['lorem ipsum generator','random text generator'],{note:'Generated prose is filler for testing, not factual content.'})
];
