import {tool,text,line,number,select} from '../shared/definitions.js';
const t=(cat,id,name,desc,fields,aliases=[])=>tool(cat,'web',id,name,desc,fields,aliases);
export default [
t('Web','url-tools','URL Parser, Query Builder & UTM Generator','Parse URLs, edit query parameters, build UTM links, or remove common tracking parameters.',[text('input','HTTP(S) URL / link list','https://example.com/page?utm_source=test&name=Alex'),select('mode','Operation',['Parse','Build query','UTM','Clean tracking','Clean link list'],'Parse'),text('params','Query pairs: key=value, one per line','utm_source=newsletter\nutm_medium=email\nutm_campaign=launch',true)],['URL parser','query string parser','query string builder','UTM builder','link cleaner','link list cleaner']),
t('Web','slug-generator','Slug Generator','Generate a normalized lowercase URL slug from text.',[line('input','Text','Hello, CalcHub!')],['URL slug','username slug']),
t('Web','extract-links','Domain, URL & Email Extractor','Extract candidates from supplied text without contacting or validating external sites.',[text('input','Text','Visit https://example.com or email hello@example.com.'),select('mode','Extract',['URLs','Domains','Emails'],'URLs')],['domain extractor','email extractor','URL extractor']),
t('Web','web-reference','HTTP Status & MIME Reference','Look up a small embedded reference for common HTTP statuses and MIME types.',[select('mode','Reference',['HTTP','MIME'],'HTTP'),line('input','Status or extension','404')],['HTTP status reference','MIME type lookup']),
t('Web','social-links','Contact & Sharing Link Generator','Build WhatsApp, Telegram, email, phone, SMS and web sharing links locally.',[select('mode','Link type',['WhatsApp','Telegram','Email','Phone','SMS','Share URL'],'WhatsApp'),line('input','Phone / username / email / URL','1234567890'),text('message','Message','Hello',true),line('subject','Email subject','Hello',true)],['WhatsApp link generator','Telegram link generator','email link','phone link','SMS link','share link']),
t('Web','youtube-links','YouTube Timestamp & Embed Generator','Generate a timestamp link or embed snippet for a supplied YouTube video ID.',[line('input','YouTube video ID or URL','dQw4w9WgXcQ'),number('seconds','Start seconds',90,0,86400),select('mode','Output',['Timestamp link','Embed HTML'],'Timestamp link')],['YouTube timestamp','YouTube embed']),
t('Web','hashtag-generator','Hashtag Formatter','Turn supplied keywords into hashtags; this does not predict trending topics.',[text('input','Keywords separated by commas or lines','local tools, web design, CalcHub')],['hashtag generator'])
];
